### ISSUE TITLE
Operator pod crashes in the middle of the reconcile logic.

### ISSUE THREAD

**Issue by kaushiksrinivas** [operator-framework/operator-sdk#2636] opened 2020-03-10 06:59 UTC
When writing the reconcile logic for a operator, there can be multiple resources to be reconciled.
As an example, a kafka operator reconcile function can call internally
ReconcilePod
ReconcileService
ReconcileConfigMap etc.

now suppose, the pod has been reconciled and just before the service reconcile if the kafka operator pod itself crashes, how do we handle such scenarios ?
Now the pods are updated to desired state but the services are not.

Even if the kafka operator pod comes up again, there is no update in the CRs and hence the reconcile logic is not triggered and is there no way to resume the reconcile logic when ever such operator pod crashes ?
Or at every restart of the operator pod, the reconcile logic is run and Status object of the CR type can be used to figure out if the reconcile must be done or not ?

Also what is the point of having more than one replica for operator itself ?

**Comment by kaushiksrinivas** [comment] 2020-03-10 07:04
@camilamacedo86 Any inputs on this.

**Comment by camilamacedo86** [comment] 2020-03-10 09:19
Hi @kaushiksrinivas, 

Following my comments inline.

> now suppose, the pod has been reconciled and just before the service reconcile if the kafka operator pod itself crashes, how do we handle such scenarios?

By using Operators you can manage the resources, for example, you can read their current state and then, programmatically and dynamically perform operations according to. 

> Now the pods are updated to desired state but the services are not.

You need to check the implementation logic of your project and logs to identify the root cause and solve it. It shows not be something related to SDK but with the specific project that you are using. Then, if you would like to report an issue for this project the correct place will be its repository as speak with its maintainers instead of. 

> Even if the kafka operator pod comes up again, there is no update in the CRs and hence the reconcile logic is not triggered and is there no way to resume the reconcile logic when ever such operator pod crashes ?

If the operator pod is crashing it means that it is facing a fatal error then, to dealing with, is required to check what error is happening and why.  For example, may the errors is that that was not possible to pull the image then the pod will crash and the solution might not be in the operator itself. 

> Or at every restart of the operator pod, the reconcile logic is run and Status object of the CR type can be used to figure out if the reconcile must be done or not ?

The reconcile will trigger when the watched resources are created, deleted and updated. By default the primary resources are watched and then the reconcile will be trigged when the CR is applied, delete and/pr updated.  

> Also what is the point of having more than one replica for operator itself ?

In some scenarios may be required to have a fast response in the failures cases, then instead of waiting for a new pod be built a second one will become to be the leader. 

**NOTE** If you have not the opportunity yet to check it, I'd like to recommend you check the blog post [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) to have a better understanding over how works the reconcile via its exemplification. 

All questions raised are answered in this one. Note that these questions show not specific to SDK but the project used. So,  I am closing this one as sorted out. However, if you still with doubts and questions, please raise a new issue with them. Also, please keep one question, or issue, or feature request per issue raised in the repo in order to allow us better assist you and then fill and provide all information requested in the templates such as versions used, type of operator, error logs, snippet of the code used and etc ... for we are able to reproduce your scenario and understand your needs and help you with.

**Closed by camilamacedo86** 2020-03-10 09:19 UTC

**Comment by kaushiksrinivas** [comment] 2020-03-10 10:03
@camilamacedo86 thanks a lot for the detailed response.
My questions were based on the use case where, the operator pod crashes before the reconcile code was complete and ways to re run the reconcile code to complete the process when operator pod comes up again.

I observe that, if i delete the operator pod. Once the pod comes back up, it is reading the state of the CR and running the reconcile logic all over again. So this behavior will take care of re running the reconcile code and get the CR to the desired state right ?

**Comment by camilamacedo86** [comment] 2020-03-10 10:45
Hi @kaushiksrinivas,

> My questions were based on the use case where, the operator pod crashes before the reconcile code was complete and ways to re run the reconcile code to complete the process when operator pod comes up again. 

So, it means that it is facing some fatal error. Then, is required to check the logic implementation used and why it happens. 

> I observe that, if i delete the operator pod and change the CR spec before the operator pod comes up. Once the pod comes back up, it is reading the state of the CR and running the reconcile logic all over again. So this behavior will take care of re running the reconcile code and get the CR to the desired state right ?

Yes, it is expected. When the operator starts it will WATCH the cluster and the resources which are. implemented to be observed. So, as described above by default in the scaffold implementation you will see a watch implementation for the primary resource (CR), [eg.](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L46), which means that if a CR is installed in the cluster then the operator will trigger the reconcile when it starts. 

I'd like to recommend you check the blog post [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) to have a better understanding over how it works.

**Comment by kaushiksrinivas** [comment] 2020-03-10 10:48
Thank you for the quick response.
