### ISSUE TITLE
Clientset generation broken after 0.0.7

### ISSUE THREAD

**Issue by benceszikora** [operator-framework/operator-sdk#678] opened 2018-10-31 17:47 UTC
I am trying to generate a clientset for my CRD so that I can use it outside the operator. Is there a way to do this with the current version of the SDK?

I used this hack previously on 0.0.7:
```
vendor/k8s.io/code-generator/generate-groups.sh all github.com/user/memcached-operator/pkg/generated github.com/user/memcached-operator/pkg/apis memcached:v1alpha1
```
This however seems to have broken on master (ab09a3d). The problem seems to be that the generated client expects to have the `AddToScheme` function in the api imported from: ```github.com/user/memcached-operator/pkg/apis/memcached/v1alpha1```
However, in the latest version of the operator-sdk, it's one package up in `apis.go`:

```
└── memcached
    ├── addtoscheme_memcached_v1alpha1.go
    ├── apis.go
    └── v1alpha1
        ├── doc.go
        ├── register.go
        ├── memcached_types.go
        └── zz_generated.deepcopy.go
```

Am I missing something here? Or should the function be somehow moved back into `v1alpha1`?

Thanks!

**Environment**
* operator-sdk version: ab09a3d

**Comment by LiliC** [comment] 2018-11-01 10:15
@benceszikora Thanks for opening this. The operator-sdk has gone through API changes, have you seen the [migration-guide](https://github.com/operator-framework/operator-sdk/blob/6d870c9ead65a567a7bda76d91b42cef4f146f57/doc/migration/v0.1.0-migration-guide.md)? Hopefully following that it should make things more clear, if not feel free to come back to the issue and we can answer any further questions!

**Comment by paulcostinean** [comment] 2018-11-01 16:15
Worth mentioning that in order for the client to be generated at all, the `
// +genclient` tag has to be added [here](https://github.com/operator-framework/operator-sdk/blob/master/test/test-framework/pkg/apis/cache/v1alpha1/memcached_types.go#L32) (directly above the type wrapped in the API).

**Comment by hasbro17** [comment] 2018-11-02 17:47
@benceszikora Since the SDK only supports `deepcopy-gen` all the other generators probably won't work on pkg/apis for `0.1.0`. We could add support for those if it makes sense.

In the meanwhile you can still hack around it by adding the `// +genclient` tag in your `memcached_types.go`.
```Go
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Memcached is the Schema for the memcacheds API
// +k8s:openapi-gen=true
type Memcached struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MemcachedSpec   `json:"spec,omitempty"`
	Status MemcachedStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// MemcachedList contains a list of Memcached
type MemcachedList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Memcached `json:"items"`
}
```
And as you pointed out we're missing `AddToScheme` in register.go. So you'll need to add that in:
```Go
AddToScheme = SchemeBuilder.AddToScheme
```

And then try:
```sh
vendor/k8s.io/code-generator/generate-groups.sh all github.com/user/memcached-operator/pkg/generated github.com/user/memcached-operator/pkg/apis memcached:v1alpha1
```

Other generators like `lister-gen`, `defaulter-gen` might need other tags and methods to be present. We'll look into supporting all generator types by default.

**Comment by indradhanush** [comment] 2018-11-21 02:37
@hasbro17 I was running into the same issue and tried your fix. I was able to generate the client set, but some bits of it still looks incorrect to me. For eg: https://github.com/indradhanush/debug-operator/blob/7ad260664fcb9626dc7a764e9974d7abab8b248e/pkg/client/clientset/versioned/typed/foo/v1alpha1/debuglist.go#L43

I created the above repo to easily reproduce the issue. Am I missing something?

**Comment by indradhanush** [comment] 2018-11-21 07:37
My apologies. It appears that I had the tags placed above the wrong struct. This commit seems to have fixed it for me: https://github.com/indradhanush/debug-operator/commit/0cccb2a426ffdf336815f308d6ce237a55f5eda3

**Comment by LiliC** [comment] 2019-04-26 08:35
I think this can be closed as it's outdated.

**Closed by LiliC** 2019-04-26 08:35 UTC
Labels: docs, kind/feature

**Comment by wreed4** [comment] 2019-08-19 15:14
@LiliC What is the best practice for generating a golang client for CRDs produced with the operatorSDK?? It appears no client is automatically generated at this point.

**Comment by hasbro17** [comment] 2019-08-19 22:55
@wreed4 The SDK will most likely not support generating typed clients(nor listers,informers) for your CRD since the expectation is to use the controller-runtime's dynamic client to interact with your CRD objects.
https://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.md

If you do have a use case that can't be fulfilled by the dynamic client then please feel free to follow up at #1646.

In the meanwhile if you do need to generate a client-set for some reason then you can use the upstream [k8s code-generator](https://github.com/kubernetes/code-generator). There's a [generate-groups.sh](https://github.com/kubernetes/code-generator/blob/master/generate-groups.sh#L26-L38) helper script that you can run against your `pkg/apis/...` to generate client/lister/informer for your CRD.

**Comment by wreed4** [comment] 2019-08-23 19:19
@hasbro17 I should have been more explicit I think, our use-case is to interact with these CRDs from various other repositories/microservices that are not themselves operators.  Is requiring the controller-runtime as a dependency still the best-practice you suggest? 

Put slightly differently, we have developed an operator and now we are developing several microservices that are themselves _clients_ of that operator interacting with the CRs it manages (CRUD operations).
