### ISSUE TITLE
Errors/warning after a resource has been deleted

### ISSUE THREAD

**Issue by rhuss** [operator-framework/operator-sdk#344] opened 2018-07-12 10:24 UTC
After we have deleted a watched resource, after some time the following error appears in the logs:

```
time="2018-07-12T09:27:24Z" level=info msg="Syndesis resource example installed successfully"
time="2018-07-12T09:28:39Z" level=info msg="Syndesis resource example deleted"
ERROR: logging before flag.Parse: W0712 09:42:41.951609       1 reflector.go:341] github.com/syndesisio/syndesis-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.go:80: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
ERROR: logging before flag.Parse: W0712 09:57:00.991730       1 reflector.go:341] github.com/syndesisio/syndesis-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.go:80: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
ERROR: logging before flag.Parse: W0712 10:08:07.055364       1 reflector.go:341] github.com/syndesisio/syndesis-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.go:80: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
```

Is this normal or how could this be prevented ? // @nicolaferraro

**Comment by eivantsov** [comment] 2018-10-11 12:44
In my case objects are created and after some time, I see this error. Nothing gets deleted.

**Comment by estroz** [comment] 2018-12-19 22:51
@rhuss @eivantsov @michalrabinowitch can you post what SDK versions you're using (`operator-sdk --version`)? Do these errors still come up?

**Comment by schen1** [comment] 2018-12-20 12:07
@estroz It happens to my customer as well, they are using version 0.2.1

**Comment by odra** [comment] 2019-02-07 17:18
Did a quick search in kubernetes repo and found this: https://github.com/kubernetes/kubernetes/issues/72187

Is this log message the expected behavior?

**Comment by eivantsov** [comment] 2019-02-07 17:28
It happened to me on version 0.0.6. Now, with 0.3.0, it's ok

**Comment by shawn-hurley** [comment] 2019-02-08 13:51
Hey everyone,

This is happening because the API server is closing the watch. The informer will automatically connect because the API server closing watches is normal and expected behavior. In this case, what happens if when the informer attempts to re-establish the watch, it is denied because the resource version is to low. The Informer will then do a List request and use the new resource version from the list to re-establish a watch. 

This is completely expected behavior from my investigation. I think that we should pin this issue and close @joelanford @hasbro17.

We could attempt to quiet this error but I worry about attempting to stifle errors from the `client-go` code and missing errors that we actually want.

**Comment by hasbro17** [comment] 2019-02-08 19:38
Yes, re-establishing the watch for objects that aren't updated for a long time seems to be the expected behavior from what I can tell.
I don't think we should be stifling this error as well since the error suggests the watchers are actually operating properly by re-attempting the watch.

Possibly related but from https://github.com/openshift/origin/issues/21636 it seems like this issue was fixed on 1.13.0.

**Comment by matihost** [comment] 2019-02-14 17:03
I don't know whether it is related 

Failed to watch *unstructured.Unstructured: the server does not allow this method on the requested resource

My play do no use k8s so... it in theory should not watch anything..

**Comment by LiliC** [comment] 2019-02-15 11:47
@matihost You need to pass the specific object you want to watch.

> My play do no use k8s so... it in theory should not watch anything..

Can you explain this a bit more?

**Comment by matihost** [comment] 2019-02-21 12:35
Created https://github.com/operator-framework/operator-sdk/issues/1123
because my case is different.

My play just creates various object like (ResourceQuota, RoleBinding) in various projects.

>My play do no use k8s so... it in theory should not watch anything..
I stopped using k8s module, and use oc/kubectl command to interact with cluster...
Essentially I just want that ansible opeartor does not watch anything except CR object (for apply/delete 
events).
I thought that this watching magic is done via k8s - but it seems it is bigger magic... relaed to K8S API not the client used to interact with cluster.

I a nutshell I reference to: https://github.com/operator-framework/operator-sdk/issues/1051#issuecomment-460862599 - where I post that watching things in cluster - when idempotent Ansible playbook are used to apply/finalizer - is not the best idea and cause more problems than good.

**Comment by shawn-hurley** [comment] 2019-02-21 13:57
> you need to pass the specific object you want to watch, the `unstructured.Unstructured` is not allowed one

This is actually supported in the controller-runtime.

> ERROR: logging before flag.Parse: E0214 17:04:01.610105 1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: Failed to watch *unstructured.Unstructured: the server does not allow this method on the requested resource

This is a different error than the one in this bug. and we should track it differently. I believe we can use #1123 to do this.

**Closed by shawn-hurley** 2019-02-21 13:57 UTC
Labels: bug
