### ISSUE TITLE
[Bug] Quickstart documentation page does not work correctly

### ISSUE THREAD

**Issue by d3287t328** [operator-framework/operator-sdk#6467] opened 2023-06-13 15:23 UTC
The process at this page https://sdk.operatorframework.io/docs/building-operators/helm/quickstart/ is broken at the step 

```
make docker-build docker-push IMG="example.com/nginx-operator:v0.0.1"
```

The error is 

```
make docker-build docker-push IMG="example.com/nginx-operator:v0.0.1"
docker build -t example.com/nginx-operator:v0.0.1 .
[+] Building 1.6s (9/9) FINISHED                                                       
 => [internal] load build definition from Dockerfile                              0.2s
 => => transferring dockerfile: 233B                                              0.1s
 => [internal] load .dockerignore                                                 0.2s
 => => transferring context: 2B                                                   0.0s
 => [internal] load metadata for quay.io/operator-framework/helm-operator:v1.29.  0.5s
 => [1/4] FROM quay.io/operator-framework/helm-operator:v1.29.0@sha256:ba54e9efb  0.0s
 => [internal] load build context                                                 0.2s
 => => transferring context: 844B                                                 0.0s
 => CACHED [2/4] COPY watches.yaml /opt/helm/watches.yaml                         0.0s
 => CACHED [3/4] COPY helm-charts  /opt/helm/helm-charts                          0.0s
 => CACHED [4/4] WORKDIR /opt/helm                                                0.0s
 => exporting to image                                                            0.1s
 => => exporting layers                                                           0.0s
 => => writing image sha256:461a6185f7ecd1d5aed8eeb91c6c2163623335b5e9a680a2592d  0.0s
 => => naming to example.com/nginx-operator:v0.0.1                                0.0s
docker push example.com/nginx-operator:v0.0.1
The push refers to repository [example.com/nginx-operator]
5f70bf18a086: Preparing 
cc3bb37a120f: Preparing 
4d978b90f941: Preparing 
d741ecd5168f: Preparing 
7f6acc525cf9: Preparing 
cb46614623b8: Waiting 
55ea6d5a354e: Waiting 
error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n\t<head>\n\t\t<title>404 - Not Found</title>\n\t</head>\n\t<body>\n\t\t<h1>404 - Not Found</h1>\n\t\t<script type=\"text/javascript\" src=\"//obj.ac.bcon.ecdns.net/ec_tpm_bcon.js\"></script>\n\t</body>\n</html>\n"
make: *** [Makefile:84: docker-push] Error 1
```

I am not sure where `error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: ` is being generated as I do not see a reference in the makefile. i tried doing this procedure a few times and the same result happens when using the Quickstart.

**Comment by kensipe** [comment] 2023-06-26 18:33
@d3287t328 the documentation includes the following:

>  example.com is used as the registry Docker Hub namespace in these examples. Replace it with another value if using a different registry or namespace.

The `example.com` is a real web site but was only used in the documentation as a placeholder for a real Docker Hub namespace.   We believe if you switch out that name with a valid value it will work.

Let us know if you run into another issue.  I'm closing for now, but feel free to reopen if the issue isn't resolved.

**Closed by kensipe** 2023-06-26 18:33 UTC
Labels: good first issue
