### ISSUE TITLE
go operator v1.0.0 instructions are failing on Expected in: flat namespace

### ISSUE THREAD

**Issue by arivatibm** [operator-framework/operator-sdk#3775] opened 2020-08-23 10:56 UTC
## Bug Report

**What did you do?**
followed the quickstart instructions for creating a go operator using operator v1.0
 
**What did you expect to see?**
all instructions working without errors

**What did you see instead? Under which circumstances?**
getting this error :
% make docker-build docker-push IMG=xxxxxxxxxx/memcached:test
/Users/ariv/.go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
/Users/ariv/.go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
mkdir -p /Users/ariv/git/test/memcached-operator/testbin
test -f /Users/ariv/git/test/memcached-operator/testbin/setup-envtest.sh || curl -sSLo /Users/ariv/git/test/memcached-operator/testbin/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/master/hack/setup-envtest.sh
source /Users/ariv/git/test/memcached-operator/testbin/setup-envtest.sh; fetch_envtest_tools /Users/ariv/git/test/memcached-operator/testbin; setup_envtest_env /Users/ariv/git/test/memcached-operator/testbin; go test ./... -coverprofile cover.out
**dyld: Symbol not found: 
  Referenced from: /Users/ariv/git/test/memcached-operator/testbin/bin/kube-apiserver
  Expected in: flat namespace

make: *** [test] Error 134**

**Environment**
* operator-sdk version: 

1.0.0

* go version: 

1.15 darwin/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}

* Kubernetes cluster kind: 

eventually want to deploy it to openshift v4.3.28_1532

* Are you writing your operator in ansible, helm, or go?

Go

**Comment by camilamacedo86** [comment] 2020-08-24 09:43
Hi @arivatibm, 

Could you please try to follow up the steps again? See `**dyld: Symbol not found:`. Shows that you added some invalid characters in your project.  You might by mistake make something wrong in the copy and paste. 

Also, note that ` make docker-build docker-push IMG=xxxxxxxxxx/memcached:test` and see the quickstart note;

<img width="839" alt="Screen Shot 2020-08-24 at 10 43 33" src="https://user-images.githubusercontent.com/7708031/91029459-b1726080-e5f6-11ea-9f52-39eedc0366cc.png">

You need to build and push the IMG to a valid and public repository. For example, you can check the mine to do tests: https://quay.io/repository/camilamacedo86/memcached-operator?tab=tags.

It would be `make docker-build docker-push IMG=quay.io/camilamacedo86/memcached-operator:0.0.1`.

**Comment by camilamacedo86** [comment] 2020-08-24 09:45
Also, I m closing this one because by following the steps we are unable to reproduce your issue. It shows that you really add some wrong characters in the copy/paste action and you are not pushing the image to a valid and public repository. However, feel free to ping us if you still requiring some help with it.

**Closed by camilamacedo86** 2020-08-24 09:45 UTC
