### ISSUE TITLE
Operator with 2 controllers not passing new liveness probe (/healthz)

### ISSUE THREAD

**Issue by slopezz** [operator-framework/operator-sdk#3216] opened 2020-06-10 15:28 UTC
## Bug Report

**What did you do?**

Using last operator-sdk `v0.18.0/v0.18.1` `ansible` version with 2 controllers on watches.yaml.

**What did you expect to see?**

Operator container passing correctly liveness probe (:6789/healthz).

**What did you see instead? Under which circumstances?**

Operator pod shows status `CrashLoopBackOff` because it didnt pass liveness probe:
```
Liveness probe failed: Get http://10.129.7.187:6789/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Container 3scale-saas-operator failed liveness probe, will be restarted
```

If I try to manually access to liveness probe endpoint, it does not respond (timeout), while if I repeat the same test, but with  a single controller on watches.yaml, it responds with OK:
``` 
sh-4.4$ curl localhost:6789/healthz
ok
```

**Environment**
* operator-sdk version: `operator-sdk version: "v0.18.0" and operator-sdk version: "v0.18.1"`

* Kubernetes version information:
```
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"1fce0fd", GitTreeState:"clean", BuildDate:"2020-02-17T19:44:53Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: `OCP 4.3.3`

* Are you writing your operator in ansible, helm, or go? `Ansible`

**Additional context**

I don't know if it may be related, but since I upgraded to operator-sdk `v0.18.0/v0.18.1`, I see on operator logs random  Throttling errors from other apis (not related to my operator), example:

```
I0610 15:12:37.039566 8 request.go:621] Throttling request took 1.038226336s, request: GET:https://172.30.0.1:443/apis/quota.openshift.io/v1?timeout=32s

I0610 15:12:47.902397 8 request.go:621] Throttling request took 1.046797531s, request: GET:https://172.30.0.1:443/apis/autoscaling/v2beta2?timeout=32s
```
It didn't happen with operator-sdk `0.17.1`.

Maybe this last point is a different not related issue.

**Comment by camilamacedo86** [comment] 2020-06-11 12:13
Hi @slopezz, 

**I could NOT reproduce any issue reported by you here with the ansible Memcached sample**. See:

- upgrade the ansible sample to use 0.18. https://github.com/operator-framework/operator-sdk-samples/pull/128/files
- Then, I use the command `operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=AppService`to create a new kind and it will scaffold a new watch for its role as well; 

```yaml
---
- version: v1alpha1
  group: cache.example.com
  kind: Memcached
  role: memcached


- version: v1alpha1
  group: cache.example.com
  kind: AppService
  role: appservice
```

Also, note that `GET:https://172.30.0.1:443/apis/integreatly.org/v1alpha1?timeout=32s `shows be specific to your local environment/project which appears have thehttps://github.com/integr8ly installed. 

By looking at your watches implementation [here](https://github.com/operator-framework/operator-sdk/issues/3216#issuecomment-642159024) shows that it is not accurate too. See that both are using the same kind. 

Please, let us know if the above information is enough for you to figure out what is wrong with your project. Otherwise, could you provide the steps for we are able to reproduce it with the Memcached Sample?

**Comment by slopezz** [comment] 2020-06-11 15:46
Hi @camilamacedo86 ,

Thank you very much for trying to check it!

I have checked your comment, and I guess my watches file is correct, there are 2 different kinds (AutoSSL  and Backend):
```yaml
---
- version: v1alpha1
  group: saas.3scale.net
  kind: AutoSSL
  role: autossl

- version: v1alpha1
  group: saas.3scale.net
  kind: Backend
  role: backend
```

Checking these weird lines (on the first example I exposed it was with api `apis/integreatly.org/v1alpha1`, but on any new pod created it actually shows any api on the cluster , some of them not used by the operator):

```
I0611 12:03:25.345335 7 request.go:621] Throttling request took 1.046533228s, request: GET:https://172.30.0.1:443/apis/apiextensions.k8s.io/v1?timeout=32s
```

Trying to find the origin of that line (taking into account that even the logging format is different from the `operator-sdk` logs), it says the error comes from `request.go Line 621`.

I have cloned `operator-sdk` repository , and vendor all go modules, to check where it comes from:

```bash
$ cd /tmp/
$ git clone https://github.com/operator-framework/operator-sdk.git
$ cd operator-sdk
$ go mod vendor
$ find . -name request.go
./vendor/k8s.io/client-go/rest/request.go
./vendor/github.com/go-openapi/runtime/request.go
./vendor/github.com/emicklei/go-restful/request.go

$ sed -n 617,623p ./vendor/k8s.io/client-go/rest/request.go
// Infof will write a log message at each logLevel specified by the reciever's throttleSettings
// as long as it hasn't written a log message more recently than minLogInterval.
func (b *throttledLogger) Infof(message string, args ...interface{}) {
	if logLevel, ok := b.attemptToLog(); ok {
		klog.V(logLevel).Infof(message, args...)
	}
}
```
- Github: https://github.com/kubernetes/client-go/blob/v0.18.2/rest/request.go#L621 
-  Introduced on commit https://github.com/kubernetes/client-go/commit/69a103b2cebed0289fb822b08dc0e273b883dc04

And it seems that comes from `client-go`, which I guess is a very important module used by `operator-sdk`, so apparently seems a legit log line that has nothing to be with `operator-sdk`. 


I have deployed the operator with `v0.18.1` on a [kind](https://kind.sigs.k8s.io/) cluster on my machine (with nothing deployed), and these weird lines don't appear (like in your test):

```json
{"level":"info","ts":1591886823.714379,"logger":"cmd","msg":"Go Version: go1.13.12"}
{"level":"info","ts":1591886823.7146208,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1591886823.7146966,"logger":"cmd","msg":"Version of operator-sdk: v0.18.1"}
{"level":"info","ts":1591886823.7149978,"logger":"cmd","msg":"Watching single namespace.","Namespace":"3scale-example"}
{"level":"info","ts":1591886824.0178204,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1591886824.0180988,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"WORKER_AUTOSSL_SAAS_3SCALE_NET","default":1}
{"level":"info","ts":1591886824.018119,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_AUTOSSL_SAAS_3SCALE_NET","default":2}
{"level":"info","ts":1591886824.0181496,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"WORKER_BACKEND_SAAS_3SCALE_NET","default":1}
{"level":"info","ts":1591886824.0181582,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_BACKEND_SAAS_3SCALE_NET","default":2}
{"level":"info","ts":1591886824.0181847,"logger":"cmd","msg":"Environment variable not set; using default value","Namespace":"3scale-example","envVar":"ANSIBLE_DEBUG_LOGS","ANSIBLE_DEBUG_LOGS":false}
{"level":"info","ts":1591886824.0181944,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"saas.3scale.net","Options.Version":"v1alpha1","Options.Kind":"AutoSSL"}
{"level":"info","ts":1591886824.0182686,"logger":"cmd","msg":"Environment variable not set; using default value","Namespace":"3scale-example","envVar":"ANSIBLE_DEBUG_LOGS","ANSIBLE_DEBUG_LOGS":false}
{"level":"info","ts":1591886824.018277,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"saas.3scale.net","Options.Version":"v1alpha1","Options.Kind":"Backend"}
{"level":"info","ts":1591886824.0183423,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1591886824.3314967,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1591886824.336912,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1591886825.2787492,"logger":"metrics","msg":"Metrics Service object created","Service.Name":"threescale-saas-operator-metrics","Service.Namespace":"3scale-example"}
{"level":"info","ts":1591886825.5810869,"logger":"cmd","msg":"Could not create ServiceMonitor object","Namespace":"3scale-example","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1591886825.5811234,"logger":"cmd","msg":"Install prometheus-operator in your cluster to create ServiceMonitor objects","Namespace":"3scale-example","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1591886825.5900104,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"info","ts":1591886825.59058,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1591886825.590711,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"backend-controller","source":"kind source: saas.3scale.net/v1alpha1, Kind=Backend"}
{"level":"info","ts":1591886825.5907664,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"autossl-controller","source":"kind source: saas.3scale.net/v1alpha1, Kind=AutoSSL"}
{"level":"info","ts":1591886825.6916318,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"backend-controller"}
{"level":"info","ts":1591886825.6916597,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"backend-controller","worker count":1}
{"level":"info","ts":1591886825.6927152,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"autossl-controller"}
{"level":"info","ts":1591886825.692727,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"autossl-controller","worker count":1}
```

So it seems that maybe the OpenShift cluster I am using to deploy my operator, seems a bit API overloaded (actually I have deployed it on a different Openshift cluster, and these lines appear also, I guess both may be quite stressed).

So the only pending question is: can you confirm if it is expected to show that log lines coming from `client-go` on operator logs?

**Comment by camilamacedo86** [comment] 2020-06-11 20:35
Hi @slopezz, 

> So the only pending question is: can you confirm if it is expected to show that log lines coming from client-go on operator logs? 

The client-go as you checked is used by the operator. So, its info/warn/errors in many scenarios are thrown to the operator logs. Then, the answer to your question is yes. 

Also, I could confirm that the root cause for the logs is the config your local setup where you are running the project. See: 

```
if latency > extraLongThrottleLatency {
		// If the rate limiter latency is very high, the log message should be printed at a higher log level,
		// but we use a throttled logger to prevent spamming.
		globalThrottledLogger.Infof("Throttling request took %v, request: %s:%s", latency, r.verb, r.URL().String())
	}
```
From: https://github.com/kubernetes/client-go/blob/3d5c80942cce510064da1ab62c579e190a0230fd/rest/request.go#L574-L575

However, note that it is not an error just an info log when the latency is too high to do the requests. 

In this way, shows that all is sorted out here. Really thank you for being engaged and work together with me to help to troubleshoot your scenario. I am closing this one, however, feel free to ping us to re-open if you see that it is required.

**Closed by camilamacedo86** 2020-06-11 20:35 UTC
Labels: ansible-operator, triage/needs-information

**Comment by christianh814** [comment] 2020-06-19 01:03
I just ran into this on 0.18.1

```
$ operator-sdk version
operator-sdk version: "v0.18.1", commit: "7bf7b6886d647dc202525daec16fab67dcc52a3d", kubernetes version: "v1.18.2", go version: "go1.13.6 linux/amd64"
```

in the events

```
5m26s       Normal    Created             pod/pricelist-operator-58c4467966-nf9wn    Created container pricelist-operator
5m26s       Normal    Started             pod/pricelist-operator-58c4467966-nf9wn    Started container pricelist-operator
5m27s       Warning   Unhealthy           pod/pricelist-operator-58c4467966-nf9wn    Liveness probe failed: Get http://10.130.2.69:6789/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

My pod is crashlooping

```
$ oc get pods
NAME                                  READY   STATUS             RESTARTS   AGE
pricelist-operator-58c4467966-5z4vz   0/1     CrashLoopBackOff   6          4m30s
```

**Comment by christianh814** [comment] 2020-06-19 01:12
So changing the livenessProbe to this worked...

```
         livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
```

Maybe the defaults the SDK provides are too aggressive?

**Comment by madorn** [comment] 2020-06-19 15:42
@christianh814 confirmed. Depending on what user is writing into their operator which affects initialization time,  this may or not be an issue. Recommended fix to is to loosen up the liveness probe parameters.

**Comment by camilamacedo86** [comment] 2020-06-19 16:34
Here wee discussed many issues and scenarios. So, I raised a new issue as the proposed values: https://github.com/operator-framework/operator-sdk/issues/3267
