### ISSUE TITLE
The ownerReferences on deployed resources are missing

### ISSUE THREAD

**Issue by hbfjk** [operator-framework/operator-sdk#2623] opened 2020-03-05 12:17 UTC
We are using operator framework to deploy our own custom resource, we deployed deployment, statefulset, job on K8s env, but the ownerReferences to the custom resource TESTCluster are missed for all deployments, statefulsets, jobs.
"ownerReferences": [{"apiVersion": "icp4a.ibm.com/v1", "kind": "TESTCluster",

After the further investigation, the operator poxy can not determine if it is virtual resources, so it will break before to inject the owner reference, see https://github.com/operator-framework/operator-sdk/blob/947a464dbe968b8af147049e76e40f787ccb0847/pkg/ansible/proxy/inject_owner.go

{"level":"info","ts":1574998033.6222746,"logger":"proxy","msg":"Unable to determine if virtual resource","gvk":"apps/v1, Kind=Deployment"}
{"level":"info","ts":1574998034.0587363,"logger":"proxy","msg":"Unable to determine if virtual resource","gvk":"/v1, Kind=Secret"}

Why it unable to determine if it is virtual resource? or any idea to debug it?

**Comment by fabianvf** [comment] 2020-03-06 19:52
That is very strange, what version of the operator-sdk and kubernetes are you using? Can you share your full (or at least more) of your logs as well, in case there's some additional information there?

With that failure it looks like it's possible that the discovery client did not properly find all API resources, are the discovery APIs restricted in your cluster? (https://github.com/operator-framework/operator-sdk/blob/947a464dbe968b8af147049e76e40f787ccb0847/pkg/ansible/proxy/proxy.go#L347)

I'm also not sure if we're doing the right thing here, does anyone know if it is true that virtual resources can't have ownerReferences? If they can we should move this check to after ownerReference injection.

**Comment by kramvan1** [comment] 2020-03-10 17:56
@fabianvf   We are also seeing this issue sometimes.   Created a test ansible operator with the SDK v15.2.

In the failing case, the deployment resource does not have the ownerReference added.
Logs:
```
+ kubectl logs -n ibm-operators -l name=stub-operator -c operator

--------------------------- Ansible Task StdOut -------------------------------

TASK [stub-operator : Create stub deployment from deployment yaml] *************
task path: /opt/ansible/roles/stub-operator/tasks/main.yml:2

-------------------------------------------------------------------------------
{"level":"info","ts":1583838619.482889,"logger":"logging_event_handler","msg":"[playbook task]","name":"stub-operator","namespace":"stub-namespace","gvk":"stub-operator.example.com/v1alpha1, Kind=stuboperator","event_type":"playbook_on_task_start","job":"605394647632969758","EventData.Name":"stub-operator : Create stub deployment from deployment yaml"}
{"level":"info","ts":1583838623.9613588,"logger":"proxy","msg":"Unable to determine if virtual resource","gvk":"apps/v1, Kind=Deployment"}
{"level":"info","ts":1583838624.4180446,"logger":"runner","msg":"Ansible-runner exited successfully","job":"605394647632969758","name":"stub-operator","namespace":"stub-namespace"}
```

In the success case the ownerReference is there
```
 ownerReferences:
    - apiVersion: stub-operator.example.com/v1alpha1
      kind: stuboperator
      name: stub-operator
      uid: c2b97cda-27d5-43ed-b77e-0898934269af
```
the logs:
```
+ kubectl -n ibm-operators logs -l name=stub-operator -c operator
{"level":"info","ts":1583861782.4056835,"logger":"logging_event_handler","msg":"[playbook task]","name":"stub-operator","namespace":"stub-namespace","gvk":"stub-operator.example.com/v1alpha1, Kind=stuboperator","event_type":"playbook_on_task_start","job":"7504504064263669287","EventData.Name":"Gathering Facts"}
{"level":"info","ts":1583861784.2601316,"logger":"logging_event_handler","msg":"[playbook task]","name":"stub-operator","namespace":"stub-namespace","gvk":"stub-operator.example.com/v1alpha1, Kind=stuboperator","event_type":"playbook_on_task_start","job":"7504504064263669287","EventData.Name":"stub-operator : Create stub deployment from deployment yaml"}

--------------------------- Ansible Task StdOut -------------------------------

TASK [stub-operator : Create stub deployment from deployment yaml] *************
task path: /opt/ansible/roles/stub-operator/tasks/main.yml:2

-------------------------------------------------------------------------------
{"level":"info","ts":1583861786.5094986,"logger":"runner","msg":"Ansible-runner exited successfully","job":"7504504064263669287","name":"stub-operator","namespace":"stub-namespace"}
```

Seems like a possible timing issue.

There should be the error context added to the message here: https://github.com/operator-framework/operator-sdk/blob/ad1d4d1953abf22c336f67198fc23a489c0f4fdb/pkg/ansible/proxy/inject_owner.go#L85
and here: https://github.com/operator-framework/operator-sdk/blob/ad1d4d1953abf22c336f67198fc23a489c0f4fdb/pkg/ansible/proxy/inject_owner.go#L77

**Comment by fabianvf** [comment] 2020-03-10 19:09
Great information, thanks for the follow up. Separately from fixing this, I wonder if we should be failing the request in the case that we can't determine whether it's a virtual resource, since recovering from a created resource without an ownerReference is going to require manual steps.

**Comment by kramvan1** [comment] 2020-03-10 19:27
@fabianvf      Yes, failing seems like the right change as it does mean manual cleanup steps.

No sure what the timing issue is, but seems related to the resource cache being queried here.  

BTW, I put up a PR (above) to help with the logging around this a bit.

**Comment by kramvan1** [comment] 2020-04-13 20:50
@ecordell Would be nice to get this timing issue looked at.

**Comment by estroz** [comment] 2020-05-28 19:28
@hbfjk @kramvan1 now that #3112 has been merged, the proxy will log a 500 error instead of creating resources without an ownerRef. From the PR:

>This seems to be caused by some kind of race condition, but the result is that resources that should have ownerReferences injected do not, preventing dependent watches from being properly established and preventing garbage collection from working properly.

The lack of ownerRefs may be network related. Feel free to ping/re-open this issue if you see related problems.

**Closed by estroz** 2020-05-28 19:28 UTC
Labels: ansible-operator, help wanted, kind/bug, triage/needs-information

**Comment by kramvan1** [comment] 2020-05-28 21:19
@estroz   Does the 500 mean there will eventually be another attempt/loop on this to get it right?

**Comment by estroz** [comment] 2020-05-28 21:24
@kramvan1 correct.

**Comment by relyt0925** [comment] 2020-11-10 22:44
@estroz we are able to replicate this specifically when an independent apiservice (that does not contain the CRD) cannot be accessed. We can replicate this on a regular basis when that is the case.


```
kubectl describe apiservice v1beta1.metrics.k8s.io
Message: failing or missing response from https://IPAddress:4443/apis/metrics.k8s.io/v1beta1: Get https://IPAddress:4443/apis/metrics.k8s.io/v1beta1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Reason: FailedDiscoveryCheck
```

Something like that  is a good example.

If there's logs you would like me to gather let me know. I will also try to get more logs of what specifically is failing in this situation.

**Comment by relyt0925** [comment] 2020-11-10 22:49
I believe the issue is there's no "silent fail" when a specific API Service cannot be looked up:
https://github.com/operator-framework/operator-sdk/blob/947a464dbe968b8af147049e76e40f787ccb0847/pkg/ansible/proxy/proxy.go#L301-L328

Basically that means if one APIService fails the entire operator cannot function. However, in this case if the operator were able to disregard that the metrics service APIService was down (it has no impacts to what the operator is trying to do) it would be able to proceed with it's operation.
