### ISSUE TITLE
scorecard - allow initContainer image to be configurable by user

### ISSUE THREAD

**Issue by jmccormick2001** [operator-framework/operator-sdk#5066] opened 2021-07-16 19:15 UTC
## Feature Request

https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/testpod.go#L36

in scorecard today,  it uses a hard-coded image name for the initContainer when doing the untar.

For some environments, accessing dockerhub is not allowed, ideally we would have a means
to override the initContainer image to be used with something else (e.g. ubi-minimal). 

#### Describe the solution you'd like.

I'd like to see in the config.yaml file and/or the command line a configurable initContainer image
name so that users can override the default value if they wish.

@scoheb 

/language go

**Comment by jberkhahn** [comment] 2021-07-19 18:29
This is a dupe of #4886. Closing this is favor of that issue.

**Closed by jberkhahn** 2021-07-19 18:29 UTC
Labels: scorecard
