### ISSUE TITLE
Upgrade guide for 0.17.x missing

### ISSUE THREAD

**Issue by k-wall** [operator-framework/operator-sdk#2984] opened 2020-05-07 08:46 UTC
Hello,

I want to move our app to 0.17.0. I refer to:

https://github.com/operator-framework/operator-sdk/blob/v0.17.0/doc/migration/version-upgrade-guide.md

however, I notice there is no section for 0.17.x.  Previously I'd been following your 'Pinning' advice from this page, so I'm left wondering what is correct for 0.17.x.

## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

Documentation question.

## Question

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**

Upgrading from v0.15.1 to 0.17.0.

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by camilamacedo86** [comment] 2020-05-07 10:19
HI @k-wall, 

It has been migrating the docs for the website. See: https://sdk.operatorframework.io
The guide is here: https://sdk.operatorframework.io/docs/migration/version-upgrade-guide/#v017x

I will keep it open for we are able to update the links in the release notes with.

**Comment by k-wall** [comment] 2020-05-07 11:39
@camilamacedo86 thank you for the rapid response.

**Comment by rcernich** [comment] 2020-05-07 13:23
I tried following the process for upgrading to v0.17 and was unsuccessful.  It seems the kubernetes dependencies may need to be updated too.  I was getting the following errors running `go mod vendor`:

```
github.com/maistra/istio-operator/pkg/controller/common/helm imports
	k8s.io/client-go/kubernetes/scheme imports
	k8s.io/api/discovery/v1beta1: module k8s.io/api@latest (v0.18.2) found, but does not contain package k8s.io/api/discovery/v1beta1
github.com/maistra/istio-operator/pkg/controller/common/helm imports
	k8s.io/client-go/kubernetes/scheme imports
	k8s.io/api/flowcontrol/v1alpha1: module k8s.io/api@latest (v0.18.2) found, but does not contain package k8s.io/api/flowcontrol/v1alpha1
github.com/maistra/istio-operator imports
	github.com/operator-framework/operator-sdk/cmd/operator-sdk imports
	github.com/operator-framework/operator-sdk/cmd/operator-sdk/cli imports
	github.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint imports
	github.com/operator-framework/operator-sdk/pkg/ansible imports
	github.com/operator-framework/operator-sdk/pkg/ansible/proxy imports
	k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme: module k8s.io/apimachinery@latest (v0.18.2) found, but does not contain package k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme
```

**Comment by camilamacedo86** [comment] 2020-05-07 13:30
Hi @rcernich, 

We should not longer keep the previous replaces in the go.mod. It should be only as follows + any specific module required for your project in the case it was customized and has implementations that are using other libs. 

```
require (
	github.com/operator-framework/operator-sdk v0.17.0
	sigs.k8s.io/controller-runtime v0.5.2
)

replace (
  k8s.io/client-go => k8s.io/client-go v0.17.4 // Required by prometheus-operator
  github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible // Required by OLM
)
``` 

If the above information is not enough, could you please raise a new issue. The subject of this issue is `Upgrade guide for 0.17.x missing` and your scenario is something as `unable to upgrade my project to use 0.17.x by following the steps` which is no longer the same scope.  Also, please provide the go.mod of your project an if possible a link for the branch with the updates made s far for we are able to reproduce and try to help you with.

**Comment by rcernich** [comment] 2020-05-07 13:57
It would be helpful if there was some text that specified this.  If you are upgrading, you will have a replace section for the kubernetes dependencies (see upgrade to v0.16).  It's not clear that these should be the only operator-sdk related entries in go.mod.

**Comment by rcernich** [comment] 2020-05-07 14:08
Created #2986

**Comment by camilamacedo86** [comment] 2020-05-10 23:42
Closing it since shows that all is sorted out. However, please feel free to re-open if you think that anything else should be addressed here.

**Closed by camilamacedo86** 2020-05-10 23:42 UTC
Labels: kind/documentation, triage/support
