### ISSUE TITLE
'generate openapi' - CRD name and group are wrong

### ISSUE THREAD

**Issue by jpkrohling** [operator-framework/operator-sdk#1608] opened 2019-06-27 10:13 UTC
## Bug Report

When running `operator-sdk generate openapi` against the Jaeger Operator, the CRD's name and group are overridden, from the original `jaegers.jaegertracing.io` / `jaegertracing.io` to `jaegers.jaegertracing.jaegertracing` / `jaegertracing.jaegertracing`.

**What did you do?**
Executed `operator-sdk generate openapi` against an existing operator (Jaeger's).

**Environment**
* operator-sdk version: `v0.8.1, commit: 33b3bfe10176f8647f5354516fff29dea42b6342`
* go version: `go1.12.5 linux/amd64`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:  minikube

* Are you writing your operator in ~ansible, helm~, or *go*? 
**Additional context**
This can be reproduced by running `make generate` in the following Jaeger Operator branch: 
https://github.com/jpkrohling/jaeger-operator/tree/466-ValidateCR

**Comment by estroz** [comment] 2019-06-28 17:08
@jpkrohling were these CRDs generated with the SDK? The behavior should have been the same when looking at the commits in the SDK, `controller-tools`, and `jaeger-operator` at the time `jaegertracing_v1_jaeger_crd.yaml` was generated; `io_v1alpha1_jaeger_crd.yaml` probably wasn’t generated with the SDK because we committed scaffolding code after its initial commit. The issue is in `controller-tools`’ API parsing, which we do not modify before scaffolding CRDs and in fact emulate when generating CRDs in non-Go projects.

**Comment by jpkrohling** [comment] 2019-07-02 08:19
I had the impression that the newest was generated via the SDK's generator, but I might be wrong. How is the name composed? Is there something I could change in the Jaeger Operator in order to get the SDK regenerate the proper CRD?

**Comment by estroz** [comment] 2019-07-02 20:48
@jpkrohling when I delved into the issue further I figured out that the controller-tools CRD generator was getting the incorrect domain for `jaegertracing_v1_jaeger_crd.yaml` from `io_v1alpha1_jaeger_crd.yaml`. The gist of the issue is we only run the CRD generator once and assume the [domain](https://github.com/operator-framework/operator-sdk/blob/db3a453bde93dc4bba13e5ace6dde08758b6dca0/internal/pkg/scaffold/crd.go#L122) is the same for all API's, which is not necessarily correct. This is not an issue in controller-tools `v0.2.0`, which we'll be upgrading to after #1512 is merged, but I'll make a PR beforehand since this should be fixed in a backwards-compatible way.

**Closed** 2019-07-07 01:12 UTC
Labels: kind/bug
