### ISSUE TITLE
I need to recreate a different CRD object that exists on Openshift, from inside the controller of my operator. How too do this is the controller in operatorSDK?

### ISSUE THREAD

**Issue by anusood** [operator-framework/operator-sdk#4175] opened 2020-11-03 20:30 UTC
So I have a scenario where if the pod gets deleted, it gets recreated from my operator, but I want the CRD Object for the VirtualService of Istio to also be recreated at the same time. How do you suggest I do it? Would be of great help. Thanks

**Comment by joelanford** [comment] 2020-11-09 19:36
Closing as a duplicate of #4171.

**Closed by joelanford** 2020-11-09 19:36 UTC
