### ISSUE TITLE
[ansible] Failed to create or get service for metrics: services "operator" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on

### ISSUE THREAD

**Issue by gbaufake** [operator-framework/operator-sdk#1736] opened 2019-07-24 16:16 UTC
## Bug Report

**What did you do?**
Patched an ansible operator based deployment and removed all env from the containers
(``WATCH_NAMESPACE`` and ``OPERATOR_NAME``)

**What did you expect to see?**
A container that can be destroyed.

**What did you see instead? Under which circumstances?**
I see two containers with two different logs
``{"level":"error","ts":1563984394.5846035,"logger":"cmd","msg":"","Namespace":"","error":"OPERATOR_NAME environment variable not set","stacktrace":"github.com/operator-``

[kiali-operator-5d9545df59-qnhgc-operator.log](https://github.com/operator-framework/operator-sdk/files/3427755/kiali-operator-5d9545df59-qnhgc-operator.log)

and a second one with 
``{"level":"info","ts":1563983817.8586397,"logger":"leader","msg":"Continuing as the leader."}
{"level":"error","ts":1563983817.943182,"logger":"cmd","msg":"Exposing metrics port failed.","Namespace":"","error":"failed to create or get service for metrics: services \"kiali-operator\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on:``
[kiali-operator-946947655-j5fpp-operator.log](https://github.com/operator-framework/operator-sdk/files/3427756/kiali-operator-946947655-j5fpp-operator.log)

and those containers are not being deleted with -f

**Environment**
* operator-sdk version: 0.8.0

* go version:go version go1.12.7 darwin/amd64

* Kubernetes version information:

* Kubernetes cluster kind: openshift 4.1
kubernetes 1.13.4

* Are you writing your operator in ansible, helm, or go? ansible

**Possible Solution**

**Additional context**

**Comment by gbaufake** [comment] 2019-07-24 16:32
It seems after deleting the cr and removing the finalizers, it was possible to remove the pods.

**Comment by fabianvf** [comment] 2019-08-02 18:47
The `Failed to create or get service for metrics: services "operator" is forbidden: cannot set blockOwnerDeletion ...` message is usually due to not having permission to create/view/edit the `deployments/finalizers` and `services/finalizers` resources, which is required for metrics.

As for the deletion, are you deleting the deployment or the pods, and how did you deploy your operator?

**Comment by jmazzitelli** [comment] 2019-11-04 16:26
just fyi...

I have ansible operator 0.10.0 as my base image and I just tried it.  I do NOT have services/finalizers, I just  have "update" verb on deployments/finalizers and  I see this in my logs (which is good):
```
{"level":"info","ts":1572880644.1276553,"logger":"metrics","msg":"Metrics Service object created","Service.Name":"kiali-operator-metrics","Service.Namespace":"kiali-operator"}
```
I then removed my operator to try a second test. I changed my role and removed this:
```
- apiGroups: ["apps"]
  resourceNames:
  - kiali-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
```
I re-installed the operator and it failed with:
```
{"level":"error","ts":1572880854.9029043,"logger":"cmd","msg":"Exposing metrics port failed.","Namespace":"kiali-operator","error":"failed to create or get service for metrics: services \"kiali-operator-metrics\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>",
```

So it looks like you only need "update" on "deployment/finalizers"

**Comment by davidkirwan** [comment] 2020-01-09 10:02
Just hit this same issue yesterday with ``operator-sdk v0.12.1``

Fix was to add deployments/finalizers update permissions:

```
- apiGroups: ["apps"]
  resourceNames:
  - kiali-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
```

**Comment by camilamacedo86** [comment] 2020-01-09 10:26
Hi @davidkirwan, 

It make sense. Really thank you for share. We will look at that.

**Comment by camilamacedo86** [comment] 2020-01-12 19:03
Hi @davidkirwan and @gbaufake, 

We could check that the issue is faced when the required permission as point out in the comments is not present in the role.ymal. It is also described already in the docs [here](https://github.com/operator-framework/operator-sdk/blob/e399ce1dadf4545ac12abf2f61d68fb334cc0bd4/doc/faq.md#i-keep-seeing-errors-like-failed-to-create-metrics-service-how-do-i-fix-this).

Also, was verified that any project made using the latest version of SDK will have the permission:

```
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - <operator-name>
  verbs:
  - "update"
```

In this way, I am closing this one since shows all sorted out. However, please feel free to re-open if yu see that something still required to be addressed here.

**Closed by camilamacedo86** 2020-01-12 19:03 UTC
Labels: ansible-operator, kind/bug

**Comment by wtrocki** [comment] 2020-12-08 11:08
If you are using the new kubebuilder based operator try

```
// +kubebuilder:rbac:groups=apps,resources=deployments/finalizers,verbs=update;patch
```

**Comment by wtrocki** [comment] 2020-12-08 12:14
I have the same issue but cannot manage to fix that by the line above:

```
2020-12-08T12:12:39.723Z	ERROR	controllers.Something Problem with creating deployment	{"": "binding/3sdgdfgfgsdfdsf-serviceapi", "error": "deployments.apps \"3sdgdfgfgsdfdsf-serviceapi-deployment\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```

@camilamacedo86 I have noticed that you have added there `resourceNames:` but my generated manifest missing that. Is that required?

**Comment by glenmc007** [comment] 2020-12-22 22:10
> If you are using the new kubebuilder based operator try
> 
> ```
> // +kubebuilder:rbac:groups=apps,resources=deployments/finalizers,verbs=update;patch
> ```

Its not working for me.

Here is the error.
ERROR	controllers.AppDeployment	Failed to create new Deployment	{"appdeployment": "pilot-deploy-operator/appdeployment", "Deployment.Namespace": "pilot-deploy-operator", "Deployment.Name": "appdeployment", "error": "deployments.apps \"appdeployment\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
app-deploy-operator/controllers.(*AppDeploymentReconciler).Reconcile
	/workspace/controllers/appdeployment_controller.go:82
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:244
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
2020-12-22T21:02:48.145Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "core.openshift.io", "reconcilerKind": "AppDeployment", "controller": "appdeployment", "name": "appdeployment", "namespace": "pilot-deploy-operator", "error": "deployments.apps \"appdeployment\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>"}
github.com/go-logr/zapr.(*zapLogger).Error
