### ISSUE TITLE
Failed to build Operator image

### ISSUE THREAD

**Issue by devdattakulkarni** [operator-framework/operator-sdk#1564] opened 2019-06-15 23:30 UTC
## Bug Report

**What did you do?**
Following the readme, I am trying to build app-operator image.

operator-sdk build quay.io/example/app-operator

**What did you expect to see?**
Image built.

**What did you see instead? Under which circumstances?**
operator-sdk build quay.io/example/app-operator
build github.com/example-inc/app-operator/cmd/manager: cannot load sigs.k8s.io/controller-runtime/pkg/controller: open /Users/devdatta/go/src/github.com/example-inc/app-operator/vendor/sigs.k8s.io/controller-runtime/pkg/controller: no such file or directory
Error: failed to build operator binary: (failed to exec []string{"go", "build", "-o", "/Users/devdatta/go/src/github.com/example-inc/app-operator/build/_output/bin/app-operator", "-gcflags", "all=-trimpath=${GOPATH}", "-asmflags", "all=-trimpath=${GOPATH}", "-mod=vendor", "github.com/example-inc/app-operator/cmd/manager"}: exit status 1)
Usage:
  operator-sdk build <image> [flags]

Flags:
  -h, --help                      help for build
      --image-build-args string   Extra image build arguments as one string such as "--build-arg https_proxy=$https_proxy"
      --image-builder string      Tool to build OCI images. One of: [docker, buildah] (default "docker")

Global Flags:
      --verbose   Enable verbose logging

**Environment**
* operator-sdk version:

operator-sdk version: v0.8.0, commit: 78c472461e75e6c64589cfadf577a2004b8a26b3

Had same issue with v0.8.1 as well

* go version:

go version go1.12.6 darwin/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: Minikube (minikube version: v1.1.1)

* Are you writing your operator in ansible, helm, or go?

Go

**Possible Solution**

**Additional context**

**Comment by devdattakulkarni** [comment] 2019-06-15 23:55
I was able to build the image after manually downloading controller-runtime v0.1.11 and manually replacing vendor/sigs.k8s.io/controller-runtime/pkg with pkg folder from v0.1.11. This contained the 'controller' package, which seemed to be missing from the auto-generated pkg tree by operator-sdk cli.

**Comment by kincl** [comment] 2019-06-17 16:38
I also ran into this issue with v0.8.1 of the operator-sdk. I think the issue is that when running `operator-sdk new --dep-manager=modules` it runs `go mod vendor -v` as part of the initialization process but unlike the dep dependency manager, go modules only vendors the packages that are needed to build the application which since there are no controllers specified it does not vendor those required packages.

> $ go help mod vendor
> usage: go mod vendor [-v]
> 
> Vendor resets the main module's vendor directory to include all packages
> needed to build and test all the main module's packages.
> It does not include test code for vendored packages.

After you create a API CRD and controller you need to run `go mod vendor` again to vendor the new packages from `sigs.k8s.io/controller-runtime`.

**Comment by LiliC** [comment] 2019-06-21 09:34
@devdattakulkarni for those releases we still require `go mod vendor` to be run before building, as we do have a dependency on the vendor directory. But since the need for that is removed recently in master so are the docs mentioning that. As @kincl mentioned look at the versioned docs. 

Closing this issue, but if you run into any other problems feel free to open a new one, thanks!

**Closed by LiliC** 2019-06-21 09:34 UTC
