### ISSUE TITLE
Cluster-scoped API objects are not recreated

### ISSUE THREAD

**Issue by aerdei** [operator-framework/operator-sdk#1914] opened 2019-09-13 13:19 UTC
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
How to implement a specific feature

## Question

**What did you do?**
I am trying to create an operator that watches namespaced CRs and creates cluster-scoped objects based on them.

**What did you expect to see?**
Creating the namespaced CR results in the cluster-scoped object being created. Deleting the namespaced CR results in the cluster-scoped object being removed. Deleting the cluster-scoped resource results in it being recreated.

**What did you see instead? Under which circumstances?**
Deleting the cluster-coped object does not result in it being recreated despite the namespaced CR being in place.
From what I can gather, at
`err := r.client.Get(context.TODO(), request.NamespacedName, instance)`
the request object is not found. The reconcile function then returns without re-queuing or recreating the cluster-scoped object.

**Environment**
* operator-sdk version:
v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170
* Kubernetes version information:
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
* Kubernetes cluster kind: 
OpenShift 3.11.143

**Comment by camilamacedo86** [comment] 2019-09-16 21:38
Hi @aerdei.

Unfortunately, I do not know if I understood your question very well. Following my understanding of your problem

WHAT: Objects has been not re-created by the operator 
WHERE: In the cluster
WHEN: They are removed 

So, have you implemented the Watches for these objects? Note that the Watches are required in order to trigger the reconcile function when so change occurs.  I'd like to suggest you check the [example](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/database/controller.go#L46). 

Following an explanation over how your Reconcile func will be trigged for your impl be able to re-check and re-duo all actions. 

After you apply/create the CR which will trigger the reconcile it is trigged by the watches implementations and/or by the manager each X time. 

#### Watches

By default, you will find the watches for the Primary resources already implemented by each controller that you generated by using the SDK tool as follows. 

```go
// Watch for changes to primary resource Memcached
err = c.Watch(&source.Kind{Type: &cachev1alpha1.Memcached{}}, &handler.EnqueueRequestForObject{})
if err != nil {
    return err
}

```

However, note that in the example has watches implemented for each secondary object controlled/created by it. 

```go
// TODO(user): Modify this to be the types you create that are owned by the primary resource
// Watch for changes to secondary resource Pods and requeue the owner Memcached
err = c.Watch(&source.Kind{Type: &appsv1.Deployment{}}, &handler.EnqueueRequestForOwner{
    IsController: true,
    OwnerType:    &cachev1alpha1.Memcached{},
})
if err != nil {
    return err
}

err = c.Watch(&source.Kind{Type: &corev1.Service{}}, &handler.EnqueueRequestForOwner{
    IsController: true,
    OwnerType:    &cachev1alpha1.Memcached{},
})
if err != nil {
    return err
}
```

#### Reconcile trigged by the manager : (main.go)

If you do not change the following code that is created when you do a new project with the SDK then the Reconcile will be trigged every 10 hours.  

```go
	// Create a new Cmd to provide shared dependencies and start components
	mgr, err := manager.New(cfg, manager.Options{
		Namespace:          namespace,
		MapperProvider:     restmapper.NewDynamicRESTMapper,
		MetricsBindAddress: fmt.Sprintf("%s:%d", metricsHost, metricsPort),
	})
	if err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

```
**Why does it happen? How do I know that?** 

See the Options Struct which is used to create the Manager of the operator project.  

```go
	// SyncPeriod determines the minimum frequency at which watched resources are
	// reconciled. A lower period will correct entropy more quickly, but reduce
	// responsiveness to change if there are many watched resources. Change this
	// value only if you know what you are doing. Defaults to 10 hours if unset.
	SyncPeriod *time.Duration
```

Please, let me know if my understanding of your question is accurate and if the info provided is enough for you to solve it otherwise could you please provide the code of your controller implementation and point us what object has been not re-created?

**Comment by aerdei** [comment] 2019-09-17 07:43
Hi @camilamacedo86 
Thank you for your answer! Apologies if the issue was ambiguous, let me elaborate:
I am trying to write an operator that will monitor namespace-scoped CRs and create OpenShift SecurityContextConstraints based on them.

I set the controller-runtime manager to watch resources in the entire cluster in main.go:
```go
	// Create a new Cmd to provide shared dependencies and start components
	mgr, err := manager.New(cfg, manager.Options{
		Namespace:          "",
		MapperProvider:     restmapper.NewDynamicRESTMapper,
		MetricsBindAddress: fmt.Sprintf("%s:%d", metricsHost, metricsPort),
	})
	if err != nil {
		log.Error(err, "")
		os.Exit(1)
	}
```
I added api/security/v1 it to the scheme:
```go
//[...]
securityv1 "github.com/openshift/api/security/v1"
//[...]
//Add OpenShift security to scheme
	if err := securityv1.AddToScheme(mgr.GetScheme()); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}
//[...]
```
Then I created a watch for the SCC resource:
```go
//[...]
func add(mgr manager.Manager, r reconcile.Reconciler) error {
//[...]
err = c.Watch(&source.Kind{Type: &securityv1.SecurityContextConstraints{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &sccv1alpha1.SccOp{},
	})
	if err != nil {
		return err
	}
//[...]
```
In the reconcile function, the SCC is created when it is not found:
```go
func (r *ReconcileMapRScc) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	//[...]
	scc := newSCCForCR(instance)
	if err := controllerutil.SetControllerReference(instance, scc, r.scheme); err != nil {
		return reconcile.Result{}, err
	}
	found := &securityv1.SecurityContextConstraints{}
	err = r.client.Get(context.TODO(), types.NamespacedName{Name: scc.Name, Namespace: ""}, found)
	if err != nil && errors.IsNotFound(err) {
		err = r.client.Create(context.TODO(), scc)
		if err != nil {
			return reconcile.Result{}, err
		}
		return reconcile.Result{}, nil
	} else if err != nil {
		return reconcile.Result{}, err
	}

	return reconcile.Result{}, nil
}
```
newSCCForCR returns an SCC:
```go
func newSCCForCR(cr *sccv1alpha1.MapRScc) *securityv1.SecurityContextConstraints {
    return &securityv1.SecurityContextConstraints{
    //[...]
    }
}
```
Before deploying the operator, I create the service account, cluster role binding and the CRD with `scope:namespaced`

When running the operator, I notice the following behaviour:
CR is created -> SCC is created
CR is deleted -> SCC is deleted
SCC is deleted -> SCC is NOT recreated - this is the issue I am trying to solve. I notice that deleting the SCC results in calling the `Reconcile` function, but the SCC object is not recreated. What am I missing something in my implementation?

**Comment by camilamacedo86** [comment] 2019-09-17 10:21
Hi @aerdei,

It shows a problem with your code impl. Following some information which I hope will help you solve it. 

### Reconcile 

The idea of the Reconcile is as the name says reconciling the cluster data according to the behaviours implemented in the controller of the operator project. 

Check that it works as a loop and in order to clarify how it works following pseudo-code to with this purpose.

```
reconcile APP {

    // Check if Deployment for the app exists, if not create one 
    // if has an error came back for the beginner of the loop   (return reconcile.Result{}, err) 

    // Check if ConfigMap for the app exists, if not create one 
    // if has an error came back for the beginner of the loop   (return reconcile.Result{}, err) 

    // search for Database CR/CRD 
    // if it was not created and/or is not with the status N and values Y then return to the beginner of the loop (return reconcile.Result{Requeue: true}, nil)
    ...
    // if came to here and it is the end then means that all is done successfully and we can stop the reconcile the `return reconcile.Result{}, nil` 

}
```

**IMPORTANT**: Check that you are stopping the "loop/reconcile" instead of keep it going on with the `return reconcile.Result{}, nil`. It should be called just at the end of the loop when all conditions were checked and passed successfully since it will stop the reconcile. You can use `reconcile.Result{Requeue: true}, nil)` and/or do not do a return and let it still working on in order to pass at the next conditions. My guess that the problem can be at this point. 
 
**NOTE:** Regards the scope note that if you are using `Namespace:          "",` it means that your operator project is cluster scope and will watch all namespaces. 

Please, let us know if the info provided was enough for you to solve it.

**Comment by aerdei** [comment] 2019-09-17 14:26
Hi @camilamacedo86 
Thank you for pointing out the extra return statements in my code!
However, cluster-scoped objects are still not handled properly.
I have found that hardcoding a namespace when fetching the SccOp instance, the problem is solved.
So defining
```go
	instance := &sccv1alpha1.SccOp{}
	err := r.client.Get(context.TODO(), types.NamespacedName{Name: request.Name, Namespace: "myproject"}, instance)
```
Will make the operator handle both cluster-scoped and namespace-scoped objects properly. This is of course not a solution, as I am trying to monitor all namespaces. 
Here's my theory, I would like to ask for your input on it:
- When deleting/creating a SecurityContextConstraint (or any other cluster-scoped resource), an `Event` is produced that is transformed into a `Request`. This Request has a `NamespacedName`.
- `Reconcile` is triggered with a `Request` containing `NamespacedName`. In this case, `NamespacedName` will not have a namespace, because the `Source` is a cluster-scoped object.
- The operator will not be able to fetch the SccOp object, because it will look for `types.NamespacedName{Name: request.Name, Namespace: request.Namespace}`, where request.Namespace is `""`
- If I re-queue  the request, it will lead to an infinite `Reconcile` loop.

**Comment by camilamacedo86** [comment] 2019-09-17 14:45
HI @aerdei, 

I see now. However, note that the following impl to get will do the fetch of the object in the namespace "" and not all. The "" for namespace will just mean all in main.go/manager implantation. To understand it further I'd recommend you check the manager impl. 

```go
	err = r.client.Get(context.TODO(), types.NamespacedName{Name: scc.Name, Namespace: ""}, found)
```

If you would like to check the object in all namespaces then you can do it like the following example.

```go
podList := &corev1.PodList{}
	listOpts := []client.ListOption{
		client.MatchingLabels(labelsForMemcached(memcachedrs.Name)),
	}
	err = r.client.List(context.TODO(), podList, listOpts...)
	if err != nil {
		reqLogger.Error(err, "Failed to list pods", "Memcached.Namespace", memcachedrs.Namespace, "Memcached.Name", memcachedrs.Name)
		return reconcile.Result{}, err
	}
``` 

Since it shows solved, I am closing this issue. However, please feel free to re-open if you see that is required.

**Closed by camilamacedo86** 2019-09-17 14:45 UTC
Labels: triage/support

**Comment by joelanford** [comment] 2019-09-17 14:53
@aerdei The problem is that cluster-scoped objects cannot be owned by namespace-scoped objects.

See the Kubernetes [reference doc about owners and dependents](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents), specifically this note:
> **Note:** Cross-namespace owner references are disallowed by design. This means: 1) Namespace-scoped dependents can only specify owners in the same namespace, and owners that are cluster-scoped. 2) Cluster-scoped dependents can only specify cluster-scoped owners, but not namespace-scoped owners.

To accomplish similar semantics, you can apply labels or annotations to the SCCs, use a custom  MapFunc event handler that maps scc events to the correct `SccOp`, and a finalizer on the SCC's so that your operator can clean them up when the `SccOp` is deleted. You effectively have to implement your own ownership and garbage collector implementation.

To help you with this, the SDK has [`operator-sdk/pkg/handler.EnqueueRequestForAnnotation` ](https://github.com/operator-framework/operator-sdk/blob/master/pkg/handler/enqueue_annotation.go)

**Comment by aerdei** [comment] 2019-09-17 15:08
Thank you guys!

**Comment by m-yosefpor** [comment] 2021-06-15 10:03
> @aerdei The problem is that cluster-scoped objects cannot be owned by namespace-scoped objects.
> 
> See the Kubernetes [reference doc about owners and dependents](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents), specifically this note:
> 
> > **Note:** Cross-namespace owner references are disallowed by design. This means: 1) Namespace-scoped dependents can only specify owners in the same namespace, and owners that are cluster-scoped. 2) Cluster-scoped dependents can only specify cluster-scoped owners, but not namespace-scoped owners.
> 
> To accomplish similar semantics, you can apply labels or annotations to the SCCs, use a custom MapFunc event handler that maps scc events to the correct `SccOp`, and a finalizer on the SCC's so that your operator can clean them up when the `SccOp` is deleted. You effectively have to implement your own ownership and garbage collector implementation.
> 
> To help you with this, the SDK has [`operator-sdk/pkg/handler.EnqueueRequestForAnnotation` ](https://github.com/operator-framework/operator-sdk/blob/master/pkg/handler/enqueue_annotation.go)

The link is outdated, can you please provide a some useful resource on how can we implement our custom MapFunc event handler?
