### ISSUE TITLE
[v1.0.0] Create ServiceMonitor with OLM

### ISSUE THREAD

**Issue by balpert89** [operator-framework/operator-sdk#3818] opened 2020-08-31 15:37 UTC
## Type of question

How to implement a specific feature

## Question
How can I enable ServiceMonitor creation with OLM?

#### What did you do?
operator-sdk version: v1.0.0

I am currently trying to add prometheus ServiceMonitor resources to my operator. The operator is deployed by OLM and thus this directory layout is used:

```
helloworld-operator
|__api
|__config
|   |__certmanager
|   |__crd
|   |__default
|   |__manager
|   |__manifests
|   |__prometheus
|   |   |__kustomization.yaml
|   |   |__monitor.yaml
|   |__rbac
|   |__samples
|   |__scorecard
|   |__webhook
|__controller
|__olm
|   |__1.0.0
|   |   |__example.com_helloworlds.yaml #crd
|   |   |__example-helloworld.clusterserviceversion.yaml
|   |   |__example-helloworld-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml
|   |   |__example-helloworld-leader-election-rolebinding_rbac.authorization.k8s.io_v1_role.yaml
|   |__1.0.1
|   |   |__example.com_helloworlds.yaml #crd
|   |   |__example-helloworld.clusterserviceversion.yaml
|   |   |__example-helloworld-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml
|   |   |__example-helloworld-leader-election-rolebinding_rbac.authorization.k8s.io_v1_role.yaml
|   |__metadata
|   |   |__annotations.yaml
|   |__package.yaml
|__vendor
...
```

content of config/prometheus/kustomization.yaml:
```
resources:
- monitor.yaml
```

content of config/prometheus/monitor.yaml:
```

# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: metrics-monitor
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      name: helloworld-operator
```

I have included the reference in the config/default/kustomization.yaml:
```
bases:
- ../crd
- ../rbac
- ../manager
# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'. 
- ../prometheus
```

Running `kustomize build config/manifests` also shows me the `ServiceMonitor` resource:
```
$ kustomize build config/manifests
...
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: helloworld-mcs-helloworld-metrics-monitor
  namespace: operators
spec:
  endpoints:
  - path: /metrics
    port: https
  selector:
    matchLabels:
      name: helloworld-operator
...
```

#### What did you expect to see?

I expected that the `ServiceMonitor` resource shows up when I run this command:
```
kustomize build config/manifests | operator-sdk generate packagemanifests --version 1.0.1 --channel beta --from-version=1.0.0 --input-dir olm/ --output-dir olm/
```

#### What did you see instead? Under which circumstances?

Instead the above structure shows no indication of the `ServiceMonitor` and `Service`. The OLM does not create the resources when installing the operator through a `CatalogSource`.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

Local and OpenShift

`$ operator-sdk version`: 

[balpert@zeus helloworld-operator]$ operator-sdk version
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.13.15 linux/amd64

#### Additional context

I am trying to create a ServiceMonitor equivalent to the approach prior v0.19.0 with the func `addMetrics` and `serveCRMetrics`. The documentation only gives so much information that "Now uncomment the line - ../prometheus in the config/default/kustomization.yaml file. It creates the ServiceMonitor resource which enables exporting the metrics:" (see https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/#export-metrics)

**Comment by joelanford** [comment] 2020-08-31 15:40
`ServiceMonitor` _is_ one of OLM's [supported resource kinds](https://github.com/operator-framework/operator-lifecycle-manager/blob/d2dc60abcc554058497d6feb85bd6e26a0fec338/pkg/controller/operators/catalog/operator.go#L2065-L2071).

@estroz Any idea what might be causing a ServiceMonitor not to be added to the bundle?

**Comment by estroz** [comment] 2020-08-31 16:31
Right now the SDK only adds extra-CSV RBAC to the bundle directly as manifests; general object support is still a feature request (#3494), which ideally will be implemented sooner than later.

**Comment by estroz** [comment] 2020-08-31 18:35
Closing as duplicate of #3494.

**Closed by estroz** 2020-08-31 18:35 UTC
Labels: language/go, triage/duplicate
