### ISSUE TITLE
Hit an unsupported type invalid type for invalid type

### ISSUE THREAD

**Issue by Jacklli** [operator-framework/operator-sdk#2302] opened 2019-12-07 11:05 UTC
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
execute the command:
operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService

and then error occured:
INFO[0001] Running deepcopy code-generation for Custom Resource group versions: [app:[v1alpha1], ] 
F1207 05:56:36.506959   20352 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from ./pkg/apis/app/v1alpha1.AppService
goroutine 1 [running]:
k8s.io/klog.stacks(0xc000d70400, 0xc0000d09a0, 0x8e, 0xde)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:855 +0xb1
k8s.io/klog.(*loggingT).output(0x3707c20, 0xc000000003, 0xc0003c4e00, 0x3511554, 0xb, 0x375, 0x0)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:806 +0x2d9
k8s.io/klog.(*loggingT).printf(0x3707c20, 0x3, 0x1f45d95, 0x2a, 0xc000124cb0, 0x3, 0x3)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:705 +0x14e
k8s.io/klog.Fatalf(...)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:1256

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:

* go version:

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

**Comment by Jacklli** [comment] 2019-12-07 11:06
# go version
go version go1.11.6 linux/amd64

**Comment by camilamacedo86** [comment] 2019-12-07 12:44
Hi @Jacklli, 

If you are using the latest versions of SDK the go version  go1.11.6  is incompatible. You need to use 1.13+. Could you please remove this version and install the 1.13+ and let us know?

If you still facing an issue could you please inform the following info for we are able to help you with?
- SDK version : (Run `operator-sdk version`)
- GO version: 
- A snippet of the code used in the _type.go file of AppService. 

Also, I'd like to suggest you check the [Getting Started ](https://github.com/operator-framework/getting-started), may it helps with.

**Comment by Jacklli** [comment] 2019-12-12 07:05
it's fixed after upgrading to go 1.13.1.
thanks a lot

**Comment by camilamacedo86** [comment] 2019-12-12 09:31
Hi @Jacklli, 

Thank you for let us know. To use the SDK version >= 0.12 is required use go 1.13+.

**Comment by camilamacedo86** [comment] 2019-12-13 22:37
I am closing this one since shows that all is sorted out. Please, feel free to re-open if you think that it's still required.

**Closed by camilamacedo86** 2019-12-13 22:37 UTC
Labels: triage/support

**Comment by kaushiksrinivas** [comment] 2020-02-27 17:12
facing the same issue 
go version
go version go1.14 linux/amd64
operator-sdk version
operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.3 linux/amd64"

**Comment by camilamacedo86** [comment] 2020-02-27 17:30
Same scenario of https://github.com/operator-framework/operator-sdk/issues/2573#issuecomment-587033913. The problem is in your local config setup for GO.

**Comment by kaushiksrinivas** [comment] 2020-02-28 06:08
Issue was operator sdk was built from a folder outside of GOPATH.
had to set GOPATH and install operator sdk from the same.
then the projects are building OK.

Thanks a ton for pointing out.

**Comment by kaushiksrinivas** [comment] 2020-03-02 05:38
Had to unset the https_proxy if behind a proxy for validating the project creation to complete.
We were seeing tls timeout issues.

**Comment by inuyasha82** [comment] 2020-03-20 15:01
Hi, just want to add my 2 cents to this issue, i hit the same exact problem building a project that is using operator-sdk, btw setting GOROOT or GOPATH, it didn't help. 

in my case, running a RHEL 7 the issure was the value of the GOPROXY variable configured by default in the system (the value you get using the command `go env GOPROXY`). By default the value of this variable is "direct", but instead it has to be set to: 

`export GOPROXY=https://proxy.golang.org,direct`

this information is available in the documentation on how to install the sdk here: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md, but is referred only on the case if you want  to build it from master, so is pretty hard to identify as possible solution to the problem. 

Could be useful to explain this case on that documentation?

**Comment by camilamacedo86** [comment] 2020-03-20 17:34
HI @inuyasha82, 

Is not it done already?

see at the bottom. 

> Note: Ensure that your GOPROXY is set with its default value for Go versions 1.13+ which is https://proxy.golang.org,direct.

However, please feel free to contribute with prs to improve the docs.

**Comment by inuyasha82** [comment] 2020-03-20 17:40
Yes, what I was trying to say is that how is written now that note looks
like that it is referring only on the case you are building the operator
from sources, and not for other cases. So is hard to spot, my suggestion is
just to probably move it somewhere else. In that document (i.e. as
prerequisite?)

Il Ven 20 Mar 2020, 17:35 Camila Macedo <notifications@github.com> ha
scritto:
