### ISSUE TITLE
Generate csv automatically adds a podCount descriptor for a size field

### ISSUE THREAD

**Issue by kapilpau** [operator-framework/operator-sdk#3212] opened 2020-06-10 08:35 UTC
## Bug Report

**What did you do?**
In my kind_types.go Kind.Spec struct, I have defined a field whose JSON key is `size` and I set a descriptor of:
```// +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.x-descriptors="urn:alm:descriptor:com.tectonic.ui:text"```
When I run `operator-sdk generate csv`, it adds the following as well:
```
urn:alm:descriptor:com.tectonic.ui:podCount
```
This then means that the values we expect cannot be entered through the form view

**What did you expect to see?**
Only specified descriptors should be added, if there is a benefit gain from adding some based on field names, then they should only be added if none are specified already

**Environment**
* operator-sdk version:
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"

* go version:
go version go1.13.4 linux/amd64

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1", GitCommit:"b23e21a", GitTreeState:"clean", BuildDate:"2020-05-18T09:20:55Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
OCP 4.4.5

* Are you writing your operator in ansible, helm, or go?
Go

**Comment by estroz** [comment] 2020-06-11 16:26
Duplicate of #2983

**Closed by estroz** 2020-06-11 16:26 UTC
