### ISSUE TITLE
Objects at cluster scope aren't deleted when CR is deleted

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-sdk#1085] opened 2019-02-11 05:41 UTC
## Type of question

Probably support question

## Question

**What did you do?**

In certain scenarios my operator creates oAuthClient - an object at cluster scope, not namespaced. It works well, however, when I delete my CR, all namespaced objects get deleted but not oAuthclient, even though it has the right ownerReference:

```
eugene@ivantsoft ~/go/src/github.com/operator-framework $ oc get oauthclients/eclipse-che-openshift-identity-provider-yy5yr8 -o=yaml
apiVersion: oauth.openshift.io/v1
grantMethod: prompt
kind: OAuthClient
metadata:
  creationTimestamp: 2019-02-11T05:26:56Z
  labels:
    app: che
  name: eclipse-che-openshift-identity-provider-yy5yr8
  ownerReferences:
  - apiVersion: org.eclipse.che/v1
    blockOwnerDeletion: true
    controller: true
    kind: Che
    name: eclipse-che
    uid: 4ee4f24a-2dbd-11e9-9f95-54e1ad81a005
  resourceVersion: "671339"
  selfLink: /apis/oauth.openshift.io/v1/oauthclients/eclipse-che-openshift-identity-provider-yy5yr8
  uid: a5e57694-2dbd-11e9-b6a9-54e1ad81a005
redirectURIs:
- http://keycloak-che.172.17.0.1.nip.io/auth/realms/che/broker/openshift-v3/endpoint
secret: qlunZTP0WcWQ
```

and is watched by the operator:

```
		err = c.Watch(&source.Kind{Type: &oauth.OAuthClient{}}, &handler.EnqueueRequestForOwner{
			IsController: true,
			OwnerType:    &orgv1.Che{},
		})
		if err != nil {
			return err
		}
```

Is this expected or perhaps I might be doing smth wrong here?

**Environment**
* operator-sdk version:

0.3.0

Happens on OpenShift 3.11, and 4.0

**Comment by hasbro17** [comment] 2019-02-12 00:23
@eivantsov This is actually the expected behavior when you have a namespaced Owner(your CR) and owning a cluster-scoped object (OAuthClient).
Due to the fact that the [OwnerReference does not have a namespace field](https://github.com/kubernetes/kubernetes/blob/6e5176b48df8719ab969a233a0411ad6ba35d222/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L288-L290) the GC cannot lookup the owner for the OAuthClient (since lookup by UID alone is not currently supported, you need both name/namespace).

So right now k8s will not GC a cluster-scoped object owned by a namespaced object.
There is [some discussion](https://github.com/kubernetes-sigs/controller-runtime/issues/214#issuecomment-443352493) on this upstream if you're interested in the background.

But to address your issue, you could add a Finalizer to block the deletion of your CR so that your operator can manually clean up the owned OAuthClient object.

**Comment by hasbro17** [comment] 2019-02-18 01:40
@eivantsov I'm hoping you could resolve the above issue with Finalizers. Since there's not much that the SDK can do to work around the GC behavior, I'm going to close this issue for now.
Feel free tor reopen it if you have a follow up question or suggestion.

**Closed by hasbro17** 2019-02-18 01:40 UTC
Labels: question

**Comment by eivantsov** [comment] 2019-02-18 05:32
@hasbro17 thanks. Yes, I will look at finalizers. If there's an example in an existing Operator, a link/pointer is appreciated.

**Comment by hasbro17** [comment] 2019-02-19 01:04
None of the sample operators we have are using finalizers right now but you can take a look at the Helm operator code to see how it uses Finalizers to block CR deletion for cleanup:
- [Adds a Finalizer to all Custom Resources that don't have them](https://github.com/operator-framework/operator-sdk/blob/5f3c3a50fa121e6cae05b9afced1469bc9fe2b7c/pkg/helm/controller/reconcile.go#L82-L92)
- [Checks if a CR deletion is blocked by a finalizer](https://github.com/operator-framework/operator-sdk/blob/5f3c3a50fa121e6cae05b9afced1469bc9fe2b7c/pkg/helm/controller/reconcile.go#L112-L116)
  - Takes the necessary steps to do cleanup(uninstalls a release). In your case, delete the OAuthClient object.
   - On successful cleanup it [removes the Finalizer and updates the CR to unblock CR deletion](https://github.com/operator-framework/operator-sdk/blob/5f3c3a50fa121e6cae05b9afced1469bc9fe2b7c/pkg/helm/controller/reconcile.go#L149-L160)

Hope that helps.
