### ISSUE TITLE
Failed to build image with operator-sdk build api

### ISSUE THREAD

**Issue by zeromsi** [operator-framework/operator-sdk#2392] opened 2020-01-11 09:11 UTC
Command:
sudo operator-sdk build quay.io/example/app-operator

Result:
Error: failed to build operator binary: (failed to exec []string{"go", "build", "-o", "/home/shahidul/go/operators/nexus-operator/build/_output/bin/nexus-operator", "-gcflags", "all=-trimpath=/home/shahidul/go/operators", "-asmflags", "all=-trimpath=/home/shahidul/go/operators", "-mod=vendor", "github.com/nexus-operator/cmd/manager"}: exec: "go": executable file not found in $PATH)
Usage:
  operator-sdk build <image> [flags]

Flags:
      --go-build-args string      Extra Go build arguments as one string such as "-ldflags -X=main.xyz=abc"
  -h, --help                      help for build
      --image-build-args string   Extra image build arguments as one string such as "--build-arg https_proxy=$https_proxy"
      --image-builder string      Tool to build OCI images. One of: [docker, podman, buildah] (default "docker")

Global Flags:
      --verbose   Enable verbose logging

**Comment by camilamacedo86** [comment] 2020-01-12 13:00
Hi @zeromsi, 

The `operator-sdk build` will build an image for the current project.  So, it needs be executed in the current directory of the project as described in the [Getting Started](https://github.com/operator-framework/getting-started#1-run-as-a-deployment-inside-the-cluster) and [Quick Start](https://github.com/operator-framework/operator-sdk#create-and-deploy-an-app-operator)

So, you should do such as:

> # Build and push the app-operator image to a public registry such as quay.io
> $ operator-sdk build quay.io/<username>/app-operator

The sudo is not rquired as well. 

Note that as a requirement you need to have the docker installed and running. 

According to the error faced `"go": executable file not found in $PATH)` shows that it has not in the current directory and/or your env is not set up properly. Could you please verify the pre-requirements  and if you still facing issue provided futher information such as follows?

- Where is your project? Is it in the /src of your GOPATH or not? What are your go env? (Run `pwd` and `go env`)
- What is the docker version used? (run `docker version`)
- What is the go version used? (run `go version`)
- What is the sdk version used? (run `operator-sdk version`)

**Comment by zeromsi** [comment] 2020-01-12 15:13
Hi @camilamacedo86,

``` Go env ```
``` 
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shahidul/.cache/go-build"
GOENV="/home/shahidul/.config/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shahidul/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/shahidul/go/operators/nexus-operator/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build261177620=/tmp/go-build -gno-record-gcc-switches"

```
```Docker version: ``` ``` 19.03.5 ```
``` go version:  ``` ```  go1.13.3 ```
``` operator-sdk version:  ``` ``` v0.13.0-33-g5fc8835b ```
``` Project kind: ``` ``` go ```

**Comment by camilamacedo86** [comment] 2020-01-12 19:16
HI @zeromsi, 

Looking at the data provided from the env I cannot see any issue. Then, all lead me to believe that something is wrong with your project. it shows that the project has not the required files. Could you please try to follow the steps in the [QuickStart](https://github.com/operator-framework/operator-sdk#create-and-deploy-an-app-operator) and let us know if it worked for you? Note that I unable to reproduce this issue and it is also something that is covered by the e2e tests in the project.

**Comment by zeromsi** [comment] 2020-01-13 03:52
@camilamacedo86  is it okay if I build image with docker build api? What operator-sdk is doing? If I'm not wrong it's just building the artifact then storing somewhere and then running Docker built addressing that artifact! Am I right?

**Comment by zeromsi** [comment] 2020-01-13 04:38
Hi @camilamacedo86 
Thanks for your support. I tried it differently, I found that Operator-sdk was unable to locate my main.go. So what i did, I just shift that file to the root, then ran operator-sdk build and it worked.

```
.
├── build
│   ├── bin
│   │   ├── entrypoint
│   │   └── user_setup
│   ├── Dockerfile
│   └── _output
│       └── bin
│           └── app-operator
├── cmd
│   └── manager
│       └── build
│           └── _output
│               └── bin
│                   └── app-operator
├── deploy
│   ├── crds
│   │   ├── app.example.com_appservices_crd.yaml
│   │   └── app.example.com_v1alpha1_appservice_cr.yaml
│   ├── operator.yaml
│   ├── role_binding.yaml
│   ├── role.yaml
│   └── service_account.yaml
├── go.mod
├── go.sum
├── main.go
├── pkg
│   ├── apis
│   │   ├── addtoscheme_app_v1alpha1.go
│   │   ├── apis.go
│   │   └── app
│   │       ├── group.go
│   │       └── v1alpha1
│   │           ├── appservice_types.go
│   │           ├── doc.go
│   │           ├── register.go
│   │           └── zz_generated.deepcopy.go
│   └── controller
│       ├── add_appservice.go
│       ├── appservice
│       │   └── appservice_controller.go
│       └── controller.go
├── tools.go
└── version
    └── version.go


```

**Comment by hasbro17** [comment] 2020-01-13 21:11
> I tried it differently, I found that Operator-sdk was unable to locate my main.go. So what i did, I just shift that file to the root

@zeromsi I don't think that's related to your initial error message.
`exec: "go": executable file not found in $PATH)` suggests that your go binary path e.g `/usr/local/go/bin`  isn't in your $PATH env var.

You can see from your own error message that `operator-sdk build` is just running `go build ... github.com/nexus-operator/cmd/manager`.

Can you print out the error that you get when you run operator-sdk build against a newly scaffolded project via `operator-sdk new` that's unmodified.

And also check your $PATH var, `echo $PATH`.

**Comment by camilamacedo86** [comment] 2020-02-07 03:30
Hi @zeromsi, 

Could you please let us know if was possible to solve the issue? 

Also, ensure the GOROOT as well. You can you run the following command and retry:

> unset GOROOT
> export GOROOT=$(go env GOROOT)

**Comment by camilamacedo86** [comment] 2020-02-07 03:31
Hi @zeromsi,

Could you please let us know if was possible to solve the issue?

**Comment by camilamacedo86** [comment] 2020-03-12 12:35
Hi @zeromsi, 

According to the https://github.com/operator-framework/operator-sdk/issues/2392#issuecomment-573505325 I understand that it is sorted out. So, I am closing this one, however,  please feel free to ping us to re-open this one if you are still needing help with.

**Closed by camilamacedo86** 2020-03-12 12:35 UTC
Labels: triage/support
