### ISSUE TITLE
Fails to create a new operator using a "--helm-chart-repo"

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#1993] opened 2019-09-30 16:05 UTC
## Bug Report

The operator-sdk version `0.10.0` fails to create a new operator using as parameter a helm chart-repo

### Test 1

Command: 
```
operator-sdk new kubedb-helm-operator \
  --type=helm \
  --helm-chart=kubedb \
  --helm-chart-repo=https://raw.githubusercontent.com/appscode/charts/master/stable/index.yaml --helm-chart-version=0.12.0`
```
Result
```
INFO[0000] Creating new Helm operator 'kubedb-helm-operator'.
Error: failed to create helm chart: failed to fetch chart: Looks like "https://raw.githubusercontent.com/appscode/charts/master/stable/index.yaml" is not a valid chart repository or cannot be reached: Failed to fetch \
https://raw.githubusercontent.com/appscode/charts/master/stable/index.yaml/index.yaml : 
404 Not Found
```

So, the CLI command is appending `/index.yaml` after the URL passed as parameter to `--helm-chart-repo`. 

### Test 2

If we remove the `index.yaml` from the url of the `--helm-chart-repo`, then we got another error

Command: `operator-sdk new kubedb-helm-operator --type=helm --helm-chart=kubedb --helm-chart-repo=https://raw.githubusercontent.com/appscode/charts/master/stable --helm-chart-version=0.12.0`
Result
```
INFO[0000] Creating new Helm operator 'kubedb-helm-operator'.
Error: failed to create helm chart: failed to fetch chart: no cached repo found. (try 'helm repo update'). open /Users/dabou/.helm/repository/cache/local-index.yaml: no such file or directory
```

**Comment by joelanford** [comment] 2019-09-30 16:19
@cmoulliard I'm not able to reproduce this.  Can you try running `helm init --client-only` and then retry the `operator-sdk new` command?

**Comment by joelanford** [comment] 2019-09-30 16:19
BTW, the second option (i.e. without `index.yaml`) is the correct invocation.

**Comment by cmoulliard** [comment] 2019-09-30 16:31
That fails too with now a different error @joelanford 

```
failed to create helm chart: failed to fetch chart: no cached repo found. (try 'helm repo update')
```

Command

```
operator-sdk new kubedb-helm-operator --type=helm --helm-chart=kubedb --helm-chart-repo=https://raw.githubusercontent.com/appscode/charts/master/stable --helm-chart-version=0.12.0
INFO[0000] Creating new Helm operator 'kubedb-helm-operator'.
Error: failed to create helm chart: failed to fetch chart: no cached repo found. (try 'helm repo update'). open /Users/dabou/.helm/repository/cache/local-index.yaml: no such file or directory
Usage:
  operator-sdk new <project-name> [flags]
```

**Comment by cmoulliard** [comment] 2019-09-30 16:35
The only way to make it works is to delete the `~/.helm` directory
See
```
mv /Users/dabou/.helm /Users/dabou/.helm.old
helm init --client-only
Creating /Users/dabou/.helm
Creating /Users/dabou/.helm/repository
Creating /Users/dabou/.helm/repository/cache
Creating /Users/dabou/.helm/repository/local
Creating /Users/dabou/.helm/plugins
Creating /Users/dabou/.helm/starters
Creating /Users/dabou/.helm/cache/archive
Creating /Users/dabou/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /Users/dabou/.helm.
Not installing Tiller due to 'client-only' flag having been set


operator-sdk new kubedb-helm-operator --type=helm --helm-chart=kubedb --helm-chart-repo=https://raw.githubusercontent.com/appscode/charts/master/stable --helm-chart-version=0.12.0
INFO[0000] Creating new Helm operator 'kubedb-helm-operator'.
INFO[0001] Created helm-charts/kubedb
INFO[0001] Generating RBAC rules
INFO[0003] Scaffolding ClusterRole and ClusterRolebinding for cluster scoped resources in the helm chart
WARN[0003] The RBAC rules generated in deploy/role.yaml are based on the chart's default manifest. Some rules may be missing for resources that are only enabled with custom values, and some existing rules may be overly broad. Double check the rules generated in deploy/role.yaml to ensure they meet the operator's permission requirements.
INFO[0003] Created build/Dockerfile
INFO[0003] Created watches.yaml
INFO[0003] Created deploy/service_account.yaml
INFO[0003] Created deploy/role.yaml
INFO[0003] Created deploy/role_binding.yaml
INFO[0003] Created deploy/operator.yaml
INFO[0003] Created deploy/crds/charts_v1alpha1_kubedb_crd.yaml
INFO[0003] Created deploy/crds/charts_v1alpha1_kubedb_cr.yaml
INFO[0003] Project creation complete.
```

**Comment by joelanford** [comment] 2019-09-30 16:39
This may be able to be resolved without blowing away the existing `.helm` folder. It looks like you're missing `~/.helm/repository/cache/local-index.yaml`.

In my `.helm` folder, I see:

```
$ ls -l ~/.helm/repository/cache/local-index.yaml
lrwxrwxrwx 1 joe joe 43 Aug 20 15:45 /home/joe/.helm/repository/cache/local-index.yaml -> /home/joe/.helm/repository/local/index.yaml
```

And

```
$ cat ~/.helm/repository/local/index.yaml
apiVersion: v1
entries: {}
generated: "2019-08-20T15:45:13.807112328-04:00"
```

Glad to see you got it working though!

**Closed by joelanford** 2019-09-30 16:39 UTC
Labels: helm-operator, triage/support
