### ISSUE TITLE
Variables with uppercase characters get mangled

### ISSUE THREAD

**Issue by danielkucera** [operator-framework/operator-sdk#3173] opened 2020-06-04 09:58 UTC
## Bug Report

**What did you do?**
Created a CR with following spec:
```
spec:
  egressIPs:
    - 10.1.1.1
    - 4.2.2.2
```

**What did you expect to see?**
following ansible variable:
```
"egressIPs":[
            "10.1.1.1",
            "4.2.2.2"
        ],
```

**What did you see instead? Under which circumstances?**
following ansible variable:
```
"egress_i_ps":[
            "10.1.1.1",
            "4.2.2.2"
        ],
```

**Environment**
* operator-sdk version:
operator-sdk version: "v0.18.0", commit: "921c33982687d6e9219fe0a1a326515fb37ae040", kubernetes version: "v1.18.2", go version: "go1.13.10 linux/amd64"

* go version:

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go? ansible

**Possible Solution**

**Additional context**

**Comment by estroz** [comment] 2020-06-05 01:09
This looks like https://github.com/operator-framework/operator-sdk/issues/2393. @danielkucera you're using `quay.io/operator-framework/ansible-operator:v0.18.0` I assume?

/cc @fabianvf @asmacdo 

/kind bug

**Comment by joelanford** [comment] 2020-06-08 18:19
If anyone is interested in working on a fix for this, @fabianvf can help.

**Comment by rawc0der** [comment] 2020-06-21 23:57
I can confirm **camelCase** variable name not working in CR for _ansible-operator:v0.18.1_

> localhost]: FAILED! => {\"msg\": \"The task includes an option with an undefined variable. The error was: 'teamConfig' is undefined\\n\\nThe error appears to be in '/opt/ansible/roles/xxxxxxxxxx/tasks/main.yml': line 3, column 3, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\n

>spec:
    camelCase:
      values: 
        - value1
        - value2

**Closed** 2020-06-29 21:15 UTC
Labels: ansible-operator, good first issue, kind/bug
