### ISSUE TITLE
The controller of the configMap of the pod's volume without the Name field parameter reports an error

### ISSUE THREAD

**Issue by huzerun0306** [operator-framework/operator-sdk#5513] opened 2022-01-23 08:53 UTC
## Type of question
General operator-related help

## Question
I need to generate a pod in the controller, this pod needs volume and the type of volume is configMap, but because the **ConfigMapVolumeSource** of the **"k8s.io/api/core/v1"** package does not have a Name field, my controller finally generates Error: 
**"error": "Pod \"zerunapi-sample\" is invalid: [spec.volumes[0].configMap.name: Required value**

#### What did you do?
I want to build a pod in the controller, this pod needs a volume, and the type of the volume is a comfigmap, so I define a pod in the following way, omitting other unimportant fields, and only keeping the volume
```
Volumes: []corev1.Volume{
        {
	        Name: podVolumeName,
	        VolumeSource: corev1.VolumeSource{
		        ConfigMap: &corev1.ConfigMapVolumeSource{
			        LocalObjectReference: corev1.LocalObjectReference{
				        Name: zapi.Spec.ConfigMap,
			        },
        
			        DefaultMode:         &configMapMode,
		        },
	        },
        },
},
```
The problem is that when I use kubernetes to create a pod, if I need to bind a volume to a configmap, then I must have a configMap.name field, as I saw in the kubernetes documentation
![image](https://user-images.githubusercontent.com/44351924/150671158-8467ce43-45d2-4e97-9a9a-3c93e351d22a.png)

But the ConfigMapVolumeSource object in the k8s.io/api/core/v1 package I referenced does not have a name field. I don't know if this is reasonable. 

I refer to the code of other operators, such as the prometheus operator. When they build a pod and need to mount the volume of the configmap, the name is not defined in pod.Spec.Volumes.VolumeSource.configMap, Only use this field LocalObjectReference. 

But if I don't define Name in my code, my controller will report an error, which is obviously an error that the pod cannot be created without this name field. 
![image](https://user-images.githubusercontent.com/44351924/150671335-3ef6dd98-5993-403b-99c8-2441eb65cd6d.png)

I don't know what is causing this and how can I fix it, thanks a lot for the help from the team

#### Environment

**Operator type:**
/language go

**Kubernetes cluster type:**
Tencent Cloud Tke Cluster

`$ operator-sdk version`
operator-sdk version: "v1.16.0-5-g2a582022", commit: "2a5820229c932c617fba446f197b9a982a17d216", kubernetes version: "v1.21", go version: "go1.16", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)
go version go1.16 linux/amd64

`$ kubectl version`
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.14", GitCommit:"c93cd0e4cfd27c8216a9ee2b6f1969a9d1294c5c", GitTreeState:"clean", BuildDate:"2021-08-18T11:09:02Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context
core package version
k8s.io/api v0.22.1

**Comment by huzerun0306** [comment] 2022-01-23 09:01
The ConfigMapVolumeSource resource in the k8s.io/api@v0.22.1/core/v1/type.go file is defined like this
![image](https://user-images.githubusercontent.com/44351924/150671376-7dac4246-f196-423d-b9a4-091561a0b5a3.png)

There are many ConfigMapVolumeSource resource objects in the code of Prometheus Opreator, but no Name is defined
https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/alertmanager/statefulset.go#L507
```
volumes = append(volumes, v1.Volume{
	Name: k8sutil.SanitizeVolumeName("configmap-" + c),
	VolumeSource: v1.VolumeSource{
		ConfigMap: &v1.ConfigMapVolumeSource{
			LocalObjectReference: v1.LocalObjectReference{
				Name: c,
			},
		},
	},
})
```

**Comment by varshaprasad96** [comment] 2022-02-03 07:27
@huzerun0306 I just created a sample pod with a similar pod spec as mentioned here:

```go
s := v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test-pod",
			Namespace: "default",
		},
		Spec: v1.PodSpec{
			Volumes: []v1.Volume{
				{
					Name: "config-maptest",
					VolumeSource: v1.VolumeSource{
						ConfigMap: &v1.ConfigMapVolumeSource{
							LocalObjectReference: v1.LocalObjectReference{
								Name: "sample-config-map",
							},
						},
					},
				},
			},
			Containers: []v1.Container{{
				Name:    "test-container",
				Image:   "k8s.gcr.io/busybox",
				Command: []string{"/bin/sh", "-c", "ls /etc/config/"},
			}},
		},
	}

	//create the pod in kubernetes cluster using the clientset
	pod, err := clientset.CoreV1().Pods(s.Namespace).Create(context.TODO(), &s, metav1.CreateOptions{})
	if err != nil {
		panic(err)
	}
	fmt.Println("Pod created successfully...")
```

When I check the details of the created pod, I see the `configMap ` with the specified name:

```yaml
Volumes:
  config-maptest:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      sample-config-map
    Optional:  false
  default-token-dbl57:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-dbl57
    Optional:    false
```

Can you check if `zapi.Spec.ConfigMap` is actually populating the value as required?

**Comment by varshaprasad96** [comment] 2022-02-03 07:40
Since this is not related to Operator SDK directly, I am closing this issue. Hope the above comment will help in debugging the cause. Please feel free to reopen this issue.

**Closed by varshaprasad96** 2022-02-03 07:40 UTC
Labels: triage/support
