### ISSUE TITLE
Scorecard needs to wait for CRs being deleted.

### ISSUE THREAD

**Issue by dmesser** [operator-framework/operator-sdk#2719] opened 2020-03-25 23:14 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**

In CR behavioral tests we often observe something like this:

```
time="2020-03-25T22:13:00Z" level=warning msg="time=\"2020-03-25T22:13:00Z\" level=info msg=\"a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\\n\"\ntime=\"2020-03-25T22:13:00Z\" level=error msg=\"Failed to cleanup resources: (a cleanup function failed; see stdout for more details)\"\n"
2939time="2020-03-25T22:13:00Z" level=error msg="Plugin `OLM Integration` failed with error (failed to create cr resource: object is being deleted: kialis.kiali.io \"kiali\" already exists)"
2940basic:
2941	Spec Block Exists                   pass
2942	CR: kiali
2943	Labels: 
2944		"necessity":"required"
2945		"suite":"basic"
2946		"test":"checkspectest"
2947
2948	Writing into CRs has an effect      pass
2949	CR: kiali
2950	Labels: 
2951		"test":"writingintocrshaseffecttest"
2952		"necessity":"required"
2953		"suite":"basic"
2954
2955:
2956	OLM Integration                     
2957	CR: 
2958	Labels: 
2959	Errors: 
2960		plugin error
2961	Log:
2962		failed to create cr resource: object is being deleted: kialis.kiali.io "kiali" already exists:
```

Source: https://travis-ci.com/github/operator-framework/community-operators/jobs/303074370

It looks like that when the Operator is not fast enough to delete the CR before the next test run it stumbles upon the CR in the terminating state when approaching the next step.

**Describe the solution you'd like**
Scorecard should wait for CRs that are deleted to finish deleting with a reasonable timeout. Furthermore, CR that already exists could be used instead of trying to create a second CR with the same name. If that is not possible we should use individual names for CRs.

**Comment by dmesser** [comment] 2020-03-26 10:56
The behavior of scorecard is also problematic for Operators that manage their own singleton-CRs: https://github.com/operator-framework/community-operators/pull/1408

**Comment by dmesser** [comment] 2020-03-26 12:51
Btw, increasing `init-timeout` does not help.

**Comment by camilamacedo86** [comment] 2020-03-26 13:33
I was checking with @dmesser the scenario with the init-timeout and I note something in the logs that may help us reproduce and identify the root cause of it. 

See:
```
time="2020-03-26T12:27:41Z" level=debug msg="Debug logging is set"
time="2020-03-26T12:27:41Z" level=info msg="Using config file: /tmp/scorecard-bundles/rnrmavdmja.bundle.yaml"
time="2020-03-26T12:33:32Z" level=warning msg="time=\"2020-03-26T12:33:32Z\" level=info msg=\"a cleanup function failed with error: cleanup function failed: error encountered during deletion of resource type KfDef with namespace/name (kubeflow-gqoek/kfdef-kubeflow): etcdserver: request timed out\\n\"\ntime=\"2020-03-26T12:33:32Z\" level=error msg=\"Failed to cleanup resources: (a cleanup function failed; see stdout for more details)\"\n"
E0326 12:33:32.143312     671 memcache.go:199] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0326 12:33:32.144332     671 memcache.go:111] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
time="2020-03-26T12:33:45Z" level=error msg="Plugin `OLM Integration` failed with error (failed to create cr resource: object is being deleted: kfdefs.kfdef.apps.kubeflow.org \"kfdef-kubeflow\" already exists)"
```
From: https://travis-ci.com/github/operator-framework/community-operators/jobs/304588664

Note the error:

> E0326 12:33:32.143312     671 memcache.go:199] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request

So, I found: https://github.com/kubernetes/kubernetes/issues/72051#issuecomment-457060575, may it helps to troubleshoot the scenario faced with init-timeout as well.

**Comment by jmccormick2001** [comment] 2020-06-08 18:04
given the new scorecard is in alpha, I'd like to close this one out unless folks feel this needs to be addressed in the soon to be deprecated version.

**Closed by jmccormick2001** 2020-06-08 18:04 UTC
Labels: kind/bug, needs discussion, priority/important-longterm, scorecard
