### ISSUE TITLE
operator fails with forbidden error - no rbac policy

### ISSUE THREAD

**Issue by sa-cloud** [operator-framework/operator-sdk#1973] opened 2019-09-26 07:55 UTC
## Bug Report

**What did you do?**
I have Openshift 3.11 and I am trying to use operators as described in this blog:
https://blog.openshift.com/build-kubernetes-operators-from-helm-charts-in-5-steps/

I created an sashard-operator operator based on my working helm chart and tried to deploy the application by running:
kubectl create -f deploy/crds/charts_v1alpha1_sashard_cr.yaml

**What did you expect to see?**
a deployed and running set of k8s components defined in my helm chart

**What did you see instead? Under which circumstances?**

failed to install release: podsecuritypolicies.policy "sa-psp-user-any" is forbidden: User "system:serviceaccount:default:sashard-operator" cannot delete podsecuritypolicies.policy at the cluster scope: no RBAC policy matched

In the operator pod log I also see this message:
{"level":"info","ts":1569228485.5403228,"logger":"cmd","msg":"failed to initialize service object for metrics: deployments.apps \"sashard-operator\" is forbidden: User \"system:serviceaccount:default:sashard-operator\" cannot get deployments.apps in the namespace \"default\": no RBAC policy matched","Namespace":"default"}

**Environment**
* operator-sdk version:
operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170

* go version:
go version go1.13 linux/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-25T23:40:32Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Openshift 3.11

* Are you writing your operator in ansible, helm, or go?
used operator-sdk on a working helm chart

**Possible Solution**

**Additional context**

**Comment by camilamacedo86** [comment] 2019-09-26 19:24
Hi @sa-cloud, 

The RBCA errors mean that it requires permissions which were not applied. So, it is missing you apply the roles as well. According to your description shows that it was not performed. I'd suggest you check the following guide. 

https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md#create-a-new-project 

Please, let us know if you could solve the RBCA (permission) issue and if we can close this issue.

**Comment by camilamacedo86** [comment] 2019-09-28 01:02
Hi @sa-cloud, 

I am closing this one because shows that we could cover your question. However, please feel free to re-open if you need.

**Comment by sa-cloud** [comment] 2019-10-06 05:16
Hi, please reopen the issue, I don't have permissions to do that.

I used the instructions to convert my **working** helm chart into an operator:
https://blog.openshift.com/make-a-kubernetes-operator-in-15-minutes-with-helm/
https://blog.openshift.com/build-kubernetes-operators-from-helm-charts-in-5-steps/

So yes, I definitely ran operator-sdk new with --helm-chart.
This is the command I used, as shown in second link above:
operator-sdk new sa-operator --kind=sa --api-version=example.org/v1alpha1 --type=helm --helm-chart sa-charts/sa-single-helm
The deploy/role.yaml is present in the operator folder.
Here is the content:

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: sa-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - sa-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - '*'
  verbs:
  - '*'

**Comment by camilamacedo86** [comment] 2019-10-06 14:49
Hi @sa-cloud, 

Another important point is that for you are able to apply the RCBA roles you need to be logged as admin. In the case of OCP use the command `oc login -u system:admin` before executing the commands to apply the operator files. 

Your error describes here is:
failed to install release: podsecuritypolicies.policy "sa-psp-user-any" is forbidden: User "system:serviceaccount:default:sashard-operator" cannot delete podsecuritypolicies.policy at the cluster scope: no RBAC policy matched

Which shows that your project has no permissions ([RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/))to delete podsecuritypolicies.policy. If your project is managing objects which are not the default of the init/scaffold project you may need to add the required roles/permissions in this file. 

So, first, at all I would recommend you check and follow the [user guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md#create-a-new-project) as use Minnikube or OPC 4 instead of OCP 3.11/Minishft.

Following the reference from this document related to your issue:

**Comment by camilamacedo86** [comment] 2019-10-08 22:26
HI @sa-cloud, 

I am closing this one since shows that the answer to your question was provided.   
However, please feel free to re-open if you need.

**Closed by camilamacedo86** 2019-10-08 22:26 UTC
Labels: helm-operator, triage/support

**Comment by obeleh** [comment] 2021-05-07 05:06
For anyone coming here falling into the same (beginner) mistake as I did. I had the same problem and what turned out to be the root cause was that my `kubebuilder` comments were like this:

```golang
//+kubebuilder:rbac:groups=db-operator.kubemaster.com,resources=dbcopyjobs,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=db-operator.kubemaster.com,resources=dbcopyjobs/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=db-operator.kubemaster.com,resources=dbcopyjobs/finalizers,verbs=update
func (r *DbCopyJobReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	_ = r.Log.WithValues("dbcopyjob", req.NamespacedName)

	rr := DbCopyJobReco{
		Reco: Reco{r.Client, ctx, r.Log, req.NamespacedName},
	}
	return rr.Reco.Reconcile((&rr))
}
```

I'm rather new to Golang and I didn't figure that in this way the kubebuilder comments wouldn't be visible to kubebuilder. When I added a blank line between the function and the comments it was fine. My conclusion is that once the comments end up in the godoc of the function they're not visible to kubebuilder
