### ISSUE TITLE
memcached operator restart due to OOMKilled when deployed "manually" and works fine when deployed using OLM

### ISSUE THREAD

**Issue by fckbo** [operator-framework/operator-sdk#4184] opened 2020-11-04 22:00 UTC
## Type of question
Open question

## Question
Hello, I noticed that the memcached controller was restarting, when deploying some memcached instance, due to " OOMKilled" when the operator was deployed "manually" using 
```
make deploy IMG=10.194.216.114:5000/test/mem-ope:latest
```
but when packaging it in a bundle, creating a CatalogSource and deploying it using OLM on OCP GUI it did not happen
#### What did you do?
Used the tutorial
```
 make manifests
 make install
 make docker-build IMG=10.194.216.114:5000/test/mem-ope:latest
 make docker-push IMG=10.194.216.114:5000/test/mem-ope:latest
 cd config/default/ && kustomize edit set namespace "default" && cd ../..
 make deploy IMG=10.194.216.114:5000/test/mem-ope:latest
 oc get pods
 oc apply -f config/samples/cache_v1alpha1_memcached.yaml
 oc get pods
 oc describe pods memcached-operator-controller-manager-74fb64fdd-fw4s5
```
I noticed that the generated manager.yaml included:
```
        image: 10.194.216.114:5000/test/mem-ope:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
```
that I believe are leading to the 'OOMKilled' when trying to deploy some instances with the operator. Looking at the pod deployed when using OLM I did not see this limit being set ?
#### What did you expect to see?
I did not expect to see the restarts of the operator pod when deploying "manually".
#### What did you see instead? Under which circumstances?
operator restarting
```
NAME                                                    READY   STATUS    RESTARTS   AGE
memcached-operator-controller-manager-74fb64fdd-fw4s5   2/2     Running   2          117s
memcached-sample-9b765dfc8-hfzn4                        1/1     Running   0          74s
memcached-sample-9b765dfc8-qfns7                        1/1     Running   0          74s
memcached-sample-9b765dfc8-xdqzp                        1/1     Running   0          74s
[root@mycluster memcached-operator]# oc delete -f config/samples/cache_v1alpha1_memcached.yaml
memcached.cache.example.com "memcached-sample" deleted
[root@mycluster memcached-operator]# oc get pods
NAME                                                    READY   STATUS        RESTARTS   AGE
memcached-operator-controller-manager-74fb64fdd-fw4s5   1/2     OOMKilled     2          2m14s
memcached-sample-9b765dfc8-hfzn4                        1/1     Terminating   0          91s
memcached-sample-9b765dfc8-qfns7                        1/1     Terminating   0          91s
memcached-sample-9b765dfc8-xdqzp                        0/1     Terminating   0          91s
```
#### Environment
```
oc version
Client Version: 4.5.17
Server Version: 4.5.17
Kubernetes Version: v1.18.3+45b9524

operator-sdk version
operator-sdk version: "v1.1.0-8-g523caf67", commit: "523caf67df91ee13b95a26de75137f99e5e45c5c", kubernetes version: "v1.18.2", go version: "go1.15.3 linux/amd64", GOOS: "linux", GOARCH: "amd64"

go version
go version go1.15.3 linux/amd64

opm version
Version: version.Version{OpmVersion:"1.12.3", GitCommit:"", BuildDate:"2020-10-15T16:24:25Z", GoOs:"linux", GoArch:"amd64"}
```
**Operator type:**
/language go 

**Kubernetes cluster type:**
Openshift 4.5.17 deployed on Libvirt running on top of a CentOS 8 bare metal server

`$ operator-sdk version`
operator-sdk version: "v1.1.0-8-g523caf67", commit: "523caf67df91ee13b95a26de75137f99e5e45c5c", kubernetes version: "v1.18.2", go version: "go1.15.3 linux/amd64", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)
go version go1.15.3 linux/amd64

`$ kubectl version`
```
oc version
Client Version: 4.5.17
Server Version: 4.5.17
Kubernetes Version: v1.18.3+45b9524
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"6082e941e6d62f3a0c6ca8ba52927100948b1d0d", GitTreeState:"clean", BuildDate:"2020-10-22T08:26:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+45b9524", GitCommit:"45b9524", GitTreeState:"clean", BuildDate:"2020-10-25T05:12:54Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

#### Additional context

Sample operator memcached v1.1.x

**Comment by camilamacedo86** [comment] 2020-11-04 22:07
Hi @fckbo, 

For we try to help you we need further information such as: 

1 - Could you please provide the logs `kubectl logs deployment.apps/memcached-operator -n <ns>`?  
2 - Could you share the link for this Memcached operator? did you wrote that following the tutorial? are you using  the project in the testdata? 
3 - Is the problem not faced if you use make deploy IMG=<image> and let the operator be installed in the default ns instead of the following commands?

```
cd config/default/ && kustomize edit set namespace "default" && cd ../..
 make deploy IMG=10.194.216.114:5000/test/mem-ope:latest
 oc get pods
 oc apply -f config/samples/cache_v1alpha1_memcached.yaml
 oc get pods
 oc describe pods memcached-operator-controller-manager-74fb64fdd-fw4s5
```

4 - What is the  kustomize version used?

**Comment by camilamacedo86** [comment] 2020-11-09 20:05
Hi @fckbo,

Could you provide the above information request? Also, could you let us know more about your local env such as: is it using the default setup? Have you many other projects or just this one?

**Comment by camilamacedo86** [comment] 2020-12-09 16:29
Hi @fckbo, 

We are unable to reproduce your scenario. Because of these additional questions or made and we would need to have further info to be able to help you with it. Since it has been open for a while without a reply I will assume that you were able to figure ou it already. In this way, I hope that it is fine we close this one.  However, please feel free to ping us to re-open if you think that it would be required.

**Closed by camilamacedo86** 2020-12-09 16:29 UTC
Labels: language/go, triage/needs-information, triage/support
