### ISSUE TITLE
Metrics of the Cluster scoped operator causes can't list unstructured object errors

### ISSUE THREAD

**Issue by surajssd** [operator-framework/operator-sdk#1858] opened 2019-08-23 06:32 UTC
## Bug Report

**What did you do?**

Created an operator with operator sdk. Changed the scope of the operator to cluster wide using following doc:
https://github.com/operator-framework/operator-sdk/blob/v0.10.x/doc/operator-scope.md

Once I deployed the operator I get following errors:

```bash
E0822 17:26:58.302751       1 reflector.go:134] pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/tools/cache/reflector.go:95: Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

Operator is deployed in namespace: `suraj-system` and the CRD is called `surajconfig`.

The operator is cluster-scoped and is trying to get the CRD information at the namespace level, got this information from the `apiserver` logs running in verbose mode:

```log
I0823 04:59:31.205378       1 handler.go:153] kube-aggregator: GET "/apis/operator.suraj.io/v1alpha1/namespaces/suraj-system/surajconfigs" satisfied by nonGoRestful
I0823 04:59:31.205433       1 pathrecorder.go:247] kube-aggregator: "/apis/operator.suraj.io/v1alpha1/namespaces/suraj-system/surajconfigs" satisfied by prefix /apis/operator.suraj.io/v1alpha1/
I0823 04:59:31.205470       1 handler.go:153] kube-apiserver: GET "/apis/operator.suraj.io/v1alpha1/namespaces/suraj-system/surajconfigs" satisfied by nonGoRestful
I0823 04:59:31.205488       1 pathrecorder.go:253] kube-apiserver: "/apis/operator.suraj.io/v1alpha1/namespaces/suraj-system/surajconfigs" satisfied by NotFoundHandler
I0823 04:59:31.205510       1 handler.go:153] apiextensions-apiserver: GET "/apis/operator.suraj.io/v1alpha1/namespaces/suraj-system/surajconfigs" satisfied by nonGoRestful
I0823 04:59:31.205528       1 pathrecorder.go:247] apiextensions-apiserver: "/apis/operator.suraj.io/v1alpha1/namespaces/suraj-system/surajconfigs" satisfied by prefix /apis/
I0823 04:59:31.205588       1 wrap.go:47] GET /apis/operator.suraj.io/v1alpha1/namespaces/suraj-system/surajconfigs?limit=500&resourceVersion=0: (768.875µs) 404 [suraj-operator/v0.0.0 (linux/amd64) kubernetes/$Format 172.17.0.4:43584]
```

**What did you expect to see?**

I don't expect to see a stream of following errors in the operator logs:

```bash
E0822 17:26:58.302751       1 reflector.go:134] pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/tools/cache/reflector.go:95: Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

**Environment**
* operator-sdk version:

```bash
operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170
```

* go version:

```bash
go version go1.12.9 linux/amd64
```

* Kubernetes version information:

```json
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

minikube

* Are you writing your operator in ansible, helm, or go?

golang

**Possible Solution**

When I commented out the metrics code in the `main.go` those errors stopped showing up:

```go
	// if err = serveCRMetrics(cfg); err != nil {
	// 	log.Info("Could not generate and serve custom resource metrics", "error", err.Error())
	// }
```

I think the errors are coming from the code here:
https://github.com/operator-framework/operator-sdk/blob/abac23c897b898e6fecfb2c02fe318843ae9347f/pkg/kube-metrics/collector.go#L41

**Additional context**

The metrics generated are none. The IP below is of the service `suraj-operator-metrics`:

```console
$ curl 10.102.123.205:8686/metrics
# HELP surajconfig_info Information about the SurajConfig custom resource.
# TYPE surajconfig_info gauge
```

**Comment by surajssd** [comment] 2019-08-28 07:13
@hasbro17 the CRD is also cluster scoped. I am sorry if I wasn't clear before in my issue description.

**Comment by danacr** [comment] 2019-09-13 09:00
Same error here, both in minikube and KIND:

```
E0913 08:59:48.457117       1 reflector.go:134] pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/tools/cache/reflector.go:95: Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

**Comment by evadnoob** [comment] 2019-09-13 22:03
I am also seeing this issue, cluster is 1.13.10 and client from go.mod: `k8s.io/client-go => k8s.io/client-go v11.0.1-0.20190409021438-1a26190bd76a+incompatible` 

Every second:
```
E0913 21:08:50.722742       1 reflector.go:126] github.com/operator-framework/operator-sdk/pkg/kube-metrics/collector.go:67: Failed to list *unstructured.Unstructured: the server could not find the requested resource
E0913 21:08:51.723757       1 reflector.go:126] github.com/operator-framework/operator-sdk/pkg/kube-metrics/collector.go:67: Failed to list *unstructured.Unstructured: the server could not find the requested resource
E0913 21:08:52.724805       1 reflector.go:126] github.com/operator-framework/operator-sdk/pkg/kube-metrics/collector.go:67: Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

I also see this error when updating the status of a Cluster scoped custom resource.

**Comment by rcernich** [comment] 2019-09-19 20:41
Not to hijack, but I see similar errors when get/list/watch permissions are not on the service account for a specific resource, e.g.:

```
E0919 20:38:37.666313 1 reflector.go:134] github.com/operator-framework/operator-sdk/pkg/kube-metrics/collector.go:67: Failed to list *unstructured.Unstructured: selfsubjectaccessreviews.authorization.k8s.io is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot list resource "selfsubjectaccessreviews" in API group "authorization.k8s.io" in the namespace "istio-operator" 
```

I think it's okay to log the issue once and move on, but it really diminishes the usability of `--zap-devel` when the messages you want to see are buried in the spam.

**Comment by rcernich** [comment] 2019-09-19 20:43
Scratch that last comment, while I think it is an issue, I can modify the GVKs used in the generated `serveCRMetrics()` to eliminate my problems.

**Comment by holger-wg2** [comment] 2019-10-31 11:20
Setting the operatorNs in `serveCRMetrics()` to "" gets rid of that error. Which also makes sense, as the error gets created when the reflector cannot find the kind in a certain namespace. ResourceTypes with scope cluster are not associated to a Namespace

**Comment by RushinthJohn** [comment] 2020-01-04 06:28
I created an Ansible operator and am getting this same error stream.
My operator is just watching Namespaces and triggering a simple Ansible role.
Since this is an ansible-operator I am not able to apply any of the fixes mentioned above.

**Comment by RushinthJohn** [comment] 2020-01-04 08:47
> I created an Ansible operator and am getting this same error stream.
> My operator is just watching Namespaces and triggering a simple Ansible role.
> Since this is an ansible-operator I am not able to apply any of the fixes mentioned above.

I was able to solve this problem by setting the scope of the operator to watch all namespaces.

**Comment by bclermont** [comment] 2020-01-26 04:45
> Setting the operatorNs in `serveCRMetrics()` to "" gets rid of that error. Which also makes sense, as the error gets created when the reflector cannot find the kind in a certain namespace. ResourceTypes with scope cluster are not associated to a Namespace

you're right, that worked for me:

```diff
                return err
        }
        // Get the namespace the operator is currently deployed in.
-       operatorNs, err := k8sutil.GetOperatorNamespace()
-       if err != nil {
-               return err
-       }
+       // operatorNs, err := k8sutil.GetOperatorNamespace()
+       // if err != nil {
+       //      return err
+       // }
        // To generate metrics in other namespaces, add the values below.
-       ns := []string{operatorNs}
+       ns := []string{""}
        // Generate and serve custom resource specific metrics.
        err = kubemetrics.GenerateAndServeCRMetrics(cfg, ns, filteredGVK, metricsHost, operatorMetricsPort)
        if err != nil {
```

**Comment by camilamacedo86** [comment] 2020-02-26 01:45
I could check and reproduce this one. Following the detailed information. 

**Scenario**
- Create a go project as described in the [QuickStart](https://github.com/operator-framework/operator-sdk#create-and-deploy-an-app-operator)
- Then, apply the required changes for the operator to become cluster-scope. See the [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md) 
- However, now instead of using the `WATCH_NAMESPACE` as it was scaffold :

```yaml
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```

Replace it for as described in the [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md) or for an invalid value as, for example, the namespace where the CRs are applied only. See in https://github.com/operator-framework/operator-sdk/issues/2494#issuecomment-582525752 that the WATCH_NAMESPACE needs to cover the operator one and cannot just be where the CR's are applied.  

```yaml
            - name: WATCH_NAMESPACE
              value: ""
```

OR an invalid scenario as: ( E.g the operator will be deployed in ns1 )

```yaml
          - name: WATCH_NAMESPACE
              value: "ns2"
```

Then, install the resources as follows:
```
	$ kubectl create namespace ns1
	$ kubectl apply -f deploy/crds/app.example.com_appservices_crd.yaml -n ns1
	$ kubectl apply -f deploy/crds/app.example.com_appservice2s_crd.yaml -n ns1
	$ kubectl apply -f deploy/role.yaml -n ns1
	$ kubectl apply -f deploy/role_binding.yaml  -n ns1
	$ kubectl apply -f deploy/service_account.yaml  -n ns1
	$ kubectl apply -f deploy/operator.yaml -n ns1
	$ kubectl create namespace ns2
	$ kubectl apply -f deploy/crds/app.example.com_v1alpha1_appservice_cr.yaml -n  ns2
	$ kubectl apply -f deploy/crds/app.example.com_v1alpha1_appservice2_cr.yaml -n  ns2
```

So, the error will be faced:

```
{"level":"error","ts":1582679311.8035285,"logger":"k8sutil","msg":"Failed to get Pod","Pod.Namespace":"ns1","Pod.Name":"app-operator-c64d68b4f-s4x9x","error":"pods \"app-operator-c64d68b4f-s4x9x\" is forbidden: User \"system:serviceaccount:ns1:app-operator\" cannot get resource \"pods\" in API group \"\" in the namespace \"ns1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/camilamacedo/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/k8sutil.GetPod\n\t/Users/camilamacedo/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.12.1-0.20191203170929-d82e63bb13c9/pkg/k8sutil/k8sutil.go:128\ngithub.com/operator-framework/operator-sdk/pkg/leader.myOwnerRef\n\t/Users/camilamacedo/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.12.1-0.20191203170929-d82e63bb13c9/pkg/leader/leader.go:161\ngithub.com/operator-framework/operator-sdk/pkg/leader.Become\n\t/Users/camilamacedo/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.12.1-0.20191203170929-d82e63bb13c9/pkg/leader/leader.go:67\nmain.main\n\tapp-operator/cmd/manager/main.go:87\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","ts":1582679311.80369,"logger":"cmd","msg":"","error":"pods \"app-operator-c64d68b4f-s4x9x\" is forbidden: User \"system:serviceaccount:ns1:app-operator\" cannot get resource \"pods\" in API group \"\" in the namespace \"ns1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/camilamacedo/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tapp-operator/cmd/manager/main.go:89\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

For now, I'd recommend as solution used instead of any other value. 

```yaml
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```

We will be working on it to check how we can address this scenario.

c/c @hasbro17 @varshaprasad96

**Comment by camilamacedo86** [comment] 2020-02-26 02:06
I could check and reproduce this one following the detailed information. 

**Scenario**
- Create a go project as described in the [QuickStart](https://github.com/operator-framework/operator-sdk#create-and-deploy-an-app-operator)
- Then, apply the required changes for the operator to become cluster-scope. See the [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md) 
- Then, put a wrong namespace in the `ClusterRoleBinding` as follows.

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-operator
subjects:
- kind: ServiceAccount
  name: app-operator
  **namespace: otherone** -> ( I will use ns1 to deploy the operator. ) 
roleRef:
  kind: ClusterRole
  name: app-operator
  apiGroup: rbac.authorization.k8s.io

```

Then, install the resources as follows:
```
	$ kubectl create namespace ns1
	$ kubectl apply -f deploy/crds/app.example.com_appservices_crd.yaml -n ns1
	$ kubectl apply -f deploy/crds/app.example.com_appservice2s_crd.yaml -n ns1
	$ kubectl apply -f deploy/role.yaml -n ns1
	$ kubectl apply -f deploy/role_binding.yaml  -n ns1
	$ kubectl apply -f deploy/service_account.yaml  -n ns1
	$ kubectl apply -f deploy/operator.yaml -n ns1
	$ kubectl create namespace ns2
	$ kubectl apply -f deploy/crds/app.example.com_v1alpha1_appservice_cr.yaml -n  ns2
	$ kubectl apply -f deploy/crds/app.example.com_v1alpha1_appservice2_cr.yaml -n  ns2
```

So, the error will be faced:

```
{"level":"error","ts":1582679311.8035285,"logger":"k8sutil","msg":"Failed to get Pod","Pod.Namespace":"ns1","Pod.Name":"app-operator-c64d68b4f-s4x9x","error":"pods \"app-operator-c64d68b4f-s4x9x\" is forbidden: User \"system:serviceaccount:ns1:app-operator\" cannot get resource \"pods\" in API group \"\" in the namespace \"ns1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/camilamacedo/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/k8sutil.GetPod\n\t/Users/camilamacedo/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.12.1-0.20191203170929-d82e63bb13c9/pkg/k8sutil/k8sutil.go:128\ngithub.com/operator-framework/operator-sdk/pkg/leader.myOwnerRef\n\t/Users/camilamacedo/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.12.1-0.20191203170929-d82e63bb13c9/pkg/leader/leader.go:161\ngithub.com/operator-framework/operator-sdk/pkg/leader.Become\n\t/Users/camilamacedo/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.12.1-0.20191203170929-d82e63bb13c9/pkg/leader/leader.go:67\nmain.main\n\tapp-operator/cmd/manager/main.go:87\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","ts":1582679311.80369,"logger":"cmd","msg":"","error":"pods \"app-operator-c64d68b4f-s4x9x\" is forbidden: User \"system:serviceaccount:ns1:app-operator\" cannot get resource \"pods\" in API group \"\" in the namespace \"ns1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/camilamacedo/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tapp-operator/cmd/manager/main.go:89\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

So, the problem here was as described in the error the operator as not thee required permissions to get the resources to create the metrics. 

c/c @hasbro17 @varshaprasad96

**Comment by camilamacedo86** [comment] 2020-02-27 00:56
HI @bclermont,  @holger-wg2, 

Do the change described in https://github.com/operator-framework/operator-sdk/issues/1858#issuecomment-578468308 can make you no longer see issues regards RBCA permissions. However, it will not allow the kube metrics to be provided as well.

See the godoc of [GenerateAndServeCRMetrics](https://github.com/openshift/static-config-operator/blob/master/vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/metrics.go#L32-L36):

```
// GenerateAndServeCRMetrics generates CustomResource specific metrics for each custom resource GVK in operatorGVKs.
// A list of namespaces, ns, can be passed to ServeCRMetrics to scope the generated metrics. Passing nil or
// an empty list of namespaces will result in an error.
// The function also starts serving the generated collections of the metrics on given host and port.
func GenerateAndServeCRMetrics(cfg *rest.Config,
```

Also, see the comment in the code scaffolded by default via SDK:

```
// To generate metrics in other namespaces, add the values below.
ns := []string{operatorNs}
```
Note that it expects 1 .. N namespaces to be able to provide the metrics from them. 

In this way, it not shows the correct solution. Note that your scenario can be because it is missing permissions such as the POC described in https://github.com/operator-framework/operator-sdk/issues/1858#issuecomment-591198675, or because it not properly configured as you can check in the issue https://github.com/operator-framework/operator-sdk/issues/2494. However, I would like to let you know that we are working on it and trying to figure out if has some other scenario which is not covered that could cause this issue as well. 

c/c @varshaprasad96 @hasbro17

**Comment by camilamacedo86** [comment] 2020-02-27 23:55
HI @surajssd, 

The error `Failed to list *unstructured.Unstructured` which is faced means that the operator has not the permission to List some GroupVersionKind(GVK). However, more than one scenario can cause it, follow some examples:

- The operator is not with the required permissions (missing RBCA/roles).   See a POC in the comment https://github.com/operator-framework/operator-sdk/issues/1858#issuecomment-591198675 
- The `cache.manager` does not receive the namespace where the operator is deployed in. See the issue: https://github.com/operator-framework/operator-sdk/issues/2494 and the PR to address it: https://github.com/operator-framework/operator-sdk/pull/2522  
- Or when the WATCH_NAMESPACE is empty. See the issue: https://github.com/operator-framework/operator-sdk/issues/2602 and the PR to address it: https://github.com/operator-framework/operator-sdk/pull/2601
- And then, when third party APIs schemas were added which shows your scenario. So, the solution is to customized the implementation. See the PR to address it: https://github.com/operator-framework/operator-sdk/pull/2606

Please, let us know if you have anything more that you believe that should be addressed here. Otherwise, this issue will be closed when the PR https://github.com/operator-framework/operator-sdk/pull/2606 get merged.

**Closed** 2020-03-09 13:35 UTC
Labels: kind/bug, lifecycle/active, metrics

**Comment by robbie-demuth** [comment] 2020-03-23 18:33
@camilamacedo86 - I think there's still an outstanding issue here https://github.com/operator-framework/operator-sdk/pull/2601/files#r396670669

**Comment by camilamacedo86** [comment] 2020-03-23 20:51
We are addressing the above comment in: https://github.com/operator-framework/operator-sdk/issues/2707

**Comment by shaloba** [comment] 2021-01-07 08:43
i succeed to solve this issue with the following: 

first of all - i install the operator under my kube-system namespace

after install i edit the clusterrole binding (like below) and change the namespace of the service account from **default** to **kube-system**

`
kubectl edit clusterrolebinding pulsar-operator-cluster-role-binding
`

`
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2021-01-07T08:34:12Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
    manager: kubectl
    operation: Update
    time: "2021-01-07T08:34:12Z"
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:subjects: {}
    manager: kubectl
    operation: Update
    time: "2021-01-07T08:40:06Z"
  name: pulsar-operator-cluster-role-binding
  resourceVersion: "6538124"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/pulsar-operator-cluster-role-binding
  uid: 3e6fba96-7fe7-4b01-8fbe-8dab82853bcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pulsar-operator
subjects:
- kind: ServiceAccount
  name: pulsar-operator
  namespace: kube-system
`
