### ISSUE TITLE
Operator-sdk errors under WSL

### ISSUE THREAD

**Issue by forvaidya** [operator-framework/operator-sdk#3971] opened 2020-10-04 17:23 UTC
## Bug Report
operator-sdk init --domain=example.com --repo=github.com/example-inc/memcached-operator

**Errors** 

```
/root/go/pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/pkg/version/version.go:23:2: rename /root/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8.tmp-262818200 /root/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8:
permission denied
```

#### What did you do?

tried to build in WSL ubuntu with root user and non root user

#### What did you expect to see?

successful generation of operator

#### Environment

**Operator type:**

/language go 

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

go version go1.15.2 linux/amd64

`$ kubectl version`

**Comment by forvaidya** [comment] 2020-10-05 07:14
I think it is common to any module not just this project
I will wait for a couple of days if anyone have advice for me or else I will close this ticket

**Comment by kensipe** [comment] 2020-10-05 19:33
@forvaidya thanks for the report!    

There are a few things question / comment on regarding this report:

1. It isn't clear why WSL and not WSL2.  WSL2 is going to provide full kernel support:  https://docs.microsoft.com/en-us/windows/wsl/compare-versions

2. Currently Operator SDK is only tested with Go 1.13 (which is likely not an issue here... just wanted to make sure you were aware)

3. The issue you are reporting looks to be tied to client-go (a dependency of operator-sdk).   after making sure the env is correct, if you are still having issue you may want to file it under that project:  https://github.com/kubernetes/client-go/issues

4. It is important to note that operator-sdk does not provide windows support as of yet.   We have nothing in our CI env etc. to ensure support for this platform.   That said, it is great to see reports of this nature which provide an indication of platform demand, which weighs into future support.   It is worth stating that even though we don't have full support there are a number of members of the community that make efforts to help on non-supported platforms.

I am closing for now... as the issue is clearly upstream and should be reported there.  I don't see any task for operator-sdk to accomplish to resolve this issue.

If you feel this is in error or have more details to provide which needs addressing... please re-open.  thanks!

**Closed by kensipe** 2020-10-05 19:33 UTC
Labels: language/go
