### ISSUE TITLE
not able to create Ansible operator

### ISSUE THREAD

**Issue by nirrozenbaum** [operator-framework/operator-sdk#2732] opened 2020-03-27 12:08 UTC
## Bug Report

**What did you do?**
created an ansible operator from scratch after using the sdk scaffolding.
I used `operator-sdk new pong-operator --type ansible --generate-playbook --api-version pong.example.com/v1alpha1 --kind Pong` to generate the skeleton, then I added my logic under roles/pong. trying to build the operator using `operator-sdk build` command

**What did you expect to see?**
a successful build of docker image.

**What did you see instead? Under which circumstances?**
`
operator-sdk build xx
INFO[0000] Building OCI image xx                        
Sending build context to Docker daemon  117.8kB
Step 1/6 : FROM quay.io/operator-framework/ansible-operator:v0.16.0
 ---> 19ba5006a265
Step 2/6 : COPY requirements.yml ${HOME}/requirements.yml
 ---> Using cache
 ---> 0e2d93d3cd4a
Step 3/6 : RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible
 ---> Running in 33e30a3719b9
OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown
Error: failed to output build image xx: failed to exec []string{"docker", "build", "-f", "build/Dockerfile", "-t", "xx", "."}: exit status 1
Usage:
  operator-sdk build <image> [flags]

Flags:
      --go-build-args string      Extra Go build arguments as one string such as "-ldflags -X=main.xyz=abc"
  -h, --help                      help for build
      --image-build-args string   Extra image build arguments as one string such as "--build-arg https_proxy=$https_proxy"
      --image-builder string      Tool to build OCI images. One of: [docker, podman, buildah] (default "docker")

Global Flags:
      --verbose   Enable verbose logging
`

**Environment**
* operator-sdk version: 
`operator-sdk version: "v0.16.0", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"
`

* go version:
`go version go1.13.6 linux/amd64`

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
regular

* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**

**Additional context**

**Comment by camilamacedo86** [comment] 2020-03-27 12:18
HI @nirrozenbaum, 

Could you please let us know what is the Docker version used by you?  
Also, by checking the above logs shows that your Dockerfile was created. So, could you please add here what do you face if you try to build it with docker by running `docker build -f build/Dockerfile .` from the root path of your project?

**Comment by nirrozenbaum** [comment] 2020-03-27 14:58
Docker version:
```
docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:27:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:25:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
docker build -f build/Dockerfile .
Sending build context to Docker daemon  117.8kB
Step 1/6 : FROM quay.io/operator-framework/ansible-operator:v0.16.0
 ---> 19ba5006a265
Step 2/6 : COPY requirements.yml ${HOME}/requirements.yml
 ---> Using cache
 ---> 0e2d93d3cd4a
Step 3/6 : RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible
 ---> Running in d98348c9922f
OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown
```

**Comment by nirrozenbaum** [comment] 2020-03-29 06:55
I've tried to git clone `https://github.com/operator-framework/operator-sdk-samples` and build the ansible memcached sample, and seeing the same error.
tried googling a bit a saw there might be a error with this docker version.
I downgraded docker version to 18.06.1 and now I'm seeing a different error:
```
docker build -f build/Dockerfile .
Sending build context to Docker daemon  74.24kB
Step 1/5 : FROM quay.io/operator-framework/ansible-operator:v0.16.0
 ---> 19ba5006a265
Step 2/5 : COPY requirements.yml ${HOME}/requirements.yml
 ---> Using cache
 ---> 41a0d6d8437d
Step 3/5 : RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible
 ---> Running in 59031ae2d135
Process install dependency map
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno -2] Name or service not known>
The command '/bin/sh -c ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible' returned a non-zero code: 1
```

**Comment by camilamacedo86** [comment] 2020-03-29 17:29
Hi @nirrozenbaum, 

I am unable to reproduce this errors, however, my local env is mac os x and my. ocker version is `17.09.1-ce` See.

```
 $ docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

See that the error `"process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown` shows an issue with your docker installation. See: https://stackoverflow.com/questions/57914696/oci-runtime-create-failed-copying-bootstrap-data-to-pipe-caused-write-init-p and https://meta.discourse.org/t/docker-copying-bootstrap-data-to-pipe-caused-write-init-p-broken-pipe/108947/34.

**Comment by nirrozenbaum** [comment] 2020-03-30 06:21
hi @camilamacedo86,
I was also suspecting something is wrong with the env so I updated the versions of all components to the latest (go, kubectl, docker).
after updating all versions is works.
thanks!

**Comment by camilamacedo86** [comment] 2020-03-30 11:58
I am closing this as sorted out. Really thank you for your reply.

**Closed** 2020-03-30 11:58 UTC
Labels: ansible-operator, triage/support

**Comment by asmacdo** [comment] 2020-07-01 20:29
In case anyone else sees this, I ran into this after starting a fresh env on Fedora 32. The resolution for me was to add `network=host`

Reproducer

``` 
$ docker build -f build/Dockerfile .           
       
Sending build context to Docker daemon  10.47MB
Step 1/5 : FROM quay.io/operator-framework/ansible-operator:latest
 ---> b0d150906bc9
Step 2/5 : COPY requirements.yml ${HOME}/requirements.yml
 ---> Using cache
 ---> 3ebe7675fc92
Step 3/5 : RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible
 ---> Running in c4a2b55d0ae6
Process install dependency map
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno -2] Name or service not known>
The command '/bin/sh -c ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible' returned a non-zero code: 1
```

Info

``` 
$ docker version

Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Fixed

```
$ docker build -f build/Dockerfile . --network=host  

Sending build context to Docker daemon  10.47MB
Step 1/5 : FROM quay.io/operator-framework/ansible-operator:latest
 ---> b0d150906bc9
Step 2/5 : COPY requirements.yml ${HOME}/requirements.yml
 ---> Using cache
 ---> 3ebe7675fc92
Step 3/5 : RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible
 ---> Running in 2f313b4f0792
Process install dependency map
Starting collection install process
Installing 'community.kubernetes:0.11.1' to '/opt/ansible/.ansible/collections/ansible_collections/community/kubernetes'
Installing 'operator_sdk.util:0.0.0' to '/opt/ansible/.ansible/collections/ansible_collections/operator_sdk/util'
Removing intermediate container 2f313b4f0792
 ---> 1a7115325c52
Step 4/5 : COPY watches.yaml ${HOME}/watches.yaml
 ---> 8fd9228253b6
Step 5/5 : COPY roles/ ${HOME}/roles/
 ---> 42825becf2b9
Successfully built 42825becf2b9
```

**Comment by tengqm** [comment] 2020-07-02 01:14
@asmacdo Thanks for sharing. Maybe we need to document this tip somewhere.

**Comment by asmacdo** [comment] 2020-07-08 17:49
@tengqm after restarting NetworkManager, I was able to run without network=host. Since this is an environmental problem with Docker, it would be outside the scope of this project to document it, IMO.

**Comment by tengqm** [comment] 2020-07-09 03:42
@asmacdo Glad to know the problem is solved. Thanks for sharing the experience.
