### ISSUE TITLE
make manifests isn't creating ./config/crds if ./apis/ has own go.mod 

### ISSUE THREAD

**Issue by sTb1337** [operator-framework/operator-sdk#5322] opened 2021-10-25 15:44 UTC
#### What did you do?
1. create operator-sek project with some apis
2. defined some types within ./apis/../.._types.go
3. execute "go mod init && go mod tidy" within ./apis/
4. tried to generate ./configs/crds by executing "make manifests"

#### What did you expect to see?
Updated / created CRDs yaml files within ./config/crd/bases/...

#### What did you see instead? Under which circumstances?
There were no CRDs yaml files within ./config/crd/bases/..

#### Environment

**Operator type:go**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version: "v1.13.1", commit: "1659ab58a073999463e6dcdf18bdc359a315e091", kubernetes version: "v1.21", go version: "go1.17.2", GOOS: "darwin", GOARCH: "amd64"`

`$ go version go1.17.2 darwin/amd64` 

`$ kubectl version Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
`

#### Possible Solution

I was able to create a workaround. Add the following lines within Makefile:

`manifests2: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	cd $(shell pwd)/apis/; \
	$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=$(shell pwd)/config/crd/bases`

After executing "make manifests2" the CRDs yaml files within ./config/crd/bases/... were created/updated.

**Comment by varshaprasad96** [comment] 2021-11-17 07:14
this is not a release blocker, moving it to the next milestone. Will need some time to dig into this.

**Comment by sTb1337** [comment] 2021-11-17 07:53
This also applies to "make generate"

**Comment by varshaprasad96** [comment] 2021-11-27 19:20
According to the controller-gen, the command line scaffolded by `Makefile` evaluates all the go `packages` containing the `markers` present in the current directory. This is specified by the `path` argument ([ref](https://book.kubebuilder.io/reference/controller-gen.html#controller-gen-cli)). Having `_types.go` defined in a separate go module inside `apis/` folder could be the cause of the issue you have mentioned. This is the reason `markers` are not getting evaluated when controller-gen command is run from the root of the project. Instead when run inside `apis/` (as you have done here: `cd $(shell pwd)/apis/`) it seems to work right. This seems to be the intended behavior of controller-gen.

Also, the output artifact directory could be anything, here it seems to be `config/crd/bases`. The tweak done here is due to having the packages containing markers in a separate module. The same thing holds good with `make generate` too.

Please let me know if this answers your question.

**Comment by sTb1337** [comment] 2021-12-13 11:43
Thank you @varshaprasad96. This answers my question.

**Closed** 2022-05-12 18:16 UTC
Labels: triage/support, lifecycle/rotten, language/go
