### ISSUE TITLE
deepcopy.go:885] Hit an unsupported type invalid type for invalid type

### ISSUE THREAD

**Issue by roysahar-ibm** [operator-framework/operator-sdk#3969] opened 2020-10-03 15:51 UTC
#### What did you do?

1. Built docker container with the following:
`FROM golang:1.13.8`
 `WORKDIR /go/src/github.com/IBM/ibm-block-csi-operator`
 `ENV GO111MODULE=on \`
   `GOROOT=/usr/local/go`
 `RUN go get github.com/onsi/ginkgo/ginkgo`
  `RUN RELEASE_VERSION=v0.16.0 \`
    `&& ARCH=$(uname -m) \`
    `&& SDK_ASSET=operator-sdk-${RELEASE_VERSION}-${ARCH}-linux-gnu \`
    `&& curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/${SDK_ASSET} \`
	`&& chmod +x ${SDK_ASSET} \`
	`&& mkdir -p /usr/local/bin/ \`
	`&& cp ${SDK_ASSET} /usr/local/bin/operator-sdk \`
	`&& rm ${SDK_ASSET}`
  `COPY . .`
  `CMD ["make", "test"]`

2. Enter container - `docker run -it --entrypoint /bin/bash 387656a9d9f8`

3. Execute - `export GOROOT=$(go env GOROOT)`
                       `operator-sdk generate k8s`
    

#### What did you expect to see?

Expected to built the operator successfully.

#### What did you see instead? Under which circumstances?

Got - `F1003 15:30:36.479393      43 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from github.com/IBM/ibm-block-csi-operator/pkg/apis/csi/v1.CSISidecar`

#### Environment

**Operator type:**

language go

**Kubernetes cluster type:**

`$ operator-sdk version`
`operator-sdk version: "v0.16.0", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"`

`$ go version` (if language is Go)
`go version go1.13.8 linux/amd64`

`$ kubectl version`

No kubectl used
#### Additional context

GO ENV Output:

`GO111MODULE="on"`
`GOARCH="amd64"`
`GOBIN=""`
`GOCACHE="/root/.cache/go-build"`
`GOENV="/root/.config/go/env"`
`GOEXE=""`
`GOFLAGS=""`
`GOHOSTARCH="amd64"`
`GOHOSTOS="linux"`
`GONOPROXY=""`
`GONOSUMDB=""`
`GOOS="linux"`
`GOPATH="/go"`
`GOPRIVATE=""`
`GOPROXY="https://proxy.golang.org,direct"`
`GOROOT="/usr/local/go"`
`GOSUMDB="sum.golang.org"`
`GOTMPDIR=""`
`GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"`
`GCCGO="gccgo"`
`AR="ar"`
`CC="gcc"`
`CXX="g++"`
`CGO_ENABLED="1"`
`GOMOD="/go/src/github.com/IBM/ibm-block-csi-operator/go.mod"`
`CGO_CFLAGS="-g -O2"`
`CGO_CPPFLAGS=""`
`CGO_CXXFLAGS="-g -O2"`
`CGO_FFLAGS="-g -O2"`
`CGO_LDFLAGS="-g -O2"`
`PKG_CONFIG="pkg-config"`
`GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build458818196=/tmp/go-build -gno-record-gcc-switches"`

Please note that I dig all over and also followed the faq page - https://v0-18-x.sdk.operatorframework.io/docs/faq/#i-see-deepcopy-errors-and-image-build-fails-how-do-i-fix-this
But it did not help.
Also this behaviour started ~ 2 weeks ago on old code (go) that have been succeeded to generate operator before.

**Comment by camilamacedo86** [comment] 2020-10-05 11:44
The error faced means that it has a really invalid type defined or your go env is not setup properly. 
I'd like to recommend that you check your project and local env for example, to see if you have more than one go version installed. 

> Also this behaviour started ~ 2 weeks ago on old code (go) that have been succeeded to generate operator before.

Note that the old sdk CLI versions did not change at all. So, all lead to a misconfiguration locally.  

Also, note that versions lower than 0.19 is no longer supported and it is recommended migrate the projects to use 1.0+. See: https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/

**Comment by steveyang95** [comment] 2020-10-23 17:33
@camilamacedo86 Can you confirm that nothing has changed?
I have the following versions/vars:

```operator-sdk version: "v0.15.1", commit: "e35ec7b722ba095e6438f63fafb9e7326870b486", go version: "go1.13.6 linux/amd64"
go version go1.13.6 linux/amd64
GO111MODULE=on
GOLANG_VERSION=1.13.6
GOPATH="/go"
GOROOT="/usr/local/go"
```

And I also get:

```INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [sky:[utils v1alpha1], ] 
F1015 21:42:36.661060     125 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from ./pkg/apis/sky/v1alpha1.Sky
```

I ran this 2 months ago in August and it worked fine. I come back to it now and no matter what I try with the Go configurations and checking the file for invalid types, I can't get past it. I also tried running my August version on CircleCI (rerunning the same exact build) and it fails with the same `invalid type` issue so it is hard to believe that nothing has changed.

----

Also, what is the best way to upgrade 0.15.1 to the latest 1.1.x+ versions? When I try to go from 0.15.1 to 0.16.0, my `go mod tidy` fails with:
```build bitbucket.org/nubeva/kates/cmd/manager: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
	github.com/Azure/go-autorest v11.2.8+incompatible (/go/pkg/mod/github.com/!azure/go-autorest@v11.2.8+incompatible/autorest)
	github.com/Azure/go-autorest/autorest v0.9.0 (/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.0)
Error: failed to build operator binary: failed to exec []string{"go", "build", "-o", "/home/circleci/project/workspace/src/bubble/kates/microservices/operator/kates/build/_output/bin/kates", "-gcflags", "all=-trimpath=/home/circleci/project/workspace/src/bubble/kates/microservices/operator", "-asmflags", "all=-trimpath=/home/circleci/project/workspace/src/bubble/kates/microservices/operator", "-ldflags", "-X=main.packageVersion=8834b900-c171-44db-a6bc-ffb859d2855c", "bitbucket.org/nubeva/kates/cmd/manager"}: exit status 1
```

And the issues continue to come up...Do you have any other recommendations for a smoother process?

**Comment by camilamacedo86** [comment] 2020-10-23 18:39
Hi @steveyang95, 

>  @camilamacedo86 Can you confirm that nothing has changed?

The binaries which are released never changes. 

> I ran this 2 months ago in August and it worked fine. I come back to it now and no matter what I try with the Go configurations and checking the file for invalid types, I can't get past it. I also tried running my August version on CircleCI (rerunning the same exact build) and it fails with the same invalid type issue so it is hard to believe that nothing has changed.

See if you have a fixed go version on the CI. For example, if you have only go 1.13.x it will always bring the latest released of go which can be related to your scenario. Note that the error faced means that it has a really invalid type defined or your go env is not set up properly. So, it can be the go env set by default in version  1.13.x related to  1.13.x+n .

> In order to fix this, you can try to export the GOROOT environment variable which is the common root cause for it as well. 
> $ export GOROOT=$(go env GOROOT)

Regards this scenario see that the repo has many issues raised with the same: https://github.com/operator-framework/operator-sdk/issues?q=is%3Aissue+is%3Aclosed+Hit+an+unsupported+type+invalid+type+for+invalid+type%2C+from 

> Also, what is the best way to upgrade 0.15.1 to the latest 1.1.x+ versions? When I try to go from 0.15.1 to 0.16.0, my go mod tidy fails with:

I'd recommend you follow the migrations guides and upgrade all until you reach 0.19.x for then follow up the migration guide to 1.0+. Note that the migration guides have all steps and there are mainly cut and past. also, I'd recommend you clone the project locally and work on with the git tags for the versions. If you run `make install` for each tag you will have an SDK with the specific version installed locally and you can check it with the command `operator-sdk version`. See: https://sdk.operatorframework.io/docs/installation/install-operator-sdk/#compile-and-install-from-master

So, it means:

- upgrade from 0.15.1 to 0.16.x : https://sdk.operatorframework.io/docs/upgrading-sdk-version/version-upgrade-guide/#v016x
- then, upgrade from 0.16.x to 0.17.x: https://sdk.operatorframework.io/docs/upgrading-sdk-version/version-upgrade-guide/#v017x
- then, from 0.17.x to 0.18.x: https://sdk.operatorframework.io/docs/upgrading-sdk-version/v0.18.0/
- until be 0.18.x to 0.19.x: https://sdk.operatorframework.io/docs/upgrading-sdk-version/v0.19.0/

After that, you can just follow up the guide for 1.0+ with the guide: https://sdk.operatorframework.io/docs/building-operators/golang/migration/. 

Also, I'd like to kindly ask for you to raise new issues instead of adding a different question in a pre-existent one. See that the info in the issues can help others as well so it is easier if we keep one subject/close questions/bug/rfe per issue.

**Comment by camilamacedo86** [comment] 2020-10-23 18:49
Following a summary, if you are facing the same:

Regards the issue: `deepcopy.go:885] Hit an unsupported type invalid type for invalid type
#3969`

**Usually it means an issue with your local go env, however, it also can be a legitimate issue where the type is invalid**

1. Ensure that you have only one go version installed and the same version supported by the tool
2. Check your go env vars:

- In order to fix this, you can try to export the GOROOT environment variable which is the common root cause/solution
`$ export GOROOT=$(go env GOROOT)`

- Also, ensure that your GOPROXY is `GOPROXY="https://proxy.golang.org,direct"`

I am closing this as duplicated of  https://github.com/operator-framework/operator-sdk/issues?q=is%3Aissue+is%3Aclosed+Hit+an+unsupported+type+invalid+type+for+invalid+type%2C+from

**Closed by camilamacedo86** 2020-10-23 18:49 UTC
Labels: triage/needs-information
