### ISSUE TITLE
Unable to bundle-upgrade

### ISSUE THREAD

**Issue by J0zi** [operator-framework/operator-sdk#5616] opened 2022-03-23 10:23 UTC
#### What did you do?
```
operator-sdk run bundle quay.io/community-operators-pipeline/flux:v0.25.2

operator-sdk run bundle-upgrade quay.io/operator_testing/flux:testing0.25.3 
```

#### What did you expect to see?

Successful upgrade

#### What did you see instead? Under which circumstances?

```
operator-sdk run bundle-upgrade quay.io/operator_testing/flux:testing0.25.3       
INFO[0001] Found existing subscription with name flux-v0-25-2-sub and namespace default 
INFO[0001] Found existing catalog source with name flux-catalog and namespace default 
INFO[0009] Successfully created registry pod: quay-io-operator-testing-flux-testing0-25-3 
INFO[0009] Updated catalog source flux-catalog with address and annotations 
INFO[0009] Deleted previous registry pod with name "quay-io-community-operators-pipeline-flux-v0-25-2" 
INFO[0048] Approved InstallPlan install-5xp65 for the Subscription: flux-v0-25-2-sub 
INFO[0048] Waiting for ClusterServiceVersion "default/flux.v0.25.3" to reach 'Succeeded' phase 
INFO[0048]   Waiting for ClusterServiceVersion "default/flux.v0.25.3" to appear 
FATA[0120] Failed to run bundle upgrade: error waiting for CSV to install: timed out waiting for the condition 
```
kubectl logs catalog-operator-5c4997c789-47bxt -n olm
```
time="2022-03-22T11:32:37Z" level=info msg="checking flux.v0.25.2"
time="2022-03-22T11:32:37Z" level=info msg="checking packageserver"
time="2022-03-22T11:32:37Z" level=info msg="checking packageserver"
time="2022-03-22T11:32:37Z" level=info msg="checking flux.v0.25.2"
time="2022-03-22T11:32:42Z" level=info msg="Processing olmConfig"
time="2022-03-22T11:32:43Z" level=info msg="Processing olmConfig"
time="2022-03-22T11:32:47Z" level=info msg="checking flux.v0.25.2"
time="2022-03-22T11:32:47Z" level=info msg="checking packageserver"
time="2022-03-22T11:32:47Z" level=info msg="checking flux.v0.25.2"
time="2022-03-22T11:32:52Z" level=info msg="Processing olmConfig"
time="2022-03-22T11:32:52Z" level=info msg="Processing olmConfig"
time="2022-03-22T11:33:30Z" level=info msg="checking packageserver"
time="2022-03-22T11:33:30Z" level=info msg="checking flux.v0.25.2"
time="2022-03-22T11:33:35Z" level=info msg="Processing olmConfig"
{"level":"error","ts":1647948830.2065864,"logger":"controllers.operatorcondition","msg":"Unable to find operatorcondition","request":"default/flux.v0.25.3","error":"OperatorCondition.operators.coreos.com \"flux.v0.25.3\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1647948830.2067282,"logger":"controller.operatorcondition","msg":"Reconciler error","reconciler group":"operators.coreos.com","reconciler kind":"OperatorCondition","name":"flux.v0.25.3","namespace":"default","error":"OperatorCondition.operators.coreos.com \"flux.v0.25.3\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
```

#### Environment

**Kubernetes cluster type:**

`kind cluster` with k8s 1.21

#### Additional information

 You replicate easily by just 2 commands.
```
operator-sdk run bundle quay.io/community-operators-pipeline/flux:v0.25.2
operator-sdk run bundle-upgrade quay.io/operator_testing/flux:testing0.25.3 
```
or
```
operator-sdk run bundle quay.io/community-operators-pipeline/apicurito:v1.0.2
operator-sdk run bundle-upgrade quay.io/operator_testing/apicurito:testing-apicurito.v1.0.3
```
 
 It is blocking us delivering a new feature - Operator upgrade testing.

**Comment by camilamacedo86** [comment] 2022-03-23 11:51
It shows the same scenario of the following issues: 
- https://github.com/operator-framework/operator-sdk/issues/5413
- https://github.com/operator-framework/operator-sdk/issues/5410

Additionally, it shows that we need to improve the run bundle to help us know why is not possible to get the operator conditional: https://github.com/operator-framework/operator-sdk/issues/3691#issuecomment-670695082

It might be the same scenario of:
https://github.com/operator-framework/operator-sdk/issues/4650

@J0zi the run bundle does not work if the bundle is not published in a public registry. 
Could you try: https://github.com/operator-framework/operator-sdk/issues/4650#issuecomment-808454359

c/c @rashmigottipati

**Comment by rashmigottipati** [comment] 2022-03-28 16:56
I was able to reproduce this issue. The registry pod and other resources are being successfully for the image, so it might not be an issue related to pulling a private bundle image. The catalog source that's created seems healthy as well. The bundle image is hosted on a public registry and is also pull-able locally so secrets don't have to be provided as well. 

Looks like the `catalog-operator` resource that's a part of OLM (this resource isn't being created during `run bundle` or `run bundle-upgrade`) is unable to get the operator condition and is causing the CSV to timeout with the error `FATA[0120] Failed to run bundle upgrade: error waiting for CSV to install: timed out waiting for the condition`  and we have to investigate that.

**Comment by laxmikantbpandhare** [comment] 2022-04-19 14:02
@J0zi - I am looking into it. I will update you soon.

**Comment by jeloba** [comment] 2022-04-21 13:35
I have a similar issue (same error). It started showing up after updating a working setup to OLM 0.20.0 from 0.18.1.

I inspected the cluster and found the following:

* the catalog is installed correctly and running
* the `packagemanifest` under tests show up
* a subscription is created
* an install plan was created, waiting for manual approval

**Comment by J0zi** [comment] 2022-04-25 09:05
@laxmikantbpandhare @rashmigottipati any update?

**Comment by VenkatRamaraju** [comment] 2022-04-27 16:17
Hey @J0zi,

My suspicion is that the problem is with the version naming. I'm able to install `apicurito:v1.0.1` and upgrade it to `apicurito:v1.0.2`. These operators follow the general semver naming conventions. However, I am not able to upgrade using the examples you provided (timeout). It may be due to the "testing" prefix on the tags of these bundle images.

**Comment by vanessarakoczy** [comment] 2022-05-06 16:46
Hi @J0zi, 
We are experiencing same issue as well.
Our naming convention is correct, we've tried reverting our OLM back to version 0.18.3 to see if it would resolve anything, but no such luck. Was there any other resolution you were able to find?

**Comment by laxmikantbpandhare** [comment] 2022-05-06 17:09
@vanessarakoczy - Could you please share which images you are trying to upgrade. I will try this locally.

**Comment by vanessarakoczy** [comment] 2022-05-06 18:45
@laxmikantbpandhare these are the commands we're trying:

operator-sdk run bundle quay.io/operatorhubio/app-director-operator:v0.0.2 --skip-tls-verify

**Comment by laxmikantbpandhare** [comment] 2022-05-08 21:21
@vanessarakoczy - I am able to reproduce the issue locally.

**Comment by camilamacedo86** [comment] 2022-05-18 14:05
This issue shows to be the scenario clarified and tracked via: https://github.com/operator-framework/operator-sdk/issues/5773. To avoid duplication and centralize the info, it seems like we can close this one in favour of https://github.com/operator-framework/operator-sdk/issues/5773.

Note that some workarounds were also proposed in the issue: https://github.com/operator-framework/operator-sdk/issues/5773. Please, ensure that you check if the proposed workarounds can help you out. If you check that your problem is not the same scenario, we would like to ask for you re-open this issue. 

Thank you for your attention and collaboration.

**Closed by camilamacedo86** 2022-05-18 14:05 UTC
Labels: triage/support
