### ISSUE TITLE
shortcircuiting reconcile loop in ansible

### ISSUE THREAD

**Issue by atinsood** [operator-framework/operator-sdk#2198] opened 2019-11-14 20:47 UTC
## Question

How do you accomplish a scenario like this in ansible? I have a secret(potential containing db credentials) that needs to be up, before my controller starts installing the product. In golang I would assume you would keep throwing an error in the reconcile loop and have the reconcile loop run again. How do you accomplish a similar flow in ansible?

This is what you could have done in the golang code and you can short circuit the reconcile loop.

I understand that for the above case specifically, one can rely on the fact that the pod mounting the secrets would keep crashing till the secret is in place, but the question along the lines of how you would accomplish a broad scenario like this.

```
Based on the return values, Result and error, the Request may be requeued and the reconcile loop may be triggered again:

// Reconcile successful - don't requeue
return reconcile.Result{}, nil
// Reconcile failed due to error - requeue
return reconcile.Result{}, err
// Requeue for any reason other than error
return reconcile.Result{Requeue: true}, nil

// Reconcile for any reason than error after 5 seconds
return reconcile.Result{RequeueAfter: time.Second*5}, nil
```

**Comment by atinsood** [comment] 2019-11-15 14:35
@camilamacedo86 this is more of a question on whether such a behavior even exists in the first place. if not I can take a stab at the code and see what would it take to implement this if it makes sense to implement this,

**Comment by atinsood** [comment] 2019-11-15 15:22
actually this is what I tried ```- name: Search for secrets
  register: secret_list
  k8s_facts:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: 'missing-secret-xxx'
    
- name: assert that secret was found
  assert:
   that:
     - secret_list.resources | length > 0
   fail_msg: " {{secret_list | length }} must be greater than 0"
   success_msg: "{secret_list | length }} was greater than 0"```

so the loop did error out because the secret was not present but no successive reconcile loop was triggered and I am not sure how to force that.

**Comment by glothriel** [comment] 2019-12-12 12:52
I have exactly the same problem with ansible operator. If I don't set `reconcilePeriod` in watches.yml it doesn't ever reconcile. If I set one it is spamming reconcile loops no mater if task failed or succeeded.

**Comment by camilamacedo86** [comment] 2019-12-13 23:53
Hi @atinsood and @glothriel, 

I understand that your scenario is: `I'd like to ensure that a task was done before continuing ...`. Then, in this case, did you try to use Ansible Conditionals. See the Ansible doc [Waits for a condition before continuing](https://docs.ansible.com/ansible/latest/modules/wait_for_module.html#examples). Also, I'd like to suggest you check the [doc](https://docs.openshift.com/container-platform/4.1/applications/operator_sdk/osdk-ansible.html#osdk-ansible-k8s-module-testing-locally_osdk-ansible) to know how you can use the k8s module as well. It has an example over a task that that wait for the namespace be with `state: present` and then, `state: absent`. Also, you can check [here](https://github.com/operator-framework/operator-sdk/blob/cf1ca34ce262c45e94504083ff51ef1606a6f212/test/ansible-inventory/molecule/test-local/playbook.yml#L31) some examples that can help you with. 

Following a more full explanation over the watch feature since you made few comments about it.

The feature which will trigger the reconcile when a resource is changed is called the watch. See the [Memcached](https://github.com/operator-framework/operator-sdk-samples/tree/master/ansible/memcached-operator) example. It has a watch feature [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/memcached-operator/watches.yaml) which is implemented for the Memcached and will retrigger the reconcile when any change such as to create, to update and to delete the Memcached resource be faced. 

Note that, another way to re-trigger the reconcile is by setting `reconcilePeriod` which will re-trigger te reconcile after a period, ever x time, which shows been used by @glothriel. To understand the watch feature check the ansible user guide [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md#watches-file). And then, to know more about the watch options see the [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/advanced_options.md#watches-file-options)

Please, let us know if the above information provided attend your expectations and if we can close this one or if with it you still unable to attend your need.

**Comment by glothriel** [comment] 2019-12-14 16:26
Thanks for the response @camilamacedo86, it's very clear. I'm aware about the behaviour you described, but it was surprising to me, that the framework doesn't operate in the mode Kubernetes controllers generally tend to follow - triggering reconciliation loops with exponential back-off after consecutive fails to reconcile a resource.

**Comment by camilamacedo86** [comment] 2019-12-14 19:04
@fabianvf could you also give a hand here and let us know if you see if I am missing something here?

**Comment by fabianvf** [comment] 2019-12-18 16:30
@glothriel if you're failing the playbook (eg, with the `fail` module), and it's not automatically requeuing with exponential backoff then that's definitely a bug. If you're exiting without a failure that will be viewed as a success though, so double check that the playbook run is marked as failed

**Comment by glothriel** [comment] 2020-01-07 08:39
Thanks @fabianvf I will try to reproduce on some minimal example this week

**Comment by camilamacedo86** [comment] 2020-01-07 09:28
Hi @glothriel, 

I am closing this one since shows all sorted out. Please, feel free to raise a new issue as a bug if it does not work as described by @fabianvf in your POC/tests.

**Closed by camilamacedo86** 2020-01-07 09:28 UTC
Labels: ansible-operator, triage/support
