### ISSUE TITLE
When reconcilePeriod is set, Ansible operator should only run playbook for CRs that have changed

### ISSUE THREAD

**Issue by rammohanc** [operator-framework/operator-sdk#1978] opened 2019-09-26 19:15 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**
When reconcilePeriod is set, Ansible operator runs the playbook for all the CRs regardless of whether the CR has changed or not. When there are hundreds of CRs it is making Ansible operator unresponsive even with 5 cores and multiple workers as it is busy doing the reconcile for the CRs. During the reconcile period if a new CR is created, the initial playbook run for this new CR was taking long time (in some cases more than an hour) as Ansible operator is busy reconciling existing CRs.

**Describe the solution you'd like**
Ansible operator should only run reconcile for CRs that have changed when reconcilePeriod is set.

**Comment by camilamacedo86** [comment] 2019-09-26 21:06
Hi @rammohanc, 

Thank you for raise the RFE. Could you please let us know how much is the value set for reconcilePeriod in your case? Have you tried to increase it?

**Comment by camilamacedo86** [comment] 2019-09-26 21:06
c/c @fabianvf @shawn-hurley

**Comment by rammohanc** [comment] 2019-09-27 14:27
Hi Camila,

reconcilePeriod was set to 30 minutes - i understand this is aggressive but even if we increase it to 12 hours, we will still be running into issue when we try to create new CRs around the time reconcile is happening. Please let me know if you need additional information.

Thanks

> Hi @rammohanc,
> 
> Thank you for raise the RFE. Could you please let us know how much is the value set for reconcilePeriod in your case? Have you tried to increase it?

**Comment by camilamacedo86** [comment] 2019-09-27 15:12
HI @rammohanc, 

Your request is a flag to be discussed and it will be made. However, IMHO you are facing a performance issue and may the solution can be solved instead of the RFE. In this way, could you provide the following information? 

1. How much long takes when you apply 1 CR and it will be reconciled alone? Also, how long it takes when has just another 1 reconcile happened? 
2. How much CR's has been managed by your operator project? 
3. Are you able to provide a small POC to reproduce this scenario?

**Comment by fabianvf** [comment] 2019-09-27 15:47
If you only want to reconcile CRs when they change, you can set a `reconcilePeriod` of `0` and make sure `watchDependentResources` is set to `true`. This will make it so that reconcilation occurs if a CR is created or changed, or if any of the child resources of the CR change (so if e.g. a pod died it would trigger reconciliation), and would no longer run on a schedule.

**Comment by rammohanc** [comment] 2019-09-30 15:16
Hi @camilamacedo86,

Please see my response below:

Thanks


> HI @rammohanc,
> 
> Your request is a flaged to be discussed and it will be made. However, IMHO you are facing a performance issue and may the solution can be solved instead of the RFE. In this way, could you provide the following information?
> 

> 1. How much long takes when you apply 1 CR and it is reconciled alone? Also, how long it takes when has just another reconcile happening when you apply 1 new CR?
RM: it takes around 30 - 40 seconds. If there is only 1 CR and i am applying new CR it takes around same time - when both are running at the same time (as we have 5 workers and 5 cores for the operator pod)

> 2. How much CR's has been managed by your operator project?
RM: we have around 100 CRs managed by this operator

> 3. Are you able to provide a small POC to reproduce this scenario?
RM: will work on creating a POC ASAP

**Comment by rammohanc** [comment] 2019-09-30 15:22
Hi @fabianvf ,

That is exactly what we have done as a workaround for now. We would like to have the reconcile running periodically as a backup in case if we miss any events from the API server. 

Thanks

> If you only want to reconcile CRs when they change, you can set a `reconcilePeriod` of `0` and make sure `watchDependentResources` is set to `true`. This will make it so that reconcilation occurs if a CR is created or changed, or if any of the child resources of the CR change (so if e.g. a pod died it would trigger reconciliation), and would no longer run on a schedule.

**Comment by fabianvf** [comment] 2019-10-01 17:00
Unfortunately I don't think there is a guaranteed way to tell if a resource has been changed or not, we get the event stream but because the resource is already changed in etcd all we know is that it needs to be reconciled, but we don't/can't track exactly why. When we refresh based on reconcile period, we have no way of knowing if a resource needs to be reconciled or not, because all we have is the current state of the resource in the cluster.

In terms of the time it takes to reconcile, it might be worth increasing the number of workers (if you haven't already). If possible it may also help to add some tasks to your playbook/role that check the cluster state and determine whether you need to do the whole reconciliation process, with conditional imports or the `meta: end_play` task to shorten the loop.

**Comment by camilamacedo86** [comment] 2019-10-09 13:23
HI @fabianvf,

So,  I understand that the RFE raised here is not implementable. Has anything else that we should address with? 

Hi @rammohanc, 

Are you ok with the clarifications, explanations and recommendations provided so far? Has anything else about this specific subject that would like help with or could we close this one?

**Comment by accammer** [comment] 2019-11-26 13:09
HI @fabianvf, @camilamacedo86,
  I was surprised by the default behaviour that when reconciliation ran it runs the ansible again.  I would have thought that reconciliation would only run in the event of a change to the CR or its dependents.  I thought that was the default behaviour of operators.  If this is not the case the documentation should be changed to describe this behaviour.  Nowhere example does it in the example Memcache does it explain this behaviour.

Thanks

**Comment by camilamacedo86** [comment] 2019-11-26 13:53
HI @accammer, 

The watch feature is able to identify that something changed and will trigger the reconcile in all types of operators. Also, it is the expected behaviour and in POV it is properly documented in k8s docs as SDK and in many blogs and articles. See for example [the kubebuilder doc](https://book-v1.book.kubebuilder.io/beyond_basics/controller_watches.html)

Regards the ansible operator done with SDK you can find an explanation over the `reconcilePeriod` and `watchDependentResources` options in its documents as the watch feature. Following a few links as reference:

- https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/advanced_options.md#watches-file-options
- https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/developer_guide.md

So, I am not sure if I followed what actually would be missing. If you still thinking that something is missing to be addressed with this issue, could you please let us know what exactly? I mean could you please point out for example what info is missing and in what doc/place you think that it should be added? If not, please let us know if you are ok in close this one.

**Comment by joelanford** [comment] 2019-11-26 14:23
@accammer The reason you might be seeing what appear to be duplicate reconciliations is that the first run of the playbook is probably making a change to the CR and/or one or more of its dependents. All of these updates cause update events to be sent to the operator's informer, and any of them that are not filtered by a watch predicate will cause a reconciliation.

We recently improved the ansible-operator by introducing a dependent watch predicate in #2024 that skips some unnecessary reconciliations.

Also, I think we've answered the original question posed in this issue, so I'm going to close it. @accammer If you'd like to continue discussion about your question, please open a new issue!

**Closed by joelanford** 2019-11-26 14:23 UTC
Labels: ansible-operator, kind/feature, needs discussion

**Comment by accammer** [comment] 2019-11-26 15:26
Is there any documentation that explains the #2024 predicates or are they internal?

**Comment by genialmaniac** [comment] 2020-06-26 14:10
Hello, could you please update the links or put some content to redirect you on the links?
example  https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/advanced_options.md#watches-file-options is broken, thank you

**Comment by tengqm** [comment] 2020-06-27 06:45
@genialmaniac I believe the published doc is here: https://sdk.operatorframework.io/docs/ansible/reference/watches/

**Comment by tobernguyen** [comment] 2021-02-02 00:09
Update the broken link above: https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/
