### ISSUE TITLE
make dep fails silently windows - used make VERBOSE=1 to get more details

### ISSUE THREAD

**Issue by mjschmidt** [operator-framework/operator-sdk#876] opened 2018-12-23 02:43 UTC
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
General Context

## Question

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

I am attempting to get the operator-sdk running and installed on my windows 10 machine. I got all of the dependencies running, I am running my Atom IDE as admin, and I am unable to do a make dep. I ran make VERBOSE=1 to attempt to get more information and I got the following

```
PS C:\Users\Mike\Documents\GitHub\Atom\src\github.com\operator-framework\operator-sdk> make VERBOSE=1
./hack/ci/marker --root=doc
process_begin: CreateProcess(C:\Users\Mike\Documents\GitHub\Atom\src\github.com\operator-framework\operator-sdk\hack\ci\marker, ./hack/ci/marker --root=doc, ...) failed.
make (e=193): Error 193
make: *** [Makefile:100: test/markdown] Error 193
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

I expected the deps to work so that I could run make install and then run the operator-sdk command and have it generate me some awesome go code that I could use to create an operator!

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

```
PS C:\Users\Mike\Documents\GitHub\Atom\src\github.com\operator-framework\operator-sdk> make VERBOSE=1
./hack/ci/marker --root=doc
process_begin: CreateProcess(C:\Users\Mike\Documents\GitHub\Atom\src\github.com\operator-framework\operator-sdk\hack\ci\marker, ./hack/ci/marker --root=doc, ...) failed.
make (e=193): Error 193
make: *** [Makefile:100: test/markdown] Error 193
```
Most of the make command did in fact work
```
PS C:\Users\Mike\Documents\GitHub\Atom\src\github.com\operator-framework\operator-sdk> make VERBOSE=1commands\operator-sdk\cmd\completion.go
commands\operator-sdk\cmd\add.go

commands\operator-sdk\cmd\build_test.go
commands\operator-sdk\cmd\generate.go
commands\operator-sdk\main.go
commands\operator-sdk\cmd\print_deps.go
commands\operator-sdk\cmd\build.go
commands\operator-sdk\cmd\new.go
commands\operator-sdk\cmd\root.go
commands\operator-sdk\cmd\test.go
commands\operator-sdk\cmd\up.go
commands\operator-sdk\cmd\add\api.go
commands\operator-sdk\cmd\add\controller.go
commands\operator-sdk\cmd\completion\zsh.go
commands\operator-sdk\cmd\add\crd.go
commands\operator-sdk\cmd\completion\bash.go
commands\operator-sdk\cmd\test\cluster.go
commands\operator-sdk\cmd\generate\k8s.go
commands\operator-sdk\cmd\test\local.go
commands\operator-sdk\cmd\up\local.go
internal\util\diffutil\diff_util.go
internal\util\projutil\project_util.go
internal\util\fileutil\file_util.go
internal\util\k8sutil\k8sutil.go
internal\util\yamlutil\manifest.go
... yada yada no errors here ...
# Gopkg.lock is out of sync with Gopkg.toml and project imports:
github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/add: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/completion: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/generate: in Gopkg.lock's input-imports, but neither imported nor required

github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/test: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/internal/util/diffutil: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/internal/util/fileutil: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/internal/util/k8sutil: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/internal/util/projutil: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/internal/util/yamlutil: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/controller: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/controller/status: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/events: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/flags: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/operator: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/paramconv: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/proxy: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/proxy/kubeconfig: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/proxy/requestfactory: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/runner: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/runner/eventapi: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/runner/fake: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/ansible/runner/internal/inputdir: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/helm/client: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/helm/controller: in Gopkg.lock's input-imports, but neither imported nor required
github.com/operator-framework/operator-sdk/pkg/helm/engine: in Gopkg.lock's input-imports, but neither imported nor required
... yada yada .. still no errors
Root project is "github.com/operator-framework/operator-sdk"
 52 transitively valid internal packages
 76 external packages imported from 23 projects
(0)   ✓ select (root)
(1)     ? attempt github.com/BurntSushi/toml with 1 pkgs; at least 1 versions to try
(1)         try github.com/BurntSushi/toml@v0.3.1
(1)     ✓ select github.com/BurntSushi/toml@v0.3.1 w/1 pkgs
(2)     ? attempt github.com/coreos/prometheus-operator with 2 pkgs; at least 1 versions to try
(2)         try github.com/coreos/prometheus-operator@v0.26.0
(2)     ✓ select github.com/coreos/prometheus-operator@v0.26.0 w/4 pkgs
(3)     ? attempt github.com/markbates/inflect with 1 pkgs; at least 1 versions to try
(3)         try github.com/markbates/inflect@v1.0.1
(3)     ✓ select github.com/markbates/inflect@v1.0.1 w/1 pkgs
(4)     ? attempt github.com/ghodss/yaml with 1 pkgs; at least 1 versions to try
(4)         try github.com/ghodss/yaml@v1.0.0
(4)     ✓ select github.com/ghodss/yaml@v1.0.0 w/1 pkgs
(5)     ? attempt github.com/martinlindhe/base36 with 1 pkgs; at least 1 versions to try
(5)         try github.com/martinlindhe/base36@master
(5)     ✓ select github.com/martinlindhe/base36@master w/1 pkgs
(6)     ? attempt github.com/gobuffalo/envy with 1 pkgs; at least 1 versions to try
(6)         try github.com/gobuffalo/envy@v1.6.5
(6)     ✓ select github.com/gobuffalo/envy@v1.6.5 w/1 pkgs
(7)     ? attempt github.com/go-openapi/spec with 1 pkgs; at least 1 versions to try
... yada yada until error ...
(136) ✓ select go.uber.org/multierr@v1.1.0 w/1 pkgs

  ✓ found solution with 607 packages from 104 projects

Solver wall times by segment:
         b-list-pkgs: 3m38.9995582s
              b-gmal:  3m29.748361s
     b-source-exists:   11.6812966s
  b-deduce-proj-root:    5.1795169s
    b-rev-present-in:    611.7484ms
         select-atom:     263.188ms
             satisfy:    260.4168ms
         select-root:      2.9945ms
            new-atom:       991.3µs
            add-atom:       974.2µs
               other:       958.8µs

  TOTAL: 7m26.7500047s

# Bringing vendor into sync
(1/1) Removed unused project github.com/operator-framework/operator-sdk
./hack/ci/marker --root=doc
process_begin: CreateProcess(C:\Users\Mike\Documents\GitHub\Atom\src\github.com\operator-framework\operator-sdk\hack\ci\marker, ./hack/ci/marker --root=doc, ...) failed.
make (e=193): Error 193
```

**Environment**
* operator-sdk version:
From the version file it looks like a new release, so seeing that now maybe this is a bug...

var (
	Version = "v0.3.0+git"
)

  insert release or Git SHA here

* Kubernetes version information:

Doesn't matter yet, but will be 1.12.something

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

Will be minikube to start then regular cluster

**Additional context**
Add any other context about the question here.

Open to questions, can try to retrieve any info you are looking for.

**Comment by mjschmidt** [comment] 2018-12-23 02:55
Hmmmmmmm it actually also happened on my linux (centos7) virtual machine.
This may actually be a bug with the new release?

make VERBOSE=1
./hack/ci/marker --root=doc
./hack/ci/marker: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./hack/ci/marker)
make: *** [test/markdown] Error 1

**Comment by mjschmidt** [comment] 2018-12-26 14:39
I was installing with the directions from master, that is where I ran into the issues with both linux and windows, the issue is one of the dependencies (./hack/ci/marker: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./hack/ci/marker)) is not working, meaning that the operatorsdk cannot be built from the master branch.

**Comment by mjschmidt** [comment] 2018-12-27 12:46
This is correct. I did that because the make dep, and make install, failed silently.

**Comment by mjschmidt** [comment] 2018-12-27 12:46
I was just trying to get more information

**Comment by mjschmidt** [comment] 2019-01-01 22:34
Is someone able to build OperatorSDK from source without having deps already installed?

**Comment by mjschmidt** [comment] 2019-01-01 22:39
No logs are printed on make dep

**Comment by mjschmidt** [comment] 2019-01-01 22:40
no logs are printed on make install

**Comment by joelanford** [comment] 2019-01-02 15:11
@mjschmidt `dep` (0.5.0+) is required (and must be on your `PATH`) to build `operator-sdk` since that's what we use to manage and vendor dependencies. After you run `make dep` you should see a `./vendor` directory in the root of the `operator-sdk` project.

If you're able to get that far, the next step is `make install`. When I run that command on Linux, logs are only printed if something goes wrong, so no logs there should mean things are working.

If that's successful, you should see a new binary executable at `$GOPATH/bin/operator-sdk` on Linux (or `%GOPATH%\bin\operator-sdk.exe` on Windows). And if you don't have GOPATH set, it would be `~/go/bin/operator-sdk` on Linux and `%USERPROFILE%\go\operator-sdk.exe` on Windows.

Does that help?

**Comment by mjschmidt** [comment] 2019-01-02 21:52
Thanks @joelanford let me take a look to see if that folder is creating or not.

**Comment by mjschmidt** [comment] 2019-01-04 12:05
We can close the ticket. This works on my linux machine but not my windows machine. Why anyone uses windows... idk. Thanks @joelanford and @LiliC

**Comment by joelanford** [comment] 2019-01-04 17:00
@mjschmidt That's an issue I see from time to time with dep. Are you able to reliably reproduce the same error on consecutive runs of `make dep`? Are you able to resolve it by deleting the `./vendor` directory before running `make dep`?

**Comment by mjschmidt** [comment] 2019-01-04 17:01
let me take a look at the ./vendor and try deleting that

**Comment by mjschmidt** [comment] 2019-01-04 17:02
no .vendor folder. would that be in the operator-sdk folder?

**Comment by joelanford** [comment] 2019-01-04 17:08
It should be `/path/to/operator-sdk/vendor`, not `/path/to/operator-sdk/.vendor`. Sorry if that was unclear!

**Comment by mjschmidt** [comment] 2019-01-04 17:10
So just by running the command again it appeared to get further. No vendor folder in the operator-sdk project

(82/104) Wrote k8s.io/client-go@kubernetes-1.12.3
(83/104) Wrote go.uber.org/atomic@v1.3.2
(84/104) Wrote k8s.io/cli-runtime@kubernetes-1.12.3
(85/104) Wrote k8s.io/apimachinery@kubernetes-1.12.3
(86/104) Wrote k8s.io/apiserver@kubernetes-1.12.3
(87/104) Failed to write golang.org/x/oauth2@master
(88/104) Failed to write k8s.io/apiextensions-apiserver@kubernetes-1.12.3
(89/104) Failed to write github.com/coreos/prometheus-operator@v0.26.0
(90/104) Failed to write k8s.io/kubernetes@v1.12.3
(91/104) Failed to write github.com/sergi/go-diff@v1.0.0
(92/104) Failed to write github.com/hashicorp/golang-lru@v0.5.0
(93/104) Failed to write k8s.io/helm@v2.12.0
(94/104) Failed to write github.com/spf13/pflag@v1.0.3
(95/104) Failed to write github.com/gregjones/httpcache@master
(96/104) Failed to write sigs.k8s.io/controller-runtime@v0.1.8
(97/104) Failed to write github.com/imdario/mergo@v0.3.6
(98/104) Failed to write k8s.io/utils@master
(99/104) Failed to write k8s.io/kube-openapi@0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803
(100/104) Failed to write cloud.google.com/go@v0.33.1
(101/104) Failed to write github.com/huandu/xstrings@v1.2.0
(102/104) Failed to write github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0
(103/104) Failed to write github.com/docker/docker@a9fbbdc8dd8794b20af358382ab780559bca589d
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export golang.org/x/oauth2: fatal: failed to unpack tree object 8f65e3013ebad444f13bc19536f7865efc793816
: exit status 128
make: *** [dep] Error 1

**Comment by joelanford** [comment] 2019-01-04 17:47
Glad you got it working.

> failed to export golang.org/x/oauth2: fatal: failed to unpack tree object 8f65e3013ebad444f13bc19536f7865efc793816

This error message makes me think dep and/or git had an issue cloning and checking out that commit, and got itself into a weird state.

I'll go ahead and close the issue, but if you see this again, definitely re-open so we can investigate further. Also, there are [a few open issues in the dep repo](https://github.com/golang/dep/search?q=fatal%3A+failed+to+unpack+tree+object&state=open&type=Issues) that appear to be related, so it might be worth a look through those to see if there are fixes or workarounds.

**Closed by joelanford** 2019-01-04 17:47 UTC

**Comment by mjschmidt** [comment] 2019-01-05 12:31
@joelanford your advice also solved the windows issues I was having for anyone who visits this issue later
