### ISSUE TITLE
r.Recorder is nil. Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vladsf** [operator-framework/operator-sdk#6697] opened 2024-03-05 20:05 UTC
## Bug Report

Hi, I followed the latest Go lang guide to create the sample memcached operator.  
[memcached_controller.go](https://github.com/operator-framework/operator-sdk/blob/4abd483aa4004af83b3c05ddf9d7a7e4d4653cc7/testdata/go/v4/memcached-operator/internal/controller/memcached_controller.go)

but it fails when I try to delete the applied sample yaml. 
 
.. Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference
...
internal/controller.(*MemcachedReconciler).doFinalizerOperationsForMemcached(0xc0000163f0, 0xc000462500)

somehow r.Recorder is nil. So [line 299 fails  ](https://github.com/operator-framework/operator-sdk/blob/4abd483aa4004af83b3c05ddf9d7a7e4d4653cc7/testdata/go/v4/memcached-operator/internal/controller/memcached_controller.go#L299)

Is there way to fix this?

**Comment by harshvijaythakkar** [comment] 2024-03-12 07:25
I think it is duplicate of #6681

**Comment by acornett21** [comment] 2024-05-07 21:43
Closing as duplicate

**Closed by acornett21** 2024-05-07 21:43 UTC
Labels: triage/duplicate
