### ISSUE TITLE
Reducing scope of Ansible operator from cluster to namespace

### ISSUE THREAD

**Issue by santoshborse** [operator-framework/operator-sdk#4314] opened 2020-12-14 21:05 UTC
## Type of question

General operator-related help

## Question
I migrated my Ansible based operator from version v0.18 to v1.2.

The default skeleton generated by v1.2 operator sdk is cluster scoped operator. When I try to change the scope to namespaced ( by change in CRD and RBAC ) the operator log throws error

```
E1214 20:47:25.428680       7 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125: Failed to list test.com/v1alpha1, Kind=WatsonSpeech: watsonspeeches.test.com is forbidden: User "system:serviceaccount:zen:default" cannot list resource "watsonspeeches" in API group "test.com" at the cluster scope

```
#### What did you expect to see?

The operator should run with Namespace scope

#### What did you see instead? Under which circumstances?

throwing error

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

"OpenShift"

`$ operator-sdk version`

operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.4", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.15.5 darwin/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a02f27a", GitTreeState:"clean", BuildDate:"2020-04-13T12:04:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by camilamacedo86** [comment] 2021-01-04 19:46
Hi @santoshborse, 

Before 1.0+ version the operators built with the SDK tool were namespaced scope. As you could check, after 1.0+ the projects starts to be cluster scoped instead.

Currently, unfortunately, we have not documented the steps required to change the scope specifically for Ansible or Helm. However, the steps are quite similar/same of the same ones done for Golang operators and described in https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#watching-resources-in-a-set-of-namespaces.  Indeed this need is tracked in https://github.com/operator-framework/operator-sdk/issues/3447 and would be great get your help to address it as well.  

For changing the operator’s scope you will need to: 
- update the `role.yaml` and `role_binding.yaml` manifests 
- replace ClusterRoleBinding with RoleBinding and ClusterRole with Role in the config/rbac/role_binding.yaml 
- then, you will need also to add the `WATCH_NAMESPACE` environment variable to the manager in `config/manager/manager.yaml`, for example, see [here](https://github.com/operator-framework/operator-sdk/blob/master/testdata/ansible/memcached-operator/config/manager/manager.yaml#L31) which for the default setup will be your `<operatorName>-system`. The operatorName is the name of the directory of your project. Note that that the for the new layout its specific namespace will be created for you. You can check its name in [config/default/kustomization.yaml](https://github.com/operator-framework/operator-sdk/blob/master/testdata/ansible/memcached-operator/config/default/kustomization.yaml#L2)
- See that if you do not want to use the default ns then more customizations will be required to be in place.  

So, first could you please let us know if you are able to do this configuration with the default ns? If not, what is the issue faced? Also, we would need to know exactly the changes made by you in order to try to help you find out what is missing or is wrong.

**Comment by camilamacedo86** [comment] 2021-01-14 11:51
Hi @santoshborse, 

Since it has been open whiteout interactions shows that the above info was enough for you to solve the problem. So, I am closing this one. However, if you still needing help with could you please raise a new issue and provide all steps done for we are able to reproduce and help you from there.

**Closed by camilamacedo86** 2021-01-14 11:51 UTC
Labels: language/ansible, triage/needs-information
