### ISSUE TITLE
How to retrieve ClusterRole in operator pod installed via OLM

### ISSUE THREAD

**Issue by aharbis** [operator-framework/operator-sdk#2925] opened 2020-04-28 14:04 UTC
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

This is admittedly a cross-over between OLM and Operator SDK, but wanted to start here in the Operator SDK repo, as this primarily involves the Operator runtime itself.

## Question

**What did you do?**

For some brief background, we create two admission webhooks (validate & default) during our operator's init. Because the `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration` objects are cluster-level resources, it made sense to us to set the ownerReference for these two webhook config objects to the `ClusterRole` that we link our operator's Service Account to.

In order to set the ClusterRole as the ownerRef for the two webhook configs, we must query the cluster for the ClusterRole object by name using `k8s/client-go` [ClusterRoleInterface](https://godoc.org/k8s.io/client-go/kubernetes/typed/rbac/v1#ClusterRoleInterface) `Get()` method.

Up until now, we've been deploying our operator via Helm3 or orchestrated `kubectl` or `oc` commands and essentially apply the YAML directly to the cluster. We've been able to template the object / resource names deterministically.

We have recently started working on OLM support, and in my testing yesterday via `operator-sdk run --olm`, I noticed that OLM instantiates all of the RBAC resources for us. However, the ClusterRole gets a unique name. As example, instead of `my-operator-cr` it is `my-operator-cr.v0.10.0-kjhd2`. This causes an issue in our init, as we cannot query the cluster for the ClusterRole by name, as we do not know the name of the generated ClusterRole.

From my inspection of the objects in the cluster, I cannot find any annotation, label, or env var that would hold the generated ClusterRole name in an accessible place for the operator runtime.

I've tried to look into a way to template out an env var for our operator's pod that would hold this generated ClusterRole name, but I cannot find a method to do so.

I know that OLM will support webhook config management in the future (https://github.com/operator-framework/operator-lifecycle-manager/pull/1436), but in the event that we still wish to manage our own configs within the operator pod, this issue still arises.

**What did you expect to see?**

A method to deterministically retrieve the created ClusterRole object in the operator runtime.

**What did you see instead? Under which circumstances?**

No method to retrieve the created ClusterRole object, as the name is unknown to the operator runtime.

**Environment**
* operator-sdk version:

```
$ operator-sdk version
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"
```

* Kubernetes version information:

```
$ oc version
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.3.0
Kubernetes Version: v1.16.2
```

* Kubernetes cluster kind: 

OCP 4.3

**Additional context**
Add any other context about the question here.

**Comment by aharbis** [comment] 2020-04-28 15:05
One potential workaround I've come up with is to fetch the list of `ClusterRoleBinding` from the cluster (possibly leveraging label selectors, it seems field selectors don't support the `subjects`), and from the found `ClusterRoleBinding` list find the one which matches our `ServiceAccount` (which we can deterministically know the name of).

From there, once we have the `ClusterRoleBinding` that links our `ServiceAccount` to a `ClusterRole`, we can fetch the `ClusterRole` by name.

**Comment by joelanford** [comment] 2020-04-28 16:55
@aharbis Are there any labels that OLM puts on the created cluster role that could be used to deterministically find it?

**Comment by aharbis** [comment] 2020-04-28 17:25
@joelanford On the OLM-generated `ClusterRole`, there are the following labels:

```yaml
  labels:
    olm.owner: my-operator.v0.10.0
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: my-operator-ns
```

I can link that `olm.owner.namespace` back to the namespace the operator is running in, but this still would require polling the objects to find it. This is currently the workaround I'm building as a POC.

It's also worth mentioning that we intend to support other installation methods for our operator (such as Helm3), not just OLM. Thus, ideally, we'd like to find a solution that hits both without too much switch/case logic.

In our Helm templating, we are able to inject the generated ClusterRole name into the PodSpec through an environment variable, making the name available to the operator runtime easily. Does any similar mechanism exist on the OLM side, or anything we could specify in our CSV generation to allow OLM to specify "this is the name of the ClusterRole I've generated for you" and drop that into an env var or something?

**Comment by joelanford** [comment] 2020-04-28 17:43
@aharbis It seems the root of the problem is that the cluster role name has that random suffix at the end. If it followed a deterministic pattern, you could add it as an environment variable to your CSV deployment yourself. Not sure if that would lead to other issues for OLM though.

So it seems like the current way to do this would be `client.List` the cluster roles using a label selector that is deterministic.

I hesitate to make any definitive suggestions without some input from the OLM maintainers.

**Comment by joelanford** [comment] 2020-05-19 21:29
@aharbis I don't think there's a whole lot the SDK itself can help with here. I'd suggest that you open an issue against the OLM repository to continue this discussion. I _think_ there are some features on the OLM roadmap that may help with this, and you'll get a faster response taking this issue up there.

Closing this one, but if there's something that comes out of the OLM issue that we could do in SDK to help integrate any new features or bug fixes OLM makes to support this use case, definitely open a new issue to continue the convo!

**Closed by joelanford** 2020-05-19 21:29 UTC
Labels: triage/support
