### ISSUE TITLE
How to configure the service account name with operator-sdk and OLM

### ISSUE THREAD

**Issue by houshengbo** [operator-framework/operator-sdk#4592] opened 2021-03-02 00:40 UTC
#### What did you do?
I followed the instruction to create the go-lang based operator:
https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/

#### What did you expect to see?
I want to generate the csv file.
I expect to see the option for me to change the serviceaccount from the default to any name I like. 

#### What did you see instead? Under which circumstances?
There is no option for me to change the service account name. I tried to manually change it in the yamls under config/rbac, but it did not work when I ran `make bundle` to generate the csv file.

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`
1.4.2

`$ go version` (if language is Go)
go1.15.5 darwin/amd64

`$ kubectl version`
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by estroz** [comment] 2021-03-08 19:06
Duplicate of #4468

**Closed by estroz** 2021-03-08 19:06 UTC
