### ISSUE TITLE
variable name contains number and underline in CR spec will be converted unexpectedly

### ISSUE THREAD

**Issue by wondersong** [operator-framework/operator-sdk#2604] opened 2020-02-27 03:26 UTC
## Bug Report
We know the rule camelCase in the spec becomes camelCase in ansible. https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md#define-the-memcached-spec
but we found such as db2_init in spec will be covered to  db_2__init in ansible unexpectedly.

**What did you expect to see?**
db2_init in spec will not be converted to db_2__init. still db2_init in ansible

**Comment by camilamacedo86** [comment] 2020-03-04 15:18
Hi @asmacdo and @fabianvf could you please give a hand in this one?

**Comment by asmacdo** [comment] 2020-03-04 18:31
Closing, I think this is a dupe of https://github.com/operator-framework/operator-sdk/issues/1770

If not, please reopen.

**Closed by asmacdo** 2020-03-04 18:31 UTC
Labels: ansible-operator, triage/support
