### ISSUE TITLE
can't install operator_sdk on win10: "cannot use syscall.NsecToFiletime" bug when doing "make install"

### ISSUE THREAD

**Issue by erjan** [operator-framework/operator-sdk#6585] opened 2023-09-28 17:13 UTC
#### What did you do?
first of all, i installed make tool, go lang on my win10 pc.

i followed the official instructions from https://sdk.operatorframework.io/docs/installation/ (Compile and install from master)
```
git clone https://github.com/operator-framework/operator-sdk
cd operator-sdk
git checkout master
make install
```
i created the folder , git cloned into and tried the last step.

the last step did not work  and gave me this error:
`go\pkg\mod\github.com\containerd\containerd@v1.4.11\archive\tar_windows.go:257:27: cannot use syscall.NsecToFiletime(createTime.UnixNano()) (value of type syscall.Filetime) as "golang.org/x/sys/windows".Filetime value in assignment`

#### What did you expect to see?

i expected to have operator-sdk installed and to follow some utube tutorial and create my own operator from scratch

#### What did you see instead? Under which circumstances?
i see this error:
```
make install
go install -gcflags "all=-trimpath=C:/Users/erjan/Downloads/operator_k8s_sdk" -asmflags "all=-trimpath=C:/Users/erjan/Downloads/operator_k8s_sdk" -ldflags " -X 'github.com/operator-framework/operator-sdk/internal/version.Version=v1.31.0+git' -X 'github.com/operator-framework/operator-sdk/internal/version.GitVersion=v1.31.0-3-gd21ed649' -X 'github.com/operator-framework/operator-sdk/internal/version.GitCommit=d21ed6499ebfc8ecdb4508e1c2a2a0cfd2a151f3' -X 'github.com/operator-framework/operator-sdk/internal/version.KubernetesVersion=v1.26.0' -X 'github.com/operator-framework/operator-sdk/internal/version.ImageVersion=v1.31.0' "  ./cmd/# github.com/containerd/containerd/archive
..\..\..\go\pkg\mod\github.com\containerd\containerd@v1.4.11\archive\tar_windows.go:234:19: cannot use syscall.NsecToFiletime(hdr.AccessTime.UnixNano()) (value of type syscall.Filetime) as "golang.org/x/sys/windows".Filetime value in struct literal
..\..\..\go\pkg\mod\github.com\containerd\containerd@v1.4.11\archive\tar_windows.go:235:19: cannot use syscall.NsecToFiletime(hdr.ModTime.UnixNano()) (value of type syscall.Filetime) as "golang.org/x/sys/windows".Filetime value in struct literal
..\..\..\go\pkg\mod\github.com\containerd\containerd@v1.4.11\archive\tar_windows.go:236:19: cannot use syscall.NsecToFiletime(hdr.ChangeTime.UnixNano()) (value of type syscall.Filetime) as "golang.org/x/sys/windows".Filetime value in struct literal
..\..\..\go\pkg\mod\github.com\containerd\containerd@v1.4.11\archive\tar_windows.go:239:17: cannot use syscall.NsecToFiletime(hdr.ModTime.UnixNano()) (value of type syscall.Filetime) as "golang.org/x/sys/windows".Filetime value in struct literal
..\..\..\go\pkg\mod\github.com\containerd\containerd@v1.4.11\archive\tar_windows.go:257:27: cannot use syscall.NsecToFiletime(createTime.UnixNano()) (value of type syscall.Filetime) as "golang.org/x/sys/windows".Filetime value in assignment
make: *** [Makefile:75: install] Error 1
```

#### Environment
`git bash,win10, 64bit,amd64`

**Kubernetes cluster type:** minikube

`$ go version` (if language is Go)
`go version go1.21.1 windows/amd64`

**Comment by varshaprasad96** [comment] 2023-10-02 17:20
@erjan we have a similar issue open: https://github.com/operator-framework/operator-sdk/issues/6586

We do not officially support or build binaries for windows. But we are open to receiving any help with contributions. I'll close this as a duplicate of #6586. But feel free to re-open if you feel otherwise. Thank you!

**Closed by varshaprasad96** 2023-10-02 17:20 UTC
