### ISSUE TITLE
Use Duration over int for resyncPeriod

### ISSUE THREAD

**Issue by olvesh** [operator-framework/operator-sdk#420] opened 2018-08-20 07:44 UTC
https://github.com/operator-framework/operator-sdk/blob/9314564aede3cf664a49fe670d6f3efdc84dd7e7/pkg/sdk/api.go#L43 and
https://github.com/operator-framework/operator-sdk/blob/9314564aede3cf664a49fe670d6f3efdc84dd7e7/pkg/sdk/informer.go#L48

should use time.Duration for resyncPeriod rather than an int that gets multiplied by `time.Second` in `NewInformer` method: 
https://github.com/operator-framework/operator-sdk/blob/9314564aede3cf664a49fe670d6f3efdc84dd7e7/pkg/sdk/informer.go#L57

**Comment by olvesh** [comment] 2018-08-20 07:52
Say I want to do an operator syncing every hour, my instinct is to write:
```go
resync := 60 * time.Minute
```
This little oversight will in this case cause the following differences:
```
=== RUN   Test
1 hours 0 minutes 0 seconds
33390 days 2 hours 40 minutes 26 seconds
--- PASS: Test (0.00s)
PASS
```

**Comment by hasbro17** [comment] 2018-08-20 20:54
@olvesh Closing this as it's a duplicate of #345

**Closed** 2018-08-20 20:54 UTC
