### ISSUE TITLE
Helm operator failed to uninstall release

### ISSUE THREAD

**Issue by liqlin2015** [operator-framework/operator-sdk#2657] opened 2020-03-16 03:02 UTC
## Bug Report

Helm operator failed to uninstall release.

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
Saw this error when I tried to remove my release with helm operator
```
{“level”:“error”,“ts”:1583813458.0704582,“logger”:“helm.controller”,“msg”:“Failed to uninstall release”,“namespace”:“ibm-common-services”,“name”:“example”,“apiVersion”:“operator.ibm.com/v1alpha1”,“kind”:“Nginx”,“release”:“example”,“error”:“failed to get release history: release: \“example\” not found”,“stacktrace”:“github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/helm/controller.HelmOperatorReconciler.Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/pkg/helm/controller/reconcile.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
```

Not sure why helm release was not found. But from the helm operator if helm release cannot be found it should return error `driver.ErrReleaseNotFound`. Just checked this code snippet in `release/manager.go`
```
// UninstallRelease performs a Helm release uninstall.
func (m manager) UninstallRelease(ctx context.Context) (*rpb.Release, error) {
	// Get history of this release
	h, err := m.storageBackend.History(m.releaseName)
	if err != nil {
		return nil, fmt.Errorf("failed to get release history: %w", err)
	}

	// If there is no history, the release has already been uninstalled,
	// so return ErrReleaseNotFound.
	if len(h) == 0 {
		return nil, driver.ErrReleaseNotFound
	}
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

Helm operator can successfully uninstall release even helm release was not there. CR can be successfully removed.

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

CR cannot be removed because of helm finalizer was insisting to remove the release even it was not found.

**Environment**
* operator-sdk version: 0.15.2

* go version: 1.13.8

* Kubernetes version information: v1.16.2, 

* Kubernetes cluster kind: OCP 4.3

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**
Refer to above code snippet, should handle release not found case too.

**Additional context**

**Comment by camilamacedo86** [comment] 2020-03-16 10:30
Hi @liqlin2015, 

Could you please provide the steps for we reproduce it? E.g 

1. Run `operator-sdk new memcached-operator --api-version=cache.example.com/v1alpha1 --kind=Memcached --type=helm --helm-chart=stable/memcached` to install the helm chart X
2. Update the value of Z with Y.
...

**Comment by liqlin2015** [comment] 2020-03-19 03:40
@camilamacedo86 Sorry, it cannot be reproduced all the time. Do you think it's a bug from above code? Should it add check for notFound case?

**Comment by joelanford** [comment] 2020-03-19 04:26
Don't know for sure, but this may be able to be reproduced by:
1. Installing a release with the operator by creating a CR
2. Manually deleting the release using the Helm CLI
3. Deleting the CR

In the past, I've seen that when there is no history for a release, `m.storageBackend.History` returns a nil error and zero length history or returns an error, depending on the underlying storage driver.

This seems like it could be related to that. Let me research a little and see if I can reproduce. But this should be something we can fix regardless because we can do a little more introspection of the error if necessary.

**Comment by joelanford** [comment] 2020-03-31 16:36
@liqlin2015 I'm unable to reproduce. I'm looking at your error message and comparing to the Helm 3 `History()` function for secrets, and can't make sense of it. Can you confirm that your operator's base image is `v0.15.2`?

In Helm 2-based operators (pre-`v0.14.0`), that error comes from [here](https://github.com/helm/helm/blob/e0604b930643f1af768b78af454d89eb23f52cec/pkg/storage/errors/errors.go#L22:2), and that looks like your error message.

In Helm 3, [`driver.ErrReleaseNotFound`](https://github.com/helm/helm/blob/9b42702a4bced339ff424a78ad68dd6be6e1a80a/pkg/storage/driver/driver.go#L27) is now just a static error value that does not contain the name of the release.

And in the Helm operator, we use [error wrapping](https://github.com/operator-framework/operator-sdk/blob/ffaf278993c8fcb00c6f527c9f20091eb8dd3352/pkg/helm/release/manager.go#L298) and [check for the `ErrReleaseNotFound` case if the Uninstall fails](https://github.com/operator-framework/operator-sdk/blob/ffaf278993c8fcb00c6f527c9f20091eb8dd3352/pkg/helm/controller/reconcile.go#L132).

Based on this, I'm going to close this and suggest that you ensure you upgrade your base image to at least `v0.14.1`.

Feel free to open a new issue if you continue to run into this problem with the new Helm 3-based operator base image.

**Closed by joelanford** 2020-03-31 16:36 UTC
Labels: helm-operator, triage/needs-information

**Comment by liqlin2015** [comment] 2020-05-22 06:49
Thanks @joelanford for the analyze. I was using helm operator 0.13.0 when the problem happened. Then I moved to helm operator 0.15.2. Did not realize there is version change.
