### ISSUE TITLE
The resourceVersion for the provided watch is too old.

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-sdk#596] opened 2018-10-11 09:54 UTC
I see this a few mins after an operator is done with creating objects:

```
ERROR: logging before flag.Parse: W1011 09:44:47.138073       1 reflector.go:341] github.com/code-ready-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.go:91: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.

ERROR: logging before flag.Parse: W1011 09:44:47.138073       1 reflector.go:341] github.com/code-ready-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.go:91: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
--
  | ERROR: logging before flag.Parse: W1011 09:59:56.232902       1 reflector.go:341] github.com/code-ready-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.go:91: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
  | ERROR: logging before flag.Parse: W1011 10:14:18.293003       1 reflector.go:341] github.com/code-ready-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.go:91: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.
  | ERROR: logging before flag.Parse: W1011 10:21:23.341743       1 reflector.go:341] github.com/code-ready-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.go:91: watch of *unstructured.Unstructured ended with: The resourceVersion for the provided watch is too old.

```

It occurs every 5-15 mins, and does not seem to impact anything. Just wonder what may cause it. The operator creates OpenShift and K8S objects and it pretty straightforward

**Comment by shawn-hurley** [comment] 2018-10-11 12:41
Closing issue as it is a duplicate of #344

**Closed by shawn-hurley** 2018-10-11 12:41 UTC
