### ISSUE TITLE
e2e test for cluster-scoped operator

### ISSUE THREAD

**Issue by mkimuram** [operator-framework/operator-sdk#2980] opened 2020-05-06 15:49 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, [e2e test](https://sdk.operatorframework.io/docs/golang/e2e-tests/#running-the-tests) for [cluster-scoped operator](https://sdk.operatorframework.io/docs/operator-scope/#cluster-scoped-operator-usage) doesn't work well, unless operator's namespace is specified by using --operator-namespace option (or --namespace option in old version).
I guess that it is because clusterrolebinding in deploy/role_binding.yaml sepcifies sa's namespace, but it is not modified to e2e test's namespace in [`createFromYAML`](https://github.com/operator-framework/operator-sdk/blob/f3240e9a326be1862c606b68b12c84fe75462157/pkg/test/resource_creator.go#L115) (only metadata.Namespace is modified), as a result, operator's sa won't have expected clusterrole.

**Describe the solution you'd like**
It would be nice if 
 - it is documented that e2e test for cluster-scoped operator requires additional option, in short term,
 - `createFromYAML` is improved to modify clusterrolebinding's sa's namespace for cluster-scoped operator.

Note that to make the improvement work well in parallel, we will also need to modify clusterrolebinding's name to avoid conflict, for clusterrolebinding is not namespaced resource and should be different in each test(Clusterrole isn't namespaced either, but it will be the same across tests, so it won't need to be modified.)

**Comment by camilamacedo86** [comment] 2020-05-07 10:42
HI @mkimuram, 

I agree with the idea of improve the docs and please feel free to collab with by doing a PR if you wish. However, I do not think that tool should deliberate change the roles. 

The -flag allows users to run the tests in other namespaces, however, it is up to them ensure that project roles and etc are done for the namespace that they wish to use. Otherwise, for example, how the users can use the tool to test the project and to ensure that all is set up properly?

**Comment by mkimuram** [comment] 2020-05-07 20:26
@camilamacedo86 

Thank you for your comment.

> however, it is up to them ensure that project role and etc are done for the namespace that they wish to use.

Let me explain this issue more in detail.

To make operator cluster-scope, changes like [this](https://github.com/mkimuram/operator-sdk-samples/commit/e555bb0bf0c810b232b5b18490b2a744c88d3a4c) is required, as the document explains. So, for this particular case, users actually don't care what namespace it is, but it should be some specific one in order to assign clusterrole to sa.

On the other hand, after these changes are applied, e2e test starts to fail. The error in operator deployment is as follows:

<details>

```
$ operator-sdk test local ./test/e2e/
INFO[0000] Testing operator locally.  
--- FAIL: TestMemcached (60.26s)
<snip>
            memcached_test.go:100: Initialized cluster resources
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            memcached_test.go:110: timed out waiting for the condition
            client.go:83: resource type Deployment with namespace/name (osdk-e2e-097cce65-cd12-48a9-9f57-b0636f1
015f6/memcached-operator) successfully deleted
            client.go:83: resource type ClusterRoleBinding with namespace/name (osdk-e2e-097cce65-cd12-48a9-9f57
-b0636f1015f6/memcached-operator) successfully deleted
            client.go:83: resource type ClusterRole with namespace/name (osdk-e2e-097cce65-cd12-48a9-9f57-b0636f1015f6/memcached-operator) successfully deleted
            client.go:83: resource type ServiceAccount with namespace/name (osdk-e2e-097cce65-cd12-48a9-9f57-b0636f1015f6/memcached-operator) successfully deleted
FAIL
FAIL    github.com/operator-framework/operator-sdk-samples/go/memcached-operator/test/e2e       60.497s
FAIL
<snip>
```

- Log for operator pod while test is running. (Note that this is a log for another test run, so the namespace is different.)

```
$ kubectl logs memcached-operator-59cc6b96-tf6zh -n osdk-e2e-4997d307-91c2-4d50-92de-523b756bc531
{"level":"info","ts":1588873350.821526,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1588873350.8216126,"logger":"cmd","msg":"Go Version: go1.13.5"}
{"level":"info","ts":1588873350.8216436,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1588873350.8216717,"logger":"cmd","msg":"Version of operator-sdk: v0.17.0"}
{"level":"info","ts":1588873350.8223052,"logger":"leader","msg":"Trying to become the leader."}
{"level":"error","ts":1588873351.132623,"logger":"k8sutil","msg":"Failed to get Pod","Pod.Namespace":"osdk-e2e-4997d307-91c2-4d50-92de-523b756bc531","Pod.Name":"memcached-operator-59cc6b96-tf6zh","error":"pods \"memcached-operator-59cc6b96-tf6zh\" is forbidden: User \"system:serviceaccount:osdk-e2e-4997d307-91c2-4d50-92de-523b756bc531:memcached-operator\" cannot get resource \"pods\" in API group \"\" in the namespace \"osdk-e2e-4997d307-91c2-4d50-92de-523b756bc531\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/mkimura/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/k8sutil.GetPod\n\t/home/mkimura/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.17.0/pkg/k8sutil/k8sutil.go:129\ngithub.com/operator-framework/operator-sdk/pkg/leader.myOwnerRef\n\t/home/mkimura/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.17.0/pkg/leader/leader.go:160\ngithub.com/operator-framework/operator-sdk/pkg/leader.Become\n\t/home/mkimura/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.17.0/pkg/leader/leader.go:67\nmain.main\n\tmemcached-operator/cmd/manager/main.go:89\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","ts":1588873351.1329646,"logger":"cmd","msg":"","error":"pods \"memcached-operator-59cc6b96-tf6zh\" is forbidden: User \"system:serviceaccount:osdk-e2e-4997d307-91c2-4d50-92de-523b756bc531:memcached-operator\" cannot get resource \"pods\" in API group \"\" in the namespace \"osdk-e2e-4997d307-91c2-4d50-92de-523b756bc531\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/mkimura/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tmemcached-operator/cmd/manager/main.go:91\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

</details>


As seen in the error, deployment doesn't become ready, because sa for the operator doesn't have proper ClusterRole bound. It is caused because [namespace](https://github.com/mkimuram/operator-sdk-samples/blob/e555bb0bf0c810b232b5b18490b2a744c88d3a4c/go/memcached-operator/deploy/role_binding.yaml#L8) of the subject in deploy/role_binding.yaml points to original namespace, not e2e's namespace.

My idea is to fix it by [this way](https://github.com/mkimuram/operator-sdk/commit/a2dad63801268363b588ef53322b2fb7619d52fe). 

I've tested it by [replacing module](https://github.com/mkimuram/operator-sdk-samples/commit/209fc238139cacd6e0f5db415b2c7fb11f5e68be) and confirmed that it works well.
(I applied this change to v0.17.0, not for master branch, because operator-sdk-samples is created for this version, and it was difficult for me to resolve conflict for go module dependencies.)


> Otherwise, for example, how the users can use the tool to test the project and to check that all is set up properly?

I think that most users are happy with this behavior.
Actually, it will properly set the namespace that is specified by --operator-namespace. So, at least this case should be OK.

Does this improvement make sense or do I miss any corner cases that will potentially affect users?

**Comment by camilamacedo86** [comment] 2020-05-11 11:35
HI @mkimuram,

Thank you for your detailed reply. Following some considerations.

Note that, the `operator-scope` defines the [Manager](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Manager) cache scope but not the permissions to access the resources.

By looking at the errors added by you it shows that the issue is faced when the test-framework will create the [resources dynamically](https://github.com/operator-framework/operator-sdk/blob/master/pkg/test/context.go#L63) and [here](https://github.com/operator-framework/operator-sdk/blob/master/pkg/test/context_test.go#L24) to do the tests. See: 

> is forbidden: User **\"system:serviceaccount:osdk-e2e-4997d307-91c2-4d50-92de-523b756bc531:memcached-operator\"** cannot get resource \"pods\" in API group \"\" **in the namespace \"osdk-e2e-4997d307-91c2-4d50-92de-523b756bc531\**

So, all lead to me believe that we have:

- A config issue which could be addressed in the docs

OR 

- A bug may be faced when the resources are dynamically generated. 

So, IHMO before we provide the solution we need to:

- Isolate the scenario and define the steps required to reproduce it. For example, by using the [Go Memcached Sample](https://github.com/operator-framework/operator-sdk-samples/tree/master/go/memcached-operator) what are the required steps to reproduce it? Is possible to check the same behaviour whiteout change the operator-scope? Is possible to face the same issue if we provide an invalid operator namespace? If we just change the scope it will be faced? Could it not be a configuration issue because when a namespace is not informed it will be the default configured in the kubeconfig? 
- Then, we need to analyse the scenario and be sure that it is not related to any config issue that is not addressed appropriated in the docs, for example, and knows exactly why and when it occurs to provide the solution.  And then because of this, I am not sure if the [solution proposed](https://github.com/mkimuram/operator-sdk/commit/a2dad63801268363b588ef53322b2fb7619d52fe) in the most appropriate or not yet. However, let's check other inputs at all. WDYT? Is it make sense? Would you like to help with?

**Comment by mkimuram** [comment] 2020-05-11 18:05
Hi @camilamacedo86

> Isolate the scenario and define the steps required to reproduce it. For example, by using the Go Memcached Sample what are the required steps to reproduce it?

Actually, [the linked branch](https://github.com/mkimuram/operator-sdk-samples/commits/cluster-scope-e2e) is modified on top of the fork from master branch of `operator-framework/operator-sdk-samples`. So, as a code level, I think that I've narrowed down the cause in a way as you suggested, but I failed to explain it clearly.

So, let me explain it step-by-step, again.

There are three commits:
1. Workaround incompatibility between GetNamespace and GetOperatorNamespace
2. Make operator cluster-scope
3. Apply improvement createFromYAML to modify cluster scoped resources


And steps to reproduce are as described in the details below. 
(Step 3 will reproduce the issue and step 4 will workaround it.)
As you will see, changing the operator to cluster-scope is the only change made there,
this obviously is the cause of the error.


<details>

1. Checkout latest commit in master branch and run test
```
$ git clone https://github.com/mkimuram/operator-sdk-samples.git
$ git checkout cluster-scope-e2e
$ git checkout 01a0e2d53ac3fac46784d2b6dddcad7031c25fbc
$ operator-sdk test local ./test/e2e/
```

Fails with:
```
            memcached_test.go:100: Initialized cluster resources
            memcached_test.go:103: namespace osdk-e2e-74337ee0-3ab9-47bb-a400-d83087919c8e already exists: namespaces "osdk-e2e-74337ee0-3ab9-47bb-a400-d83087919c8e" already exists
```

This is out of the scope of this topic, but I think that it is introduced in https://github.com/operator-framework/operator-sdk/pull/2617 .

2. Workaround for 1 (Workaround incompatibility between GetNamespace and GetOperatorNamespace)
```
$ git checkout cluster-scope-e2e
$ git checkout 56643a6eff02f3ed869ec6d4bbe8affb13273f4b
$ operator-sdk test local ./test/e2e/
```

Succeeds.


3. Modify the scope (Make operator cluster-scope) as described in [the document](https://sdk.operatorframework.io/docs/operator-scope/#cluster-scoped-operator-usage)
```
$ git checkout cluster-scope-e2e
$ git checkout e555bb0bf0c810b232b5b18490b2a744c88d3a4c
$ operator-sdk test local ./test/e2e/
```

Fails with:
```
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            wait_util.go:67: Waiting for full availability of memcached-operator deployment (0/1)
            memcached_test.go:110: timed out waiting for the condition
```
```
{"level":"error","ts":1589217438.0970838,"logger":"k8sutil","msg":"Failed to get Pod","Pod.Namespace":"osdk-e2e-991a4822-dc6c-42c8-9c42-bc46d654389b","Pod.Name":"memcached-operator-59cc6b96-svblk","error":"pods \"memcached-operator-59cc6b96-svblk\" is forbidden: User \"system:serviceaccount:osdk-e2e-991a4822-dc6c-42c8-9c42-bc46d654389b:memcached-operator\" cannot get resource \"pods\" in API group \"\" in the namespace \"osdk-e2e-991a4822-dc6c-42c8-9c42-bc46d654389b\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).
```


4. Apply workaround for cluster-scope (Apply improvement createFromYAML to modify cluster scoped resources)
```
$ git checkout cluster-scope-e2e
$ git checkout 209fc238139cacd6e0f5db415b2c7fb11f5e68be
$ operator-sdk test local ./test/e2e/
```

Succeeds.



Note that 
steps like below are needed before `operator-sdk test` command, 
```
sed -i 's|Always|IfNotPresent|g' deploy/operator.yaml
sed -i 's|REPLACE_IMAGE|quay.io/example/memcached-operator:v0.0.1|g' deploy/operator.yaml
```
and below step might is needed after `operator-sdk test` command, 
```
git stash
```
until step 2, where I forgot to revert the changes :)

Also, to try step 4, my modified version of operator-sdk need to exist in the referenced path. 
(I assume that operator-sdk and operator-sdk-sample exists under the same directory.)
```
$ git clone https://github.com/mkimuram/operator-sdk.git
$ git checkout e2e-cluster-scope-v0.17.0
```

</details>

**Comment by camilamacedo86** [comment] 2020-05-11 23:51
Hi @mkimuram, 

Really thank you for your collaboration and great effort on it. Today we discussed this issue in the Bug Traigged meeting. The current strategy is to integrate the project with Kubebuilder. We are near to achieve this goal and then, the test-framework will be deprecated soon. 

In this way, we will start to recommend to use the env-test instead of it. See: https://book.kubebuilder.io/reference/testing/envtest.html. Because of this was decided that would not really be worth at this point we spend effort by improving the test-framework. 

I hope that it is ok for you. We will be close to this one. Also, feel free to attend this meeting if you wish. More info: https://github.com/operator-framework/community

**Closed by camilamacedo86** 2020-05-11 23:51 UTC
Labels: triage/unresolved

**Comment by mkimuram** [comment] 2020-05-12 15:58
@camilamacedo86

It sounds a good idea to leverage libraries. And envtest seems to provide a good interface.

However, for this particular use case, we need to modify manifests from files and envtest currently doesn't seem to provide a way to do it. (Actually, even without this use case, modifying `metadata.namespace` would be required for testing in auto-generated namespace, which is needed for running e2e test in parallel.)
So, I think that we need something like `PatchItems` in `CreateFromManifests` implemented [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/utils/create.go#L206), before [`CreateCRDs` in `InstallCRDs`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/envtest/crd.go#L69) in envtest.

Without it, we will be required to implement it again by ourselves, even after we leverage envtest.
(I mean to say that we should add such a feature to envtest, not mean to say don't use evntest.
And minimum requirement in short term is to make `readCRDFiles` public, so that we can add such modification between read and create by ourselves, until sophisticated `InstallCRDs` are provided.)

**Comment by mkimuram** [comment] 2020-05-12 22:35
Also, I noticed that envtest has [strict check](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/envtest/crd.go#L370) to only create CRD, so it needs to be modified to allow creating k8s resources, like sa and rolebinding.

**Comment by joelanford** [comment] 2020-05-13 03:02
@mkimuram 

> Actually, even without this use case, modifying metadata.namespace would be required for testing in auto-generated namespace, which is needed for running e2e test in parallel.

In Kubebuilder, the default operator scope is cluster-scoped, which makes running tests in parallel quite a bit more difficult (if not impossible) since multiple instantiations of the operator would all try to reconcile any CR that gets created. `envtest` is quite a bit different than the SDK test-framework so some of the concepts (like auto-generation of random namespaces) won't translate nicely.

> So, I think that we need something like PatchItems in CreateFromManifests implemented here, before CreateCRDs in InstallCRDs in envtest.

`envtest` is mainly focused on giving you a Kubernetes environment that can be reproduced from scratch every time you run tests. Helpers like `PatchItems` and `CreateFromManifests` can be imported and used with `envtest`. It's unfortunate they're in k/k since that makes importing those, in particular, a huge pain :slightly_frowning_face:

> Also, I noticed that envtest has strict check to only create CRD, so it needs to be modified to allow creating k8s resources, like sa and rolebinding.

Other resources can be created with controller-runtime's `client.Client`. This page has some high level descriptions and links to some examples that use envtest:

https://book.kubebuilder.io/reference/writing-tests.html

Lastly, rest assured that as we make this transition in SDK, we'll be working more and more on the upstream projects and documenting more examples. So be on the lookout in the near future!

**Comment by mkimuram** [comment] 2020-05-14 21:37
@joelanford 

Thank you for your comment and sharing information.

> It's unfortunate they're in k/k since that makes importing those, in particular, a huge pain 🙁

I agree with you that it would be a pain. So, we need to port part of them somewhere, if we use this approach.

> Other resources can be created with controller-runtime's client.Client. This page has some high level descriptions and links to some examples that use envtest:

I see. Thank you.

> envtest is mainly focused on giving you a Kubernetes environment that can be reproduced from scratch every time you run tests. 

I understand that envtest works for both mocked controller and real k8s controller. And your comment above seems to mention mocked controller case for integration test, while I'm interested in real k8s controller for e2e test. Could you let me know how it will work for later case?



> In Kubebuilder, the default operator scope is cluster-scoped, which makes running tests in parallel quite a bit more difficult (if not impossible) since multiple instantiations of the operator would all try to reconcile any CR that gets created. envtest is quite a bit different than the SDK test-framework so some of the concepts (like auto-generation of random namespaces) won't translate nicely.

I think that we will be able to avoid conflict among multiple instances of operators by patching `WATCH_NAMESPACE` as well on each parallel test run. (as you said 'not impossible')

And, I've implemented a PoC code for it. Please see https://github.com/mkimuram/operator-sdk-samples/commits/e2e-ginkgo2 .

- The 1st commit makes e2e run using ginkgo without dependency to current operator-sdk's e2e framework. 
- The 2nd commit is patching WATCH_NAMESPACE env in operator to specified namespace. 
- The 3rd commit make memcahce-operator cluster-scope.
- The 4th commit shows how to use the 2nd commit for 3rd commit's situation.


It works by below command. As the result shows, operator only handles the resources inside `WATCH_NAMESPACE`
```
go test ./test/e2e-ginkgo/ -v -ginkgo.v --kubeconfig=$HOME/.kube/config
--image=quay.io/example/memcached-operator:v0.0.1
--image-pull-policy=IfNotPresent
```


However, while writing this comment, I noticed that there are [no `WATCH_NAMESPACE`](https://github.com/mkimuram/operator-sdk-samples/blob/master/go/kubebuilder/memcached-operator/config/manager/manager.yaml) any more in kubebuilder version ...
Can't we use this approach in the version?
