### ISSUE TITLE
Best Practices: Updating operator-sdk, watching different kinds, and community

### ISSUE THREAD

**Issue by steveyang95** [operator-framework/operator-sdk#2178] opened 2019-11-11 18:23 UTC
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

General questions on best practices:

Q: If we ever need to update the operator-sdk to whatever is latest, what is the recommended way to update our operators?

Q: For the add function, there is a TODO comment like the following:

> Modify this to be the types you create that are owned by the primary resource

When would you want to watch anything besides a pod, deployment, replicaset, or a daemonset? Does it make sense to watch secrets? Services? Volumes?

Q: Is there a community forum, slack channel, or some other social medium in order to ask such questions as above or is Github issue the best place?

**Comment by steveyang95** [comment] 2019-11-11 18:33
I found the following for updating operator-sdk, but the changes seem to be very manual:
https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md

If I was on operator-sdk version 0.9.x and if I want to go to 0.11.x, do I need to manually apply the changes for 0.10.x first and then go to 0.11.x?

**Comment by camilamacedo86** [comment] 2019-11-11 20:34
Hi @steveyang95, 

> Q: If we ever need to update the operator-sdk to whatever is latest, what is the recommended way to update our operators?

As you checked and found it you need to follow the steps in the [version upgrade doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md). 

> If I was on operator-sdk version 0.9.x and if I want to go to 0.11.x, do I need to manually apply the changes for 0.10.x first and then go to 0.11.x?

Yes. I'd recommend you do step by step and keep your project updated in order to avoid tech debts as well. 

> Q: For the add function, there is a TODO comment like the following:
> Modify this to be the types you create that are owned by the primary resource

The TODO in the code shows places that you might would like to add the code implementation according to your solution. So regards the following code in the init/scaffolded project it is showing a watch implemented for the pod which is used as an example. However, you might have N watch func implemented here.

```go
	// TODO(user): Modify this to be the types you create that are owned by the primary resource
	// Watch for changes to secondary resource Pods and requeue the owner {{ .Resource.Kind }}
	err = c.Watch(&source.Kind{Type: &corev1.Pod{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &{{ .GoImportIdent }}.{{ .Resource.Kind }}{},
	})
	if err != nil {
		return err
	}
```
I'd like to recommend you check the [Memcached Sample](https://github.com/operator-framework/operator-sdk-samples/tree/master/memcached-operator) and the blog post [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/).

Also, as a reference, I'd like to provide a more complete example which is a personal project which I have been working on. See [here](https://github.com/dev4devs-com/postgresql-operator). Note that it covers the integration with OLM and is published in [operatorhb.io](https://operatorhub.io/operator/postgresql-operator-dev4devs-com)

> When would you want to watch anything besides a pod, deployment, replicaset, or a daemonset? Does it make sense to watch secrets? Services? Volumes?

The goal of the watch feature has triggered the Reconcile in the case of has any change in the resource. So, what resource would make sense or not sense be watched is according to the solution and business. In general, would make sense watch what is be managed/controlled by the controller. 

So, if something changed by a mistake, for example, caused by human intervention would be possible solved it automatically. 

> Q: Is there a community forum, slack channel, or some other social medium in order to ask such questions as above or is Github issue the best place?

For questions/issues/rfes I'd recommend you raise here in the repo. However, please, feel free to check the operator-framework google group as well. See [here](https://github.com/operator-framework/operator-sdk/blob/master/CONTRIBUTING.MD#email-and-chat).

I believe that this answer covers all the questions raised. In this way, I am closing this one. However, please feel free to re-open if you think that it still required. 

I hope that it helps you with.

**Closed by camilamacedo86** 2019-11-11 20:34 UTC
Labels: triage/support
