### ISSUE TITLE
Controller do not wait for next reconcile if set `RequeueAfter: 10 * time.Second` 

### ISSUE THREAD

**Issue by DeamonMV** [operator-framework/operator-sdk#6332] opened 2023-02-23 10:49 UTC
## Type of question

 General operator-related help 

#### What did you do?

I want to have a timeout before next reconcile after create a new Recourse(ex. Ingress).

To make it possible I used  such construction `return ctrl.Result{RequeueAfter: 10 * time.Second}, nil`, my code is can be found [here](https://github.com/DeamonMV/static-webpage-k8s-operator/blob/60ce5c60fb4a9c32a571ad030fdc13717c9cc2a9/controllers/static_controller.go#L365)

#### What did you expect to see?

I except that controller will wait 10 second before do next reconcile

#### What did you see instead? Under which circumstances?

So I create a new CR, I see that controller do not wait at all, and it lead to problem "... already exists"

```
1.6771476353359025e+09  INFO    RECONCILE       {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "523a1d79-d43a-4f95-a19c-7dc3ca711fd2"}
1.6771476353359363e+09  INFO    2023-02-23 10:20:35.335931345 +0000 UTC m=+118.957936405        {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "523a1d79-d43a-4f95-a19c-7dc3ca711fd2"}
1.6771476353459191e+09  INFO    Creating a new Deployment       {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"},
"namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "523a1d79-d43a-4f95-a19c-7dc3ca711fd2", "Deployment.Namespace": "static-webpage-k8s-operator-system", "Deployment.Name": "sample-1"}
1.6771476353517501e+09  INFO    RECONCILE       {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "84ff484f-5a06-4524-9086-5292b1b53ee3"}
1.6771476353517928e+09  INFO    2023-02-23 10:20:35.351787105 +0000 UTC m=+118.973792243        {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "84ff484f-5a06-4524-9086-5292b1b53ee3"}
1.6771476353518734e+09  INFO    Creating a new Service  {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "84ff484f-5a06-4524-9086-5292b1b53ee3", "Service.Namespace": "static-webpage-k8s-operator-system", "Service.Name": "sample-1"}
1.6771476353841863e+09  INFO    RECONCILE       {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "d8cc8bb1-81a7-4910-9e32-49f47f07ddbf"}
1.677147635384227e+09   INFO    2023-02-23 10:20:35.384220911 +0000 UTC m=+119.006225973        {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "d8cc8bb1-81a7-4910-9e32-49f47f07ddbf"}
1.6771476353843064e+09  INFO    Creating a new Ingress  {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "d8cc8bb1-81a7-4910-9e32-49f47f07ddbf", "Ingress.Namespace": "static-webpage-k8s-operator-system", "Ingress.Name": "sample-1"}
1.6771476354446588e+09  INFO    RECONCILE       {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "4bfa77f6-d482-4c90-8c55-7b6bf179457b"}
1.677147635444688e+09   INFO    2023-02-23 10:20:35.444682603 +0000 UTC m=+119.066687665        {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "4bfa77f6-d482-4c90-8c55-7b6bf179457b"}
1.6771476354447663e+09  INFO    Creating a new Ingress  {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "4bfa77f6-d482-4c90-8c55-7b6bf179457b", "Ingress.Namespace": "static-webpage-k8s-operator-system", "Ingress.Name": "sample-1"}
1.6771476355101254e+09  ERROR   Failed to create new Ingress    {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"},
"namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "4bfa77f6-d482-4c90-8c55-7b6bf179457b", "Ingress.Namespace": "static-webpage-k8s-operator-system", "Ingress.Name": "sample-1", "error": "ingresses.networking.k8s.io \"sample-1\" already exists"}
github.com/DeamonMV/static-webpage-k8s-operator/controllers.(*StaticReconciler).Reconcile
        /workspace/controllers/static_controller.go:357
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234
1.6771476355103161e+09  ERROR   Reconciler error        {"controller": "static", "controllerGroup": "webpage.daemon.io", "controllerKind": "Static", "Static": {"name":"sample-1","namespace":"static-webpage-k8s-operator-system"}, "namespace": "static-webpage-k8s-operator-system", "name": "sample-1", "reconcileID": "4bfa77f6-d482-4c90-8c55-7b6bf179457b", "error": "ingresses.networking.k8s.io \"sample-1\" already exists"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234
```        

#### Environment

**Operator type:**

/language go 

**Kubernetes cluster type:**

Just Kubernetes cluster deployed by Kubespray.

`$ operator-sdk version`
```
operator-sdk version: "v1.27.0", commit: "5cbdad9209332043b7c730856b6302edc8996faf", kubernetes version: "1.25.0", go version: "go1.19.5", GOOS: "linux", GOARCH: "amd64"
```

`$ go version (if language is Go)`
```
go version go1.19 linux/amd64
```

`$ kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```

#### Additional context

Nothing to add more.

**Comment by varshaprasad96** [comment] 2023-02-27 15:23
@DeamonMV In controller-runtime, the result of reconciler is based on which we enqueue the events again into controller's queue (https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/internal/controller/controller.go#L215-L229). `ctrl.Result{RequeueAfter: 10 * time.Second}` helps in controlling the time period in which you would like to add an event with the key of your Custom Resource to the queue. 

However, looks like your controller is watching other resources: https://github.com/DeamonMV/static-webpage-k8s-operator/blob/60ce5c60fb4a9c32a571ad030fdc13717c9cc2a9/controllers/static_controller.go#L452-L455. If any other object triggers an event, it will also call the [EnqueueRequestForOwner](https://github.com/kubernetes-sigs/controller-runtime/blob/f6f37e6cc1ec7b7d18a266a6614f86df211b1a0a/pkg/builder/controller.go#L113) which will [add keys](https://github.com/kubernetes-sigs/controller-runtime/blob/f6f37e6cc1ec7b7d18a266a6614f86df211b1a0a/pkg/handler/enqueue_owner.go#L50) to the controller's queue. 

With RequeueAfter you can control the delay with which the key is added for your CR but cannot control the events added from other sources (afaik). 

I would like to understand your use case though, because `RequeueAfter` is usually used for timed reconciliation in case there is any change in cluster caused by objects which cannot be watched by the controller. If you would like to wait for the object to be created, I would suggest to either poll till you are able to fetch the object or maybe have a hard `time.Sleep()`.

**Comment by varshaprasad96** [comment] 2023-03-16 16:57
@DeamonMV I am closing this issue for now. Please feel free to reopen if you have any concerns. Thanks for raising the issue!

**Closed by varshaprasad96** 2023-03-16 16:57 UTC
Labels: triage/support, language/go
