### ISSUE TITLE
Support for s390x for the Go operator

### ISSUE THREAD

**Issue by IBMRob** [operator-framework/operator-sdk#2526] opened 2020-02-10 12:24 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**

As per https://github.com/operator-framework/operator-sdk/blob/master/doc/dev/release.md the operator-sdk is not supported on s390x. To enable our operators to be fully portable we need to be able to test and ship our operators across multiple platforms. 

**Describe the solution you'd like**

The operator-sdk support s390x and provide built binaries for the platform.

**Comment by camilamacedo86** [comment] 2020-02-10 12:35
HI @IBMRob, 

I flagged this one for we are able to check and discuss it internally. However, please feel free to collab with PR's as well if you wish in order to provide and proposal solution to attend this need.  

@joelanford WDYT?

**Comment by yselkowitz** [comment] 2020-02-17 18:52
Is this not fixed by #2564?  Binaries will be available once v0.16.0 is released, otherwise I have already provided binaries from my fork from which the aforementioned PR originated.  If you need official upstream binaries soon, that depends on whether a `/cherry-pick v0.15.x` of #2564 (which would apply cleanly last I checked) would be accepted.

**Comment by camilamacedo86** [comment] 2020-02-17 19:07
Hi @yselkowitz, 

I also understand that yes it is fixed. I am not sure if in this case, we should cherry-pick since it is not a bug fix. So, I am closing this one as solved. 

@IBMRob please, feel free to ping us if you think that it should be re-opened fo any reason.

**Closed by camilamacedo86** 2020-02-17 19:07 UTC
Labels: kind/feature, needs discussion
