### ISSUE TITLE
Add generate client command

### ISSUE THREAD

**Issue by robinbraemer** [operator-framework/operator-sdk#1802] opened 2019-08-08 20:06 UTC
## Feature Request

It would be convenient to provide a `generate client/clientset` command to generate a versioned clientset.

**Comment by hasbro17** [comment] 2019-08-12 22:19
@robinbraemer Thanks for opening the issue. Although this is probably a duplicate of #1646 so I'm going to close this and we can follow up over there.

In particular though I'd like to know the use case for using a generated clientset as opposed to the existing dynamic client.

**Closed by hasbro17** 2019-08-12 22:19 UTC
