### ISSUE TITLE
Unable to run the tests directly

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4153] opened 2020-10-31 23:36 UTC
#### What did you do?

Run make install and then run the tests directly via command line or IDE such as done before the changes made in the Makefile targets. 

#### What did you expect to see?

Be able to run the tests without the need to use the makefile target in order to troubleshooting. 

#### What did you see instead? Under which circumstances?

The error ` time="2020-11-01T10:03:52-03:00" level=fatal msg="Failed to install OLM version \"0.15.1\": deployment/olm-operator failed to rollout: Get \"https://127.0.0.1:55256/apis/apps/v1/namespaces/olm/deployments/olm-operator\": context deadline exceede` is faced when we run: 

- $ make install
- $ kind delete cluster
- $ kind create cluster
- $ go test ./test/e2e-go -v -ginkgo.v

<details>
<summary>
`see the full log`
</summary>
```
camilamacedo@Camilas-MacBook-Pro ~/go/src/github.com/operator-framework/operator-sdk (master) $ kind delete cluster
Deleting cluster "kind" ...
camilamacedo@Camilas-MacBook-Pro ~/go/src/github.com/operator-framework/operator-sdk (master) $ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
camilamacedo@Camilas-MacBook-Pro ~/go/src/github.com/operator-framework/operator-sdk (master) $ go test ./test/e2e-go -v -ginkgo.v
=== RUN   TestE2EGo
Running Suite: E2EGo Suite
==========================
Random Seed: 1604235586
Will run 4 of 4 specs

STEP: creating a new test context
STEP: creating a new directory
preparing testing directory: /Users/camilamacedo/go/src/github.com/operator-framework/operator-sdk/test/e2e-go/e2e-enhy
STEP: fetching the current-context
running: kubectl config current-context
STEP: preparing the prerequisites on cluster
STEP: checking API resources applied on Cluster
running: kubectl api-resources
STEP: installing Prometheus
running: kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.33/bundle.yaml
STEP: ensuring provisioned Prometheus Manager Service
running: kubectl get Service prometheus-operator
STEP: installing OLM
running: operator-sdk olm install --version 0.15.1 --timeout 4m
Failure [245.725 seconds]
[BeforeSuite] BeforeSuite 
/Users/camilamacedo/go/src/github.com/operator-framework/operator-sdk/test/e2e-go/e2e_go_suite_test.go:45

  Expected success, but got an error:
      <*errors.errorString | 0xc000294160>: {
          s: "operator-sdk olm install --version 0.15.1 --timeout 4m failed with error: time=\"2020-11-01T09:59:52-03:00\" level=info msg=\"Fetching CRDs for version \\\"0.15.1\\\"\"\ntime=\"2020-11-01T09:59:52-03:00\" level=info msg=\"Using locally stored resource manifests\"\nI1101 09:59:53.822393   32881 request.go:621] Throttling request took 1.047662202s, request: GET:https://127.0.0.1:55256/apis/apps/v1?timeout=32s\ntime=\"2020-11-01T09:59:59-03:00\" level=info msg=\"Creating CRDs and resources\"\ntime=\"2020-11-01T09:59:59-03:00\" level=info msg=\"  Creating CustomResourceDefinition \\\"catalogsources.operators.coreos.com\\\"\"\ntime=\"2020-11-01T09:59:59-03:00\" level=info msg=\"  Creating CustomResourceDefinition \\\"clusterserviceversions.operators.coreos.com\\\"\"\ntime=\"2020-11-01T10:00:01-03:00\" level=info msg=\"  Creating CustomResourceDefinition \\\"installplans.operators.coreos.com\\\"\"\ntime=\"2020-11-01T10:00:02-03:00\" level=info msg=\"  Creating CustomResourceDefinition \\\"operatorgroups.operators.coreos.com\\\"\"\ntime=\"2020-11-01T10:00:02-03:00\" level=info msg=\"  Creating CustomResourceDefinition \\\"subscriptions.operators.coreos.com\\\"\"\ntime=\"2020-11-01T10:00:03-03:00\" level=info msg=\"  Creating Namespace \\\"olm\\\"\"\ntime=\"2020-11-01T10:00:03-03:00\" level=info msg=\"  Creating Namespace \\\"operators\\\"\"\ntime=\"2020-11-01T10:00:03-03:00\" level=info msg=\"  Creating ServiceAccount \\\"olm/olm-operator-serviceaccount\\\"\"\ntime=\"2020-11-01T10:00:03-03:00\" level=info msg=\"  Creating ClusterRole \\\"system:controller:operator-lifecycle-manager\\\"\"\ntime=\"2020-11-01T10:00:03-03:00\" level=info msg=\"  Creating ClusterRoleBinding \\\"olm-operator-binding-olm\\\"\"\ntime=\"2020-11-01T10:00:03-03:00\" level=info msg=\"  Creating Deployment \\\"olm/olm-operator\\\"\"\ntime=\"2020-11-01T10:00:03-03:00\" level=info msg=\"  Creating Deployment \\\"olm/catalog-operator\\\"\"\ntime=\"2020-11-01T10:00:03-03:00\" level=info msg=\"  Creating ClusterRole \\\"aggregate-olm-edit\\\"\"\ntime=\"2020-11-01T10:00:03-03:00\" level=info msg=\"  Creating ClusterRole \\\"aggregate-olm-view\\\"\"\ntime=\"2020-11-01T10:00:03-03:00\" level=info msg=\"  Creating OperatorGroup \\\"operators/global-operators\\\"\"\nI1101 10:00:05.528158   32881 request.go:621] Throttling request took 1.04704742s, request: GET:https://127.0.0.1:55256/apis/autoscaling/v2beta1?timeout=32s\ntime=\"2020-11-01T10:00:07-03:00\" level=info msg=\"  Creating OperatorGroup \\\"olm/olm-operators\\\"\"\ntime=\"2020-11-01T10:00:07-03:00\" level=info msg=\"  Creating ClusterServiceVersion \\\"olm/packageserver\\\"\"\ntime=\"2020-11-01T10:00:08-03:00\" level=info msg=\"  Creating CatalogSource \\\"olm/operatorhubio-catalog\\\"\"\ntime=\"2020-11-01T10:00:09-03:00\" level=info msg=\"Waiting for deployment/olm-operator rollout to complete\"\ntime=\"2020-11-01T10:00:09-03:00\" level=info msg=\"  Waiting for Deployment \\\"olm/olm-operator\\\" to rollout: 0 of 1 updated replicas are available\"\ntime=\"2020-11-01T10:03:52-03:00\" level=fatal msg=\"Failed to install OLM version \\\"0.15.1\\\": deployment/olm-operator failed to rollout: Get \\\"https://127.0.0.1:55256/apis/apps/v1/namespaces/olm/deployments/olm-operator\\\": context deadline exceeded\"\n",
      }
      operator-sdk olm install --version 0.15.1 --timeout 4m failed with error: time="2020-11-01T09:59:52-03:00" level=info msg="Fetching CRDs for version \"0.15.1\""
      time="2020-11-01T09:59:52-03:00" level=info msg="Using locally stored resource manifests"
      I1101 09:59:53.822393   32881 request.go:621] Throttling request took 1.047662202s, request: GET:https://127.0.0.1:55256/apis/apps/v1?timeout=32s
      time="2020-11-01T09:59:59-03:00" level=info msg="Creating CRDs and resources"
      time="2020-11-01T09:59:59-03:00" level=info msg="  Creating CustomResourceDefinition \"catalogsources.operators.coreos.com\""
      time="2020-11-01T09:59:59-03:00" level=info msg="  Creating CustomResourceDefinition \"clusterserviceversions.operators.coreos.com\""
      time="2020-11-01T10:00:01-03:00" level=info msg="  Creating CustomResourceDefinition \"installplans.operators.coreos.com\""
      time="2020-11-01T10:00:02-03:00" level=info msg="  Creating CustomResourceDefinition \"operatorgroups.operators.coreos.com\""
      time="2020-11-01T10:00:02-03:00" level=info msg="  Creating CustomResourceDefinition \"subscriptions.operators.coreos.com\""
      time="2020-11-01T10:00:03-03:00" level=info msg="  Creating Namespace \"olm\""
      time="2020-11-01T10:00:03-03:00" level=info msg="  Creating Namespace \"operators\""
      time="2020-11-01T10:00:03-03:00" level=info msg="  Creating ServiceAccount \"olm/olm-operator-serviceaccount\""
      time="2020-11-01T10:00:03-03:00" level=info msg="  Creating ClusterRole \"system:controller:operator-lifecycle-manager\""
      time="2020-11-01T10:00:03-03:00" level=info msg="  Creating ClusterRoleBinding \"olm-operator-binding-olm\""
      time="2020-11-01T10:00:03-03:00" level=info msg="  Creating Deployment \"olm/olm-operator\""
      time="2020-11-01T10:00:03-03:00" level=info msg="  Creating Deployment \"olm/catalog-operator\""
      time="2020-11-01T10:00:03-03:00" level=info msg="  Creating ClusterRole \"aggregate-olm-edit\""
      time="2020-11-01T10:00:03-03:00" level=info msg="  Creating ClusterRole \"aggregate-olm-view\""
      time="2020-11-01T10:00:03-03:00" level=info msg="  Creating OperatorGroup \"operators/global-operators\""
      I1101 10:00:05.528158   32881 request.go:621] Throttling request took 1.04704742s, request: GET:https://127.0.0.1:55256/apis/autoscaling/v2beta1?timeout=32s
      time="2020-11-01T10:00:07-03:00" level=info msg="  Creating OperatorGroup \"olm/olm-operators\""
      time="2020-11-01T10:00:07-03:00" level=info msg="  Creating ClusterServiceVersion \"olm/packageserver\""
      time="2020-11-01T10:00:08-03:00" level=info msg="  Creating CatalogSource \"olm/operatorhubio-catalog\""
      time="2020-11-01T10:00:09-03:00" level=info msg="Waiting for deployment/olm-operator rollout to complete"
      time="2020-11-01T10:00:09-03:00" level=info msg="  Waiting for Deployment \"olm/olm-operator\" to rollout: 0 of 1 updated replicas are available"
      time="2020-11-01T10:03:52-03:00" level=fatal msg="Failed to install OLM version \"0.15.1\": deployment/olm-operator failed to rollout: Get \"https://127.0.0.1:55256/apis/apps/v1/namespaces/olm/deployments/olm-operator\": context deadline exceeded"
      

  /Users/camilamacedo/go/src/github.com/operator-framework/operator-sdk/internal/testutils/utils.go:219
------------------------------
STEP: uninstalling prerequisites
STEP: uninstalling Prometheus
running: kubectl delete -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.33/bundle.yaml
STEP: uninstalling OLM
running: operator-sdk olm uninstall
warning: error when uninstalling OLM: operator-sdk olm uninstall failed with error: I1101 10:04:03.643342   32964 request.go:621] Throttling request took 1.008471582s, request: GET:https://127.0.0.1:55256/apis/packages.operators.coreos.com/v1?timeout=32s
time="2020-11-01T10:04:04-03:00" level=info msg="Fetching CRDs for version \"0.15.1\""
time="2020-11-01T10:04:04-03:00" level=info msg="Using locally stored resource manifests"
time="2020-11-01T10:04:15-03:00" level=info msg="Uninstalling resources for version \"0.15.1\""
time="2020-11-01T10:04:15-03:00" level=info msg="  Deleting CustomResourceDefinition \"catalogsources.operators.coreos.com\""
time="2020-11-01T10:04:33-03:00" level=info msg="  Deleting CustomResourceDefinition \"clusterserviceversions.operators.coreos.com\""
time="2020-11-01T10:06:04-03:00" level=fatal msg="Failed to uninstall OLM: Get \"https://127.0.0.1:55256/apis/apiextensions.k8s.io/v1/customresourcedefinitions/clusterserviceversions.operators.coreos.com\": context deadline exceeded"

STEP: destroying container image and work dir
running: docker rmi -f quay.io/example/e2e-enhy:v0.0.1
```
</details>

#### Environment

$ operator-sdk version
operator-sdk version: "v1.1.0-7-gcc409fb3", commit: "cc409fb3b0b8785a794e503e2d2238fd950652ce", kubernetes version: "v1.18.8", go version: "go1.15.2 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"

#### Possible Solution

`make install` provide the SDK bin with OLM bindata

#### Additional context

Also, see that we are facing issues to install OLM lastest: https://github.com/operator-framework/operator-sdk/issues/4154

**Comment by camilamacedo86** [comment] 2020-10-31 23:36
c/c @estroz

**Comment by varshaprasad96** [comment] 2020-11-01 04:48
Hi @camilamacedo86 
I am not able to reproduce this issue. Could you please have a look at : https://github.com/operator-framework/operator-sdk/issues/4154#issuecomment-720026561

**Comment by camilamacedo86** [comment] 2020-11-01 13:09
Hi @varshaprasad96, 

sorry, I cut/paste the wrong output. I just updated the first comment. See that to test it I am doing:

- $ kind delete cluster
- $ kind create cluster
- $ go test ./test/e2e-go -v -ginkgo.v

**Comment by estroz** [comment] 2020-11-02 18:34
@camilamacedo86 the operator-sdk e2e tests are not meant to be run directly. There is a bunch of setup done in the Makefile and scripts like image builds and loading into the kind cluster. The tests were designed this way intentionally, so I'm closing this issue.

**Closed by estroz** 2020-11-02 18:34 UTC
Labels: kind/bug
