### ISSUE TITLE
Private Container Registry: operator-sdk run bundle can't start controller-manager pod due to incorrect imagePullSecret reference

### ISSUE THREAD

**Issue by SRodi** [operator-framework/operator-sdk#6622] opened 2023-11-07 12:11 UTC
## Bug Report

`operator-sdk run bundle` does not work on `openshift` when pulling images from `private container registry`

Symptoms:
* controller-manager pod cannot be started as the image cannot be pulled from the private registry [icr.io](http://icr.io/)

#### What did you do?
```bash
$ operator-sdk run bundle $BUNDLE_IMG --namespace operators  --pull-secret-name all-icr-io --ca-secret-name icr-ca-pem
INFO[0009] Creating a File-Based Catalog of the bundle "us.icr.io/ic4v-vpc-prod/secrets-operator-bundle:v0.1.3"
INFO[0012] Generated a valid File-Based Catalog
INFO[0018] Created registry pod: us-icr-io-ic4v-vpc-prod-secrets-operator-bundle-v0-1-3
INFO[0018] Created CatalogSource: secrets-operator-catalog
INFO[0018] OperatorGroup "operator-sdk-og" created
INFO[0018] Created Subscription: secrets-operator-v0-0-1-sub
INFO[0021] Approved InstallPlan install-htfw5 for the Subscription: secrets-operator-v0-0-1-sub
INFO[0021] Waiting for ClusterServiceVersion "operators/secrets-operator.v0.0.1" to reach 'Succeeded' phase
INFO[0021]   Waiting for ClusterServiceVersion "operators/secrets-operator.v0.0.1" to appear
INFO[0034]   Found ClusterServiceVersion "operators/secrets-operator.v0.0.1" phase: Pending
INFO[0035]   Found ClusterServiceVersion "operators/secrets-operator.v0.0.1" phase: InstallReady
INFO[0036]   Found ClusterServiceVersion "operators/secrets-operator.v0.0.1" phase: Installing
FATA[0120] Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition

$ k get po -n operators
NAME                                                              READY   STATUS             RESTARTS   AGE
cefc464696a5cb3b5df8bf983ebb24685f08b77594508b159aed026f4e2scrs   0/1     Completed          0          12m
secrets-operator-controller-manager-5d86b658c6-vh56b              1/2     ImagePullBackOff   0          12m
us-icr-io-ic4v-vpc-prod-secrets-operator-bundle-v0-1-3            1/1     Running            0          12m
```
#### What did you expect to see?

I expect `operator-sdk run bundle` command to:
1. pull the bundle image from private registry (successful)
2. pull operator image from same private registry (NOT successful)
3. run operator (NOT successful)

#### What did you see instead? Under which circumstances?

It looks like the `controller-manager` pod does not reference the correct `imagePullSecret`

```bash
$ k get po -n operators secrets-operator-controller-manager-5d86b658c6-vh56b -oyaml | grep imagePullSecrets -A1
  imagePullSecrets:
  - name: secrets-operator-controller-manager-dockercfg-z49dg
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

"OpenShift 4.11"

`$ operator-sdk version`

operator-sdk version: "v1.32.0", commit: "4dcbbe343b29d325fd8a14cc60366335298b40a3", kubernetes version: "1.26.0", go version: "go1.19.13", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.21.3 linux/amd64

`$ kubectl version`

Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.16+6981c04

`$ oc version`

Client Version: 4.11.0-0.okd-2022-10-28-153352
Kustomize Version: v4.5.4
Server Version: 4.11.50
Kubernetes Version: v1.24.16+6981c04

#### Additional context

I have also tried passing the flag `--ca-secret-name` with the Root CA .pem of the Private Container Registry, according to [private-bundle-and-catalog-image-registries doc](https://master.sdk.operatorframework.io/docs/olm-integration/cli-overview/#private-bundle-and-catalog-image-registries) but it makes no difference (i.e. again, the controller-manager pod does NOT reference correct imagePullSecret)

The `imagePullSecret` which is passed via flag `--pull-secret-name all-icr-io` to `operator-sdk run bundle` command  is correct, in fact the indexing pod `cefc464696a5cb3b5df8bf983ebb24685f08b77594508b159aed026f4e2scrs` is correctly pulling the bundle image from the same private container registry

```bash
$ k get po -n operators cefc464696a5cb3b5df8bf983ebb24685f08b77594508b159aed026f4e2scrs -oyaml | grep imagePullSecret -A1
  imagePullSecrets:
  - name: all-icr-io
  
 $ k describe po -n operators cefc464696a5cb3b5df8bf983ebb24685f08b77594508b159aed026f4e2scrs | grep Pulled
  Normal  Pulled          25m   kubelet            Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:83428122fdc8994899943f936ca3b657af4d6014e7dcd51706ff183f22a90a4c" already present on machine
  Normal  Pulled          25m   kubelet            Successfully pulled image "us.icr.io/ic4v-vpc-prod/secrets-operator-bundle:v0.1.3" in 2.172617011s
  Normal  Pulled          25m   kubelet            Container image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4fdbe7c4755a8665169937e56cbb290079f06c8c4be0c8b2981a12f71a496cf9" already present on machine
```

**Comment by joelanford** [comment] 2023-11-07 13:45
Just for context, this is expected behavior, and not a bug. The help text for `operator-sdk run bundle` shows:

```
--pull-secret-name string                   Name of image pull secret ("type: kubernetes.io/dockerconfigjson") required to pull bundle images. This secret *must* be both in the namespace and an imagePullSecret of the service account that this command is configured to run in
```

The flag is to enable pulling of bundle images from private registries, not controller images. It is not in scope for this flag for the pull secret to be used to pull the controller image as well.

OLM docs cover this a little bit here: https://olm.operatorframework.io/docs/tasks/make-catalog-available-on-cluster/#using-registry-images-that-require-authentication-as-catalogbundleoperatoroperand-images

The OLM docs seems to suggest that the solution is to pre-create the necessary pull secrets for the operator image pulls.

Part of the problem is that we can't always assume that the bundle image pull secret is the same thing required to pull operator images or operand images.

**Comment by joelanford** [comment] 2023-11-07 22:12
> secrets-operator-controller-manager-dockercfg-b4wml

Another of the OLM maintainers might know off the top of their head (I don't), but can you tell where this comes from?

The suggestion that the OLM docs makes is to create a pull secret in the controller namespace, and then attach that secret to the serviceaccount that the controller will run as. Is that possible for you?

Upstream docs here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account

**Comment by SRodi** [comment] 2023-11-08 09:38
> The suggestion that the OLM docs makes is to create a pull secret in the controller namespace, and then attach that secret to the serviceaccount that the controller will run as. Is that possible for you? 

@joelanford this is exactly the issue. Before anything else mentioned in previous comment, and the GH issue description, I have tried to add the `imagePullSecret` directly to the ServiceAccount of the operator as follows:

a. This is the ServiceAccount used by the controller-manager. The RBAC, including this ServiceAccount, is `generated by operator-sdk` and it is `managed by kustomize`

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secrets-operator
    app.kubernetes.io/part-of: secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
```

b. I have added the following

```yaml
imagePullSecrets:
  - name: all-icr-io
```

c. I have then built and push a new operator image and new operator bundle
d. deployed the new bundle (trying both methods described in point 1 and 2 of my previous comment)

----

Unfortunately the above has no effect, as it seems the `all-icr-io` imagePullSecrets in the controller-manager ServiceAccount is replaced by `secrets-operator-controller-manager-dockercfg-b4wml` as mentioned in my previous comment.

----

Of course, if we install the operator AND THEN update the ServiceAccount by adding my `all-icr-io` imagePullSecrets, AND THEN killing the controller-manager pod, the new controller-manager pod will use the ServiceAccount that reference the correct imagePullSecret and everything works as expected. But this is less than ideal. We would like to install the operator and make sure it works out of the box.

I believe this is a very common use case - anything wrong I am doing? thanks

**Comment by SRodi** [comment] 2023-11-08 16:04
@joelanford this worked! thanks for your help on this. I am happy enough with this resolution as it seems sustainable for future upgrades.

This is what I have done, just in case anyone else has the same issue 🙌 :

----

I have modified `config/manager/manager.yaml` and added `deployment.spec.template.spec.imagePullSecrets` with my secret name:

```yaml
      imagePullSecrets:
      - name: all-icr-io
```

Then:
1. build + push operator image [operator-sdk doc link](https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/#steps)
2. build + push bundle image [operator-sdk doc link](https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/#olm-deployment)
3. add bundle to the Catalog [olm doc link](https://olm.operatorframework.io/docs/tasks/creating-a-catalog/#add-a-bundle-to-the-catalog)
4. add channel entry for the bundle [olm doc link](https://olm.operatorframework.io/docs/tasks/creating-a-catalog/#add-a-channel-entry-for-the-bundle)
5. build + push catalog image [olm doc link](https://olm.operatorframework.io/docs/tasks/creating-a-catalog/#build-and-push-the-catalog-image)


I deployed `CatalogSource`, `OperatorGroup` and `Subscription`(mentioned in the previous comment). This automatically creates a new `InstallPlan` which is not automatically approved.
```bash
$ k get ip -n operators
NAME            CSV                       APPROVAL   APPROVED
install-6kdh9   secrets-operator.v0.0.2   Manual     false
```

I edited the `InstallPlan` to approve the operator install and here is the result:



```bash
$ k get csv -n operators secrets-operator.v0.0.1
NAME                      DISPLAY            VERSION   REPLACES   PHASE
secrets-operator.v0.0.1   secrets-operator   0.0.1                Succeeded

$ k get po -n operators
NAME                                                              READY   STATUS      RESTARTS   AGE
26a5a9603e3dcca21065c45058369b90a59351cfbd163927d705e17be6x4mtx   0/1     Completed   0          112s
db4db11887b68feacc9a39c40f15f85fb12b2db90a0792318305dab529rvm42   0/1     Completed   0          99m
ic4v-catalog-r2fgk                                                1/1     Running     0          3m53s
secrets-operator-controller-manager-5f4cbfdb7-9977f               2/2     Running     0          70s

$ k get po -n operators secrets-operator-controller-manager-5f4cbfdb7-9977f -oyaml | grep imagePullS -A1
  imagePullSecrets:
  - name: all-icr-io
```

**Comment by varshaprasad96** [comment] 2023-11-13 19:28
Thanks @joelanford @SRodi for looking into this. The issue seems resolved, though it would be nice to have this documented for reference. Closing this issue!

**Closed by varshaprasad96** 2023-11-13 19:28 UTC
Labels: language/go
