### ISSUE TITLE
Scorecard flake in "go unit and e2e" CI job

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#4148] opened 2020-10-30 14:52 UTC
## Bug Report
In the `go unit and e2e` on travis, I got a timeout error:

`Error: error running tests context deadline exceeded`

Log:

```
• Failure [60.118 seconds]

Testing Go Projects with Scorecard

/home/travis/gopath/src/github.com/operator-framework/operator-sdk/test/e2e-go/e2e_go_scorecard_test.go:27

  with operator-sdk

  /home/travis/gopath/src/github.com/operator-framework/operator-sdk/test/e2e-go/e2e_go_scorecard_test.go:28

    should work successfully with scorecard [It]

    /home/travis/gopath/src/github.com/operator-framework/operator-sdk/test/e2e-go/e2e_go_scorecard_test.go:37

    Unexpected error:

        <*errors.errorString | 0xc00003d600>: {

            s: "operator-sdk scorecard bundle --selector=suite=basic --output=json --wait-time=60s failed with error: Error: error running tests context deadline exceeded\nUsage:\n  operator-sdk scorecard [flags]\n\nFlags:\n  -c, --config string            path to scorecard config file\n  -h, --help                     help for scorecard\n      --kubeconfig string        kubeconfig path\n  -L, --list                     Option to enable listing which tests are run\n  -n, --namespace string         namespace to run the test images in\n  -o, --output string            Output format for results. Valid values: text, json (default \"text\")\n  -l, --selector string          label selector to determine which tests are run\n  -s, --service-account string   Service account to use for tests (default \"default\")\n  -x, --skip-cleanup             Disable resource cleanup after tests are run\n  -w, --wait-time duration       seconds to wait for tests to complete. Example: 35s (default 30s)\n\nGlobal Flags:\n      --verbose   Enable verbose logging\n\ntime=\"2020-10-30T14:47:21Z\" level=fatal msg=\"error running tests context deadline exceeded\"\n",```

**Comment by asmacdo** [comment] 2020-10-30 15:04
Also seen in helm e2e test

**Comment by estroz** [comment] 2020-11-10 17:59
Bumping the timeout to 2m will fix this.

**Comment by camilamacedo86** [comment] 2020-11-10 20:04
HI @estroz,

The images used in the CI should not be pulled since we build all images with the dev tag and load them on the cluster. 
So, why would be required a timeout of 2 min to get the image when they are on the cluster already? My guess is that the CI is using the release tags (pulling) when should not see:

Currently: 

1. We just replace 2 places with dev images for scorecard. See: https://github.com/operator-framework/operator-sdk/blob/e64d95f6a6e12b14b440507aebe4a0dc72ba329e/internal/testutils/scorecard.go#L88
2. Then, we relay on execute `make bundle` to generate all manifest files with the dev tag. See: https://github.com/operator-framework/operator-sdk/blob/master/test/e2e-go/e2e_go_suite_test.go#L122-L124
3. Then, we run OLM and scorecard tests which will use the images:tag defined in the manifests. 

We expected that, after run `make bundle,` all manifests will be updated to use the `dev` image but we are not updating all or check if all is updated either before running the tests. More info:  https://com/operator-framework/operator-sdk/pull/3909#discussion_r490586393 and #3922. So, IMO it shows that the root cause for the timeout is because the tests are pulling the release tag images instead of using the dev ones because how it is implemented.

**Comment by estroz** [comment] 2020-11-10 21:50
How can they be pulled if you're already [replacing scorecard all images](https://github.com/operator-framework/operator-sdk/blob/723bec5a9895f07429297af84d75445a0082049f/internal/testutils/scorecard.go#L88) tags with the `<image>:dev` tag? That tag [does not exist remotely](https://quay.io/repository/operator-framework/scorecard-test?tab=tags), so can never be pulled. If they aren't  being replaced correctly then our regexp is failing and needs to be fixed and unit tested. However it appears to work just fine. This is the main reason why I believe #3922 is extraneous.

**Comment by camilamacedo86** [comment] 2020-11-10 22:37
> How can they be pulled if you're already replacing scorecard all images tags with the <image>:dev tag?

As described above, we are NOT replacing ALL images tags. We just replace 2 places. 

> That tag does not exist remotely, so can never be pulled

You linked https://quay.io/repository/operator-framework/scorecard-test?tab=tags which has the image with release tags. However, it is not the only image used by the scorecard. 

> If they aren't being replaced correctly then our regexp is failing and needs to be fixed and unit tested

The regex will ONLY fail if not be able to do the replace in the 2 specifics places. However, as described in https://com/operator-framework/operator-sdk/pull/3909#discussion_r490586393 and #3922 it has many other places/manifests. 

> However it appears to work just fine. This is the main reason why I believe #3922 is extraneous.

IMO it is not working fine at all, see: 

- we have a timeout issue that leads to us think that the CI has been pulling the release tag images when we should not pull any image at all 
- If we are using the release instead of the dev images, it works fine until a bug be introduced on the code which will only make the CI fail after the release since it means that the tests are NOT testing the changes made for scorecard
- Also, if I did NOT know about that and just addressed your suggestion made in https://github.com/operator-framework/operator-sdk/pull/4144/files#r518228619, which shows be very reasonable btw, to move the make bundle commands from the suite test to the OLM test then, it will no longer use dev images at all which means that we will NO longer be testing the scorecard changes introduced in the PR. What are the chances of someone just move the commands to create the bundle command to another place/order where/when it shows more appropriate? High since you want to do that, am I right? So, we very easily will end up in the scenario where we are not testing the code changes for the scorecard images which was the motivation for the fix/change made in https://com/operator-framework/operator-sdk/pull/3909 again.

**Comment by joelanford** [comment] 2020-11-11 13:49
> So, IMO it shows that the root cause for the timeout is because the tests are pulling the release tag images instead of using the dev ones because how it is implemented.

This sounds like speculation. Have you tried stepping through the e2e test manually to see what ends up in the bundle? How would release tags end up in the bundle if the source config files have been replaced with the `:dev` tags? That seems extremely unlikely. If you have verified a release tag is being used, can you identify which file contains the release tag?

Until we can find to a specific case where a release tag is used instead of the `:dev` tag, I think we can safely assume that we're using `:dev` tags everywhere we need to be.

IMO, this release tag vs. `:dev` tag is distracting us from the immediate problem. Let's go ahead and bump this timeout to see if that solves the flake, and if we find a case of the `:dev` tag replacement that needs to happen, we can fix that separately.

**Comment by camilamacedo86** [comment] 2020-11-11 15:51
Hi @joelanford, 
 
> This sounds like speculation. 

I understand that the error `context deadline exceeded` faced in the scorecard means that was NOT possible to pull the image. Then, I know that in the CI we should NOT pull the image. The CI should build a dev image using the code changes and load it in the Kind. The PR https://github.com/operator-framework/operator-sdk/pull/4144 has the goal to ensure that the CI will no longer pull the images and use the dev images by replacing ONLY 2 places and calling make a bundle with the expectation that all will be replaced after that. 

In this way, by looking `context deadline exceeded` I just can make the assumption that CI is pulling the image and that the solution in place does not work as respected. 

> Have you tried stepping through the e2e test manually to see what ends up in the bundle? 

Bisedes I be unable to run the tests locally https://github.com/operator-framework/operator-sdk/issues/4151, this check is possible and it confirmed my assuption above:  

<img width="1680" alt="Screen Shot 2020-11-11 at 12 33 45" src="https://user-images.githubusercontent.com/7708031/98832315-91ec1680-2434-11eb-9095-1a4ffebff9e2.png">

> IMO, this release tag vs. :dev tag is distracting us from the immediate problem. Let's go ahead and bump this timeout to see if that solves the flake, and if we find a case of the :dev tag replacement that needs to happen, we can fix that separately.

The problem is a timeout to pull an image that we should not pull at the first moment.
So, in POV increase the time to allow the CI to pull the image and can solve the flake but do not actually solve its root cause and just hide it. IMO the solution here is to ensure that we have all manifests with the dev tag to not pull the image at all which has been suggested in  #3922 .  However, if you wish folks we can do this PR.

**Comment by camilamacedo86** [comment] 2020-11-11 16:03
Hi @joelanford @estroz, 
 
I understand that the error `context deadline exceeded` faced in the scorecard occurs when is NOT possible to pull the image. Then, I know that in the CI we should NOT pull the image and use the dev image loaded on the Kind instead of that.  

In this way, by looking `context deadline exceeded` I just can make the assumption that CI is pulling the image when should not which shows to be the root cause here. However, I pushed the PR increasing the timeout as suggested to close this one:  https://github.com/operator-framework/operator-sdk/pull/4222

**Comment by joelanford** [comment] 2020-11-11 16:08
> I understand that the error context deadline exceeded faced in the scorecard means that was NOT possible to pull the image.

That's not right. All that means is that the test did not complete before the timeout. It doesn't tell us anything about _why_ the test didn't complete in time.

It looks like your screenshot is showing files in the generated projects in `testdata`. However, we [copy those projects into an e2e directory](https://github.com/operator-framework/operator-sdk/blob/265b948cca9248cbd60db81b162623976d6ea4f8/test/e2e-helm/e2e_helm_suite_test.go#L59), [replace those image tags](https://github.com/operator-framework/operator-sdk/blob/265b948cca9248cbd60db81b162623976d6ea4f8/test/e2e-helm/e2e_helm_suite_test.go#L69), and then [run `make bundle`](https://github.com/operator-framework/operator-sdk/blob/265b948cca9248cbd60db81b162623976d6ea4f8/test/e2e-helm/e2e_helm_suite_test.go#L91) to update the bundle with the correct image references.

I just commented out the [`tc.Destroy()` call](https://github.com/operator-framework/operator-sdk/blob/265b948cca9248cbd60db81b162623976d6ea4f8/test/e2e-helm/e2e_helm_suite_test.go#L102), ran the Helm e2e test, and verified that there are no image references that contain release tags in the `quay.io/operator-framework` repo.

```
$ grep -r 'quay.io/operator-framework' e2e-tlar
e2e-tlar/Dockerfile:FROM quay.io/operator-framework/helm-operator:dev
e2e-tlar/config/scorecard/patches/olm.config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/config/scorecard/patches/olm.config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/config/scorecard/patches/olm.config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/config/scorecard/patches/olm.config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/config/scorecard/patches/olm.config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/config/scorecard/patches/basic.config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/bundle/tests/scorecard/config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/bundle/tests/scorecard/config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/bundle/tests/scorecard/config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/bundle/tests/scorecard/config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/bundle/tests/scorecard/config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
e2e-tlar/bundle/tests/scorecard/config.yaml:    image: quay.io/operator-framework/scorecard-test:dev
```

**Comment by joelanford** [comment] 2020-11-11 16:51
I found this in the scorecard test pod before the e2e scorecard test timed out:
```
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    62s                default-scheduler  Successfully assigned default/scorecard-test-smpr to operator-sdk-e2e-control-plane
  Warning  FailedMount  30s (x7 over 62s)  kubelet            MountVolume.SetUp failed for volume "default-token-qkqgv" : secret "default-token-qkqgv" not found
```

I didn't see that secret in the namespace, but I may not have been fast enough before the test timed out and things got cleaned up.

**Closed** 2020-11-11 17:52 UTC
Labels: area/testing, kind/flake
