### ISSUE TITLE
TypeMeta : Kind + ApiVersion are empty

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#727] opened 2018-11-09 11:34 UTC
## Bug

When I create a `Component`'s custom resource, the component is well created and the MetaData well defined (Kind, ApiVersion)

```
oc get cp/fruit-client -o yaml                
apiVersion: component.k8s.io/v1alpha1
kind: Component
metadata:
  name: fruit-client
  namespace: my-spring-app
spec:
  deployment: innerloop
  exposeService: true
  runtime: springboot
  version: 1.5.16
```

but when the reconcile's function of the controller fetch the Component, then the Kind, ApiVersion fields are empty

What is the root cause of this issue ?

![screenshot 2018-11-09 12 27 43](https://user-images.githubusercontent.com/463790/48260329-53718a80-e41b-11e8-8696-f42ed333a9d1.png)

## Environment

```
okd : 3.11
operator-sdk : v0.1.1+git
```

## Project

Code of the API : https://github.com/snowdrop/component-operator/tree/operator-0.1.1/pkg/apis
Code of the controller : https://github.com/snowdrop/component-operator/blob/operator-0.1.1/pkg/controller/component/handler.go#L94

**Comment by cmoulliard** [comment] 2018-11-09 11:57
I have debugged the code and what I can say is that if the `Component` has already been cached, then we will get it with the fields set but if the obj is not yet cached, then the fields are empty ....

**Comment by odra** [comment] 2018-11-09 12:14
which operator sdk cli version did you use to generate the project?

**Comment by cmoulliard** [comment] 2018-11-09 12:21
BTW, I confirm that when the first time the object is retrieved [1] from the cache of the reader, then the fields are empty. 

```
// Get checks the indexer for the object and writes a copy of it if found
func (c *CacheReader) Get(_ context.Context, key client.ObjectKey, out runtime.Object) error {
	storeKey := objectKeyToStoreKey(key)

	// Lookup the object from the indexer cache
	obj, exists, err := c.indexer.GetByKey(storeKey) // TypeMeta/Kind and ApiVersion = ""
```
[1] https://goo.gl/oM6exr


![screenshot 2018-11-09 13 15 45](https://user-images.githubusercontent.com/463790/48262153-c120b500-e421-11e8-88fb-bca2fef1b39c.png)

Question :
- Do we have an issue during `deepCopy` process ?  
- Should we open a ticket for the kubernetes `controller-runtime` project ?

**Comment by shawn-hurley** [comment] 2018-11-09 13:03
1. Yes, if this is something that you can not live without then you will need to submit a bug to controller runtime.
2. Can you please explain the use case? Why is it is important to you that these fields are set? I can help get this change upstream if I understand the use case and why you need it.

**Comment by cmoulliard** [comment] 2018-11-09 13:36
> 2\. Why is it is important to you that these fields are set?

This is needed by some OpenShift's resources when they are created (DeploymentConfig, Route, ImageStream,....)

Error `DeploymentConfig.apps.openshift.io "fruit-client" is invalid: metadata.ownerReferences.kind: Invalid value: "": kind must not be empty ` is generated here - https://goo.gl/SuzM9p

![screenshot 2018-11-09 14 33 07](https://user-images.githubusercontent.com/463790/48265301-77899780-e42c-11e8-98e9-e90c88af53c6.png)

**Comment by cmoulliard** [comment] 2018-11-09 13:40
> 1. if this is something that you can not live without then you will need to submit a bug to controller runtime.

Ticket created : https://github.com/kubernetes-sigs/controller-runtime/issues/202

**Comment by shawn-hurley** [comment] 2018-11-09 15:12
@cmoulliard pushed a PR to controller-runtime kubernetes-sigs/controller-runtime#203

**Comment by cmoulliard** [comment] 2018-11-09 15:41
Well done @shawn-hurley :-) I will retest it.

**Comment by lli-hiya** [comment] 2018-11-26 20:38
I had the same issue. When I create my CR, which should create a deployment, the controller is complaining about that deployment has missing field in its ownerReferences: 

> "[metadata.ownerReferences.apiVersion: Invalid value: \"\": version must not be empty, metadata.ownerReferences.kind: Invalid value: \"\": kind must not be empty]"

I added some debug code to my controller and found that after I called this function:
`err := r.client.Get(context.TODO(), request.NamespacedName, my-cr-object)`, my-cr-object's API_Version and Kind will always be `""`, while other fields are correct.

**Comment by hasbro17** [comment] 2018-12-03 08:20
Waiting on the next release for the controller-runtime that includes the fix for this:
https://github.com/kubernetes-sigs/controller-runtime/pull/212

**Comment by cmoulliard** [comment] 2018-12-03 08:42
The PR of Shawn has been merged top of the master branch of controller-runtime but `v0.1.8` is not yet out.

**Comment by cmoulliard** [comment] 2018-12-03 08:45
I created a ticket to have more info about release's cadence and milestones of `controller-runtime`. https://github.com/kubernetes-sigs/controller-runtime/issues/231

**Comment by AlexNPavel** [comment] 2019-06-27 23:26
This was resolved in an older release of controller-runtime, so this should be resolved in the SDK as well

/close

**Closed by AlexNPavel** 2019-06-27 23:26 UTC
Labels: blocked, kind/bug, lifecycle/rotten

**Comment by msvechla** [comment] 2019-09-15 21:42
@AlexNPavel are you sure this has been resolved? I'm hitting the same issue on `operator-sdk v0.10.0` / `controller-runtime v0.1.12`

**Comment by tliron** [comment] 2020-02-02 19:38
Sorry, but this issue has not yet been resolved. A workaround is to check the Kind is empty, and if so to do a DeepCopy and set it explicitly:
```
if cr.Kind == "" {
	cr = cr.DeepCopy()
	cr.APIVersion, cr.Kind = CustomResourceGVK.ToAPIVersionAndKind()
}
```

**Comment by camilamacedo86** [comment] 2020-02-02 22:54
HI @tliron, 

Could you please, let us know if you check it with the latest version of SDK  0.15.1? Note that it was solved in the latest versions according to @AlexNPavel.

**Comment by tliron** [comment] 2020-02-03 15:07
Thanks for the attention, @camilamacedo86 ! Upon closer look I don't think the issue is in the Operator SDK, but rather in k8s.io/client-go v0.17.1. Do you have insight into what is going on? How was this underlying issue solved in the Operator SDK?

**Comment by camilamacedo86** [comment] 2020-02-03 15:23
Hi @tliron, 

The SDK uses the controller-runtime as dep. The controller-runtime is who is responsible to provide the client which will be used in the controllers o CRUD the resources in the cluster. In this way see:

> This was resolved in an older release of controller-runtime, so this should be resolved in the SDK as well

In this way, in the latest versions of SDK, it is using latest versions of controller-runtime which has this fixed.

**Comment by shinji62** [comment] 2020-07-15 08:41
@tliron I am wondering where you are putting 
```
if cr.Kind == "" {
	cr = cr.DeepCopy()
	cr.APIVersion, cr.Kind = CustomResourceGVK.ToAPIVersionAndKind()
}
```

For us we are stuck with Operator 0.17.1 which suppose to fix the issue as it's using `sigs.k8s.io/controller-runtime 0.5.8` but still kind and APIVersion are empty.

**Comment by tliron** [comment] 2020-07-15 14:05
@shinji62 I put that code immediately after I do a "get" from the indexer.

**Comment by shinji62** [comment] 2020-07-16 00:29
For me I don't get the `ToAPIVersionAndKind` function.. not sure how to get that.

**Comment by tliron** [comment] 2020-07-16 05:48
Sorry, it is pseudo-code. You need to get you APIVersion-Group-Kind combination from somewhere. You can even provide them as strings directly in case you know exactly which resource you are retrieving.
