### ISSUE TITLE
Helm: "release not found" error is unclear

### ISSUE THREAD

**Issue by xrow** [operator-framework/operator-sdk#2339] opened 2019-12-16 21:07 UTC
## Feature Request

**Is your feature request related to a problem? 

I have an issue when I am debugging an helm operator. I get an error message on which it is unclear on how to react or what to fix. I would like to see an improvement.

"failed to get release history: release: \"xxx-stage\" not found" is just not enough I would say. I believe the real cause are some template errors.

```
{"level":"error","ts":1576530167.8434966,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"ezplatform-controller","request":"xxx-stage/xxx-stage","error":"failed to get release history: release: \"xxx-stage\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.3.0/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88"}
```

**Describe the solution you'd like**
I get an error message that tells me what to fix.

**Comment by joelanford** [comment] 2019-12-16 21:34
@xrow what is the output of `operator-sdk version`?

**Comment by xrow** [comment] 2019-12-16 21:38
@joelanford I am using v0.12

**Comment by joelanford** [comment] 2019-12-16 21:52
@xrow Interesting. I asked because there's a known bug on `master` where something similar is occurring, but I'm not sure what's causing that with `v0.12.0`.

Can you provide more context? 
1. What logs were output leading up to that error? 
2. What happens that causes the operator to reconcile the CR when you see this error? Are you creating a CR, editing it, or deleting it?
3. Are you able to reproduce the issue consistently? If so, what steps are you taking to do that?

**Comment by xrow** [comment] 2019-12-16 21:56
I only have more hint.... just before I was seeing the opertor not not being able to install a release due to a missing key. That somehow fucked up the old install. There where no logs before other then sucessfull outout from before the i did an update on the release. I am getting this problem from time to time. I can`t tell yet on have to reproduce it on purpose.

**Comment by joelanford** [comment] 2019-12-16 23:04
Are you able to paste snippets from the operator log into this issue? Without that, it'll be tough to debug further. And let me know if you are able to figure out how to reproduce consistently.

**Comment by xrow** [comment] 2019-12-16 23:07
Yes I need time to repoduce... Below is the template error from before that did lead to the mentioned behavoir. I am now using v0.13.

```

{"level":"info","ts":1576537564.3795547,"logger":"cmd","msg":"Go Version: go1.13.5"}
--
  | {"level":"info","ts":1576537564.3796308,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
  | {"level":"info","ts":1576537564.3796418,"logger":"cmd","msg":"Version of operator-sdk: v0.13.0"}
  | {"level":"info","ts":1576537564.3796794,"logger":"cmd","msg":"Watching all namespaces.","Namespace":""}
  | {"level":"info","ts":1576537565.183579,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
  | {"level":"info","ts":1576537565.1865525,"logger":"helm.controller","msg":"Watching resource","apiVersion":"xrow.de/v1alpha1","kind":"EzPlatform","namespace":"","reconcilePeriod":"1m0s"}
  | {"level":"info","ts":1576537565.1865933,"logger":"leader","msg":"Trying to become the leader."}
  | {"level":"info","ts":1576537566.0011315,"logger":"leader","msg":"No pre-existing lock was found."}
  | {"level":"info","ts":1576537566.0047867,"logger":"leader","msg":"Became the leader."}
  | {"level":"info","ts":1576537567.6326325,"logger":"metrics","msg":"Metrics Service object updated","Service.Name":"ezplatform-operator-metrics","Service.Namespace":"kube-system"}
  | {"level":"info","ts":1576537567.6329103,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
  | {"level":"info","ts":1576537567.6329503,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"ezplatform-controller","source":"kind source: xrow.de/v1alpha1, Kind=EzPlatform"}
  | {"level":"info","ts":1576537567.6331146,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"ezplatform-controller"}
  | {"level":"info","ts":1576537567.7333205,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"ezplatform-controller","worker count":1}
  | {"level":"error","ts":1576537568.6566815,"logger":"helm.controller","msg":"Release failed","namespace":"hannover-stage","name":"hannover-stage","apiVersion":"xrow.de/v1alpha1","kind":"EzPlatform","release":"hannover-stage","error":"failed to install release: error parsing rendered template to add ownerrefs: error converting YAML to JSON: yaml: line 42: did not find expected key","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/helm/controller.HelmOperatorReconciler.Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/pkg/helm/controller/reconcile.go:174\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}


```

**Comment by joelanford** [comment] 2019-12-16 23:24
@xrow yep that error indicates that the rendered manifest from your chart contains invalid YAML.
I would expect that error to continually repeat (with a backoff) until the templating issue is resolved. Is that what you're seeing?

**Comment by xrow** [comment] 2019-12-16 23:27
Yes... that is right that error is clear to me... But concerning the error of the original issue it appeared when having the app already installed and an operator update came in place that broke it. Maybe with or wihtout the CRD being updated.

**Comment by joelanford** [comment] 2019-12-16 23:58
@xrow I'm not positive, but that templating error _may_ be a red herring. Do you have other logs from before and after the `failed to get release history: release: \"xxx-stage\" not found` error? 

Looking at the code, the only place I see with that error message is when the Helm operator is trying to uninstall a release. There's currently a bug in `v0.13.0` (The one I mentioned in my second comment and I think introduced inadvertently by https://github.com/operator-framework/operator-sdk/pull/1047) that causes the helm-operator to reconcile a stale version of the CR, making it think a release should exist, when in fact it was just uninstalled.  This bug is not entirely reproducible because the cache from which the CR is fetched during reconciliation is sometimes up-to-date, and sometimes it isn't.

If you get that error, but then no further error output, you should be able to safely ignore it because the operator will continue attempting reconciliation until the cache is up-to-date and the error ceases.

Nonetheless, this IS something we've noticed and are working on a fix for.

**Comment by xrow** [comment] 2019-12-17 00:01
Ok. Please put the ticket on hold or close. I need to gather more info and reproduce. Meanwhile thanks for your help.

**Comment by joelanford** [comment] 2019-12-17 18:19
@xrow I created https://github.com/operator-framework/operator-sdk/issues/2342 to cover this specific issue, so I'll close this one. If you find that you have found a separate issue, we can either re-open or create another new issue.

**Closed by joelanford** 2019-12-17 18:19 UTC
Labels: helm-operator, kind/bug
