### ISSUE TITLE
To requeue or not to requeue that is the question

### ISSUE THREAD

**Issue by woohhan** [operator-framework/operator-sdk#2898] opened 2020-04-24 02:08 UTC
## Type of question
how to implement a specific feature

## Question
Hi all, I'm using the operator SDK very well. But I was curious as I was writing the controller. My controller makes a Pod and PVC. Here is a sample code.

```go
pod := &corev1.Pod{}
err := r.client.Get(context.Background(), types.NamespacedName{Namespace: ipNamespace, Name: ipName}, pod)
if err != nil {
  if (!errors.IsNotFound(err)) {
    return reconcile.Result{}, err
  }
  if err := r.client.Create(context.Background(), ip); err != nil {
    return reconcile.Result{}, err
  }
  // here. requeue or not requeue?
  // 1: return reconcile.Result{requeue: true}, err
  // 2: just skip
}

pvc := &corev1.Pvc{}
// ... get and create pvc
```

The question is: after creating the Pod, should we return with `return reconcile.Result{requeue: true}, nil`? Or is it better not to be returned? Either way, IMO, the code works fine. But which one is better when we think about the concept of a reconciliation loop?

---

And this is the second question. When I wrote the code below, I occasionally encountered the `Pod Already Exists` error. In my opinion, this seems to have not been found in `r.client.Get` because the just created was not reflected when `r.client.Create` and the loop was called immediately. 

```go
pod := &corev1.Pod{}
err := r.client.Get(context.Background(), types.NamespacedName{Namespace: ipNamespace, Name: ipName}, pod)
if err != nil {
  if (!errors.IsNotFound(err)) {
    return reconcile.Result{}, err
  }
  if err := r.client.Create(context.Background(), ip); err != nil {
    return reconcile.Result{}, err
  }
}
```

I was able to fix the problem by making the following modifications. But I wonder that is there a better way. Should all `r.client.Create` be checked with `errors.IsAlreadyExists`?

```go
pod := &corev1.Pod{}
err := r.client.Get(context.Background(), types.NamespacedName{Namespace: ipNamespace, Name: ipName}, pod)
if err != nil {
  if (!errors.IsNotFound(err)) {
    return reconcile.Result{}, err
  }
  if err := r.client.Create(context.Background(), ip); err != nil {
    if errors.IsAlreadyExists(err) {
      return reconcile.Result{requeue: true}, err
    }
    return reconcile.Result{}, err
  }
}
```

Thanks in advance!

**Environment**
* operator-sdk version: 
```shell
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"
```

* Kubernetes version information:
```shell
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: NONE

**Additional context**
NONE

**Comment by camilamacedo86** [comment] 2020-04-24 15:25
Hi @woohhan, 

It will depend on the business logic implemented by yourself. Note that the reconcile works such as a loop which will still be running until achieving all its goals. See:

> The reconcile function is responsible for synchronizing the resources and their specifications according to the business logic implemented on them. In this way, it works like a loop, and it does not stop until all conditionals match its implementation. The following is pseudo-code with an example that clarifies it.

```go
reconcile App {

   // Check if a Deployment for the app exists, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
   
   // Check if a Service for the app exists, if not create one 
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   }  

   // Looking for Database CR/CRD 
   // Check the Database Deployments Replicas size
   // If deployment.replicas size != cr.size, then update it
   // Then, go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{Requeue: true}, nil
   }  
   ...
   
   // If it is at the end of the loop, then:
   // All was done successfully and the reconcile can stop  
   return reconcile.Result{}, nil

}
```

Reference: https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/

In this way, if you check the Go Memcached sample [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L123), you will see that the requeue is made after creating the Deployment because the next step requires to have this resource to check if the Deployment size is the same as the specified. See [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L134). 

However, the same need could be addressed by using the client.GET to get the Deployment resource created above before check the Deployment spec size instead of requeue it after the creation. So, it is important to implement a reconciler that will be an idempotent solution.   

I am closing it, however, please feel free to ping us to re-open it if you think that something still required is clarified over this subject.

**Closed by camilamacedo86** 2020-04-24 15:25 UTC
Labels: triage/support

**Comment by woohhan** [comment] 2020-04-25 04:21
@camilamacedo86 Thanks for your answer. I could understand it very well :)

**Comment by leg100** [comment] 2020-05-05 06:48
@camilamacedo86 I've wanted to ask these two questions too but I'd appreciate further clarification on the answers:

Q1) Why would `return reconcile.Result{requeue: true}` ever be necessary? Surely anything the reconciler is updating, it is also watching, and an update will *implictly* 'requeue' another reconcile. All that would be necessary to avoid further processing in the current reconcile would be a  `return reconcile.Result{}`, without a requeue.

Q2) I don't think this was answered? That is, "Should all r.client.Create be checked with errors.IsAlreadyExists?" as @woohhan asks. Is there a timing issue in which the `Create()` is not immediately reflected in the cache which the `Get()` reads? If so, is the only way to avoid this is to catch the error? And if not, what then is the cause?

Much appreciated.

**Comment by camilamacedo86** [comment] 2020-05-05 14:08
HI @leg100, 

Your question as answered above. 

**Why would return reconcile.Result{requeue: true} ever be necessary?**

> In this way, if you check the Go Memcached sample here, you will see that the requeue is made after creating the Deployment because the next step requires to have this resource to check if the Deployment size is the same as the specified. See here.

> However, the same need could be addressed by using the client.GET to get the Deployment resource created above, before checking the Deployment spec size, instead of requeue it after the creation. So, it is important to implement a reconciler that will be an idempotent solution.

**"Should all r.client.Create be checked with errors.IsAlreadyExists?"**

You have many ways to implement a solution. So, you can say for the project create the resource a not check if exist or not and then use `errors.IsAlreadyExists(err)` or you do as it is done in the example shared which is checking first if exist or not, then create which I prefer particularly think is a better way to do that and to ensure that the solution work idempotent.

However, note that this issue is closed. So, if you still needing help could you please create a new one?

**Comment by relaxdiego** [comment] 2024-07-24 09:27
> Q1) Why would return reconcile.Result{requeue: true} ever be necessary? Surely anything the reconciler is updating, the controller is also watching, and an update will implictly 'requeue' another reconcile. All that would be necessary to avoid further processing in the current reconcile would be a return reconcile.Result{}, without a requeue.

I feel like the answer to @leg100's question above was unsatisfactory especially in the case of a controller that owns resources like deployments. For example, say we registered the following controller to the manager:

```go
func (r *MyResourceReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&v1alpha1.MyResource{}, builder.WithPredicates(predicate.GenerationChangedPredicate{})).
		Owns(&appsv1.Deployment{}).
		Complete(r)
}
```

In the above case, provided that the deployments created by `MyResourceReconciler.Reconcile()` have their `ownerRef` set correctly, if anything changes with them (e.g. number of readyReplicas changed), wouldn't `MyResourceReconciler.Reconcile()` be automatically queued? If so, there would be no need to `return reconcile.Result{requeue: true}, nil` right after the deployment is created.

Also, since returning a `reconcile.Result{requeue: true}` triggers an exponential backoff rate limiter by default, I think it's important to consider this approach too.
