### ISSUE TITLE
Should disable the AllNamespaces installMode

### ISSUE THREAD

**Issue by jianzhangbjz** [operator-framework/operator-sdk#2173] opened 2019-11-10 10:50 UTC
## Bug Report

**What did you do?**
I create the CSV files by using `operator-sdk olm-catalog gen-csv` command.
```console
mac:learn-operator jianzhang$ operator-sdk olm-catalog gen-csv --operator-name learn-operator --csv-version 0.0.1 --csv-channel alpha 
INFO[0000] Generating CSV manifest version 0.0.1        
INFO[0000] Fill in the following required fields in file deploy/olm-catalog/learn-operator/0.0.1/learn-operator.v0.0.1.clusterserviceversion.yaml:
	spec.keywords
	spec.maintainers
	spec.provider 
INFO[0000] Created deploy/olm-catalog/learn-operator/0.0.1/learn-operator.v0.0.1.clusterserviceversion.yaml 
INFO[0000] Created deploy/olm-catalog/learn-operator/learn-operator.package.yaml 
```
But, failed to install the CSV.
```console
mac:learn-operator jianzhang$ oc get csv
NAME                                        DISPLAY                  VERSION              REPLACES                                    PHASE
learn-operator.v0.0.1                       Learn Operator           0.0.1                learn-operator.v0.0.0                       Pending

mac:learn-operator jianzhang$ oc describe csv learn-operator.v0.0.1 
...
  Install Modes:
    Supported:  true
    Type:       OwnNamespace
    Supported:  true
    Type:       SingleNamespace
    Supported:  false
    Type:       MultiNamespace
    Supported:  true
    Type:       AllNamespaces
...
  Normal   RequirementsUnknown  31m                 operator-lifecycle-manager  InstallModes now support target namespaces
```

**What did you expect to see?**
Should set the `AllNamespaces` to `false` as default since I didn't use the cluster CRD. 

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:
```console
mac:operator-sdk jianzhang$ operator-sdk version
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.4 darwin/amd64"
```

* go version:
```console
mac:operator-sdk jianzhang$ go version
go version go1.13.1 darwin/amd64
```

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

**Comment by estroz** [comment] 2019-11-12 01:02
@jianzhangbjz what do you mean by
> I didn't use the cluster CRD
Do you mean your operator is `Namespaced` scoped?

**Comment by jianzhangbjz** [comment] 2019-11-26 10:26
> I didn't use the cluster CRD

@estroz Sorry for the late reply. Yes, I used the `Namespaced` scoped as default.

**Comment by estroz** [comment] 2019-11-27 22:09
@jianzhangbjz can you please include:
>    Kubernetes version information:
>    Kubernetes cluster kind:
In your issue description. Seeing as you're using `oc`, this issue may be caused by your cluster version.

**Comment by camilamacedo86** [comment] 2020-03-09 19:01
Hi @estroz, 

I understand that when we scaffold the project by default the scope of the operator will be namespaced, however, when the CSV is generated by default it is done like the project was cluster-scoped and will be dealing with multi-namespaces.  

So, what @jianzhangbjz is a proposing in https://github.com/operator-framework/operator-sdk/pull/2174 is change the default configuration of CSV for it be scaffolded dealing with just 1 namespace by default which shows reasonable for me. Otherwise, for the default scaffold/setup need to edit manually the CSV in order to make them compatible. 

WDYT @estroz? Is it make sense?

Also, @jianzhangbjz please let me know if I misunderstood something here.

**Comment by estroz** [comment] 2020-05-22 20:44
Closing, see https://github.com/operator-framework/operator-sdk/pull/2174#issuecomment-626086945.

**Closed by estroz** 2020-05-22 20:44 UTC
Labels: olm-catalog, triage/unresolved
