### ISSUE TITLE
How to get webhook + OLM generation right

### ISSUE THREAD

**Issue by chrispatmore** [operator-framework/operator-sdk#4244] opened 2020-11-17 19:04 UTC
## Type of question

How to implement a specific feature

#### What did you do?

I was using `v1.0.0` to generate a webhook that I was using with OLM. I had to add in several "hacks"
to get around some issues, namely the webhook container port, target port, and deployment name. To do this
after building the bundle I would manipulate the CSV using `yq` to set these values appropriately.

```
    yq w -i "${csv}" spec.webhookdefinitions[*].containerPort "9443" 
    yq w -i "${csv}" spec.webhookdefinitions[*].targetPort "9443" 
    yq w -i "${csv}" spec.webhookdefinitions[*].deploymentName "<kustomize-prefix>-controller-manager" 
```

This lead to the created ValidatingWebhookConfiguration pointing at `<kustomize-prefix>-controller-manager-service` on port 9443 and a service being created called `<kustomize-prefix>-controller-manager-service` with port 9443, target port 9443. And everything lined up and worked as expected

I have just moved up to version `v1.2.0` which says it fixes the issues for which I had hacks above. So I removed the hacks I had in place and reran.

#### What am I seeing?

I am seeing behaviour I am confused by, and am now not sure how I am supposed to set this up so it works correctly.

I am really struggling to put into words what is being created and how it all isn't quite fitting together, because I am not sure what the expected behaviour is now. So I think it would be really helpful if someone could explain what it is that is expected to be generated and with what values, and what files those values are based on. So that I can compare and then say what I have got that is different from what is expected.

The essence of the problem is, since moving to `1.2.0` when I install the operator through OLM and remove the hacks I had in place. where I had 1 9443:9443 service (`<kustomize-prefix>-controller-manager-service`) and the generated `ValidatingWebhookConfiguration` was pointing at that service,
I know have 2 services. A `443:443` one (`<kustomize-prefix>-controller-manager-service`) that the webhook is pointing at, which therefore does not work, and a `443:9443` (`<kustomize-prefix>-webhook-service`) one that the webhook is not pointing at so is redundant.

I have tried to manipulate values to bring things in line, but everything I change just seems to make things worse or has no impact at all

**Operator type:**

/language go

**Kubernetes cluster type:**  OpenShift

`$ operator-sdk version` 1.2.0

`$ go version ` 1.15

**Comment by chrispatmore** [comment] 2020-11-18 09:08
Looking with fresh eyes in the morning, I see that although the generated CSV has 
```
targetPort: 9443
containerPort:443
```
Once I install the `targetPort` is no longer in the CSV, This may explain why the `<kustomize-prefix>-controller-manager-service` is not being generated as a `443:9443` service as I would expect

**Comment by chrispatmore** [comment] 2020-11-18 11:12
After testing on a `4.6.1` OCP I can confirm that the `<kustomize-prefix>-controller-manager-service` is now created with a `433:9443` port mapping and the webhook references that service so everything now lines up, and works correctly

*However* I still have the extra service `<kustomize-prefix>-webhook-service` being generated into the bundle, which is therefore being deployed into the cluster when I install even though nothing is using it

**Comment by varshaprasad96** [comment] 2020-11-23 18:09
Hi @chrispatmore , 
I will use @estroz 's demo project as an example here. The generated bundle should look like [this](https://github.com/estroz/kubecon-2020-demo/tree/main/bundle). `<kustomize-prefix>-webhook-service` should be having the target port to the value specified in the csv ([here](https://github.com/estroz/kubecon-2020-demo/blob/main/bundle/manifests/memcached-operator-webhook-service_v1_service.yaml#L9)). `<kustomize-prefix>-controller-manager-service` is the service created by OLM for the Webhooks which takes in the targetPorts defined in the `webhookdefinitions` section of the csv. Can I take a look at your crd just to check if any of the service is included ?

**Comment by chrispatmore** [comment] 2020-11-23 18:32
Oh all the services are there and everything now lines up thanks! (the bundle looks like the one you have linked), after upgrading to OCP `4.6.1`. The only thing I am interested in is the need for the `webhook-service` to be generated into the bundle, as it then get's deployed by OLM alongside the `controller-manager-service`. So I have created 2 services where I only need one, and only one is used

**Comment by estroz** [comment] 2020-11-23 18:48
>However I still have the extra service <kustomize-prefix>-webhook-service being generated into the bundle, which is therefore being deployed into the cluster when I install even though nothing is using it

`make bundle` reads a bunch of manifests from `kustomize build config/manifests` output, then adds manifests whose GVKs OLM supports to your on-disk bundle. Unfortunately there's no non-error-prone way to remove a webhook's service from that set of manifests because it could contain port mappings for other parts of your operator. Therefore this service will get added to `./bundle` and OLM will create it, but it won't actually do anything nor cause issues for your operator.

I think there are some improvements/additions that could be made to the set of scaffolded manifests in `./config` to configure `make bundle` to not add this service manifest to the bundle. For now, doing the following will work:

1. Uncomment only [this line](https://github.com/estroz/kubecon-2020-demo/blob/main/config/default/kustomization.yaml#L21) out of all `[WEBHOOK]` and `[CERTMANAGER]` lines in `./config/default/kustomization.yaml`.
1. Create a [patch](https://github.com/estroz/kubecon-2020-demo/blob/main/config/manifests/olm_manager_webhook_patch.yaml) that adds a webhook port to your manager's deployment (slimmed down version of :
	```sh
	cat <<EOF > ./config/manifests/olm_manager_webhook_patch.yaml
	apiVersion: apps/v1
	kind: Deployment
	metadata:
	  name: controller-manager
	  namespace: system
	spec:
	  template:
	    spec:
	      containers:
	      - name: manager
	        ports:
	        - containerPort: 9443
			  // Default targetPort is 443.
 	          name: webhook-server
	          protocol: TCP
	```
1. Add a [merge directive](https://github.com/estroz/kubecon-2020-demo/blob/main/config/manifests/kustomization.yaml#L6) to your manifests' kustomization.yaml.
	```sh
	cat <<EOF >> ./config/manifests/kustomization.yaml

	patchesStrategicMerge:
	# Exposes port 9443 for the OLM-managed webhook server.
	- olm_manager_webhook_patch.yaml
	```

**Comment by estroz** [comment] 2020-11-23 20:28
This problem is really a bug because `make bundle` should work out of the box, without and with webhooks.

**Comment by estroz** [comment] 2020-12-08 17:26
This issue is a duplicate of #4201 btw

/remove-triage support
/triage duplicate

**Closed** 2021-03-19 21:30 UTC
Labels: kind/bug, language/go, triage/duplicate
