### ISSUE TITLE
operator-sdk test local failed with `-skipCleanupOnError` flag provided but not defined

### ISSUE THREAD

**Issue by DanielXLee** [operator-framework/operator-sdk#2866] opened 2020-04-21 08:48 UTC
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
When I run e2e test with the `operator-sdk test local ./test/e2e`, find error
**flag provided but not defined: -skipCleanupOnError**

Detail logs:
```console
# operator-sdk test local ./test/e2e
INFO[0000] Testing operator locally.
flag provided but not defined: -skipCleanupOnError
Usage of /var/folders/9l/r11n63ld3v56nnkmy3wbs6xc0000gn/T/go-build477685006/b001/e2e.test:
  -globalMan string
    	path to operator manifest
  -kubeconfig string
    	path to kubeconfig
  -localOperator
    	enable if operator is running locally (not in cluster)
  -localOperatorArgs string
    	flags that the operator needs (while using --up-local). example: "--flag1 value1 --flag2=value2"
  -namespacedMan string
    	path to rbac manifest
  -root string
    	path to project root
  -singleNamespace
    	enable single namespace mode
  -test.bench regexp
    	run only benchmarks matching regexp
  -test.benchmem
    	print memory allocations for benchmarks
  -test.benchtime d
    	run each benchmark for duration d (default 1s)
  -test.blockprofile file
    	write a goroutine blocking profile to file
  -test.blockprofilerate rate
    	set blocking profile rate (see runtime.SetBlockProfileRate) (default 1)
  -test.count n
    	run tests and benchmarks n times (default 1)
  -test.coverprofile file
    	write a coverage profile to file
  -test.cpu list
    	comma-separated list of cpu counts to run each test with
  -test.cpuprofile file
    	write a cpu profile to file
  -test.failfast
    	do not start new tests after the first test failure
  -test.list regexp
    	list tests, examples, and benchmarks matching regexp then exit
  -test.memprofile file
    	write an allocation profile to file
  -test.memprofilerate rate
    	set memory allocation profiling rate (see runtime.MemProfileRate)
  -test.mutexprofile string
    	write a mutex contention profile to the named file after execution
  -test.mutexprofilefraction int
    	if >= 0, calls runtime.SetMutexProfileFraction() (default 1)
  -test.outputdir dir
    	write profiles to dir
  -test.parallel n
    	run at most n tests in parallel (default 12)
  -test.run regexp
    	run only tests and examples matching regexp
  -test.short
    	run smaller test suite to save time
  -test.testlogfile file
    	write test action log to file (for use only by cmd/go)
  -test.timeout d
    	panic test binary after duration d (default 0, timeout disabled)
  -test.trace file
    	write an execution trace to file
  -test.v
    	verbose: print additional output
FAIL	github.com/IBM/operand-deployment-lifecycle-manager/test/e2e	0.348s
FAIL
FATA[0002] Failed to build test binary: failed to exec []string{"go", "test", "./test/e2e/...", "-namespacedMan", "/var/folders/9l/r11n63ld3v56nnkmy3wbs6xc0000gn/T/namespaced-manifest.yaml170520042", "-globalMan", "/var/folders/9l/r11n63ld3v56nnkmy3wbs6xc0000gn/T/global-manifest.yaml347092033", "-root", "/Users/blob/go/src/github.com/IBM/operand-deployment-lifecycle-manager", "-skipCleanupOnError=false"}: exit status 1
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:
```console
# operator-sdk version
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "v1.17.2", go version: "go1.14.2 darwin/amd64"
# go version
go version go1.14.2 darwin/amd64
```

* go version:
```console
# go version
go version go1.14.2 darwin/amd64
```

* Kubernetes version information:

```console
oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0+b4261e0", GitCommit:"b4261e07ed", GitTreeState:"clean", BuildDate:"2019-10-06T23:21:44Z", GoVersion:"go1.13.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1", GitCommit:"29a3597", GitTreeState:"clean", BuildDate:"2020-03-13T05:44:41Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

**Comment by estroz** [comment] 2020-04-23 18:20
@DanielXLee I'm unable to reproduce this error locally. Can you provide a link to your e2e test code?

**Comment by DanielXLee** [comment] 2020-04-24 05:28
@estroz github.com/IBM/operand-deployment-lifecycle-manager/test/e2e, this is my e2e test code, and I can reproduce this issue with operator-sdk version `v0.16.0` and `v0.17.0`, for the version `v0.15.2`, it's good for me.

**Comment by camilamacedo86** [comment] 2020-04-24 11:20
Hi @DanielXLee, 

Your project is using 0.15.1. See your [go.mod](https://github.com/IBM/operand-deployment-lifecycle-manager/blob/master/go.mod#L12). And then, note that the flag `-skipCleanupOnError` was added in the 0.16. See the following entry in the [changelog](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#v0160):

> Add a new flag option (--skip-cleanup-error) to the test framework to allow skip the function which will remove all artefacts when an error be faced with performing this operation. (#2512)

So, you are using an upper version of the tool which is not compatible with the version used in your project. In this way, you can:

- Use the SKD client tool version 0.15.x as you checked that it worked successfully with already 

OR

- Upgrade duly your project to be able to use the upper versions. To do it, you can follow up the steps in the [migration guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#v016x). 

I hope that it helps you with and then I am closing this as sorted out. However, please feel free to ping us and ask to re-open if you think that it is required.

**Closed by camilamacedo86** 2020-04-24 11:20 UTC
Labels: triage/needs-information

**Comment by DanielXLee** [comment] 2020-04-27 05:42
Thanks, @camilamacedo86, I'll update our project to the newer version
