### ISSUE TITLE
Improve CI speed

### ISSUE THREAD

**Issue by fabianvf** [operator-framework/operator-sdk#1062] opened 2019-02-05 20:28 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**
Our CI runs are getting longer and longer, and a non-trivial portion of that is due to the dep ensure and build of the binary.

**Describe the solution you'd like**
It would be nice if we could make use of [travis caching](https://docs.travis-ci.com/user/caching/) to have a pre-step that's shared by all the stages that handles pulling the dependencies and doing the initial builds to make the binaries available from the cache, so that every stage wouldn't need to dep ensure and build.

**Comment by AlexNPavel** [comment] 2019-02-05 21:42
Would caching `$GOPATH/pkg/dep/sources` make sense? That would be a trivial addition that should help the speed of `dep` somewhat, as it wouldn't have to download full git repos with that cached

**Comment by AlexNPavel** [comment] 2019-02-05 21:44
The main issue with travis caching is that it's not network local, so this might not actually result in much of a speed improvement for us: https://docs.travis-ci.com/user/caching/#how-does-caching-work

**Comment by fabianvf** [comment] 2019-02-05 22:14
I was also thinking we could hopefully skip the dep ensure in some steps and just pull a cached binary. I don't think Ansible or Helm actually need anything other than a built binary.

**Comment by AlexNPavel** [comment] 2019-02-06 18:17
Caching is problematic on travis as the cache gets shared across basically all jobs (https://docs.travis-ci.com/user/caching/#pull-request-builds-and-caches), which can cause the cache to explode quite quickly if we try to cache the project binaries. We are adding the vendor to the git repo, which reduces the time dep takes to run to under 1 second (as all the dependencies are already in the project) and we'll start caching the go-build cache, which should reduce build times from ~1.5-2 minutes to <10 seconds.

**Comment by fabianvf** [comment] 2019-02-06 20:09
Ah, that's a shame, I misunderstood how this all worked.

**Comment by AlexNPavel** [comment] 2019-02-07 20:06
I think we can close this issue now, as the dependency getting and build speeds have been drastically improved. Here is a summary:

1. PR #1065: Added `vendor` to git. This increases the initial git clone time by ~1 second and allows the `dep ensure` stage to be reduced to ~1 second from the original ~200-250 seconds due to all dependencies already existing. It also fixes the occasional flakes caused by `dep` stalling during a pull. Overall improvement: ~3-4 minutes

2. PR #1068: Cache go-build cache in travis. Travis will first check if the PR already has a build cache. If not, it will then check the target branch, and then master. This allows us to avoid rebuilding the same dependencies every time we build the sdk and instead just build the couple of packages changed in the SDK and do the final linking. The download of the cache takes ~5 seconds, and archiving and uploading an updated cache takes ~45-50 seconds. The make install time gets reduced from ~100 seconds to ~10 seconds. Overall improvement: ~30 seconds-1 minute (note that the ~45-50 second upload happens after the tests complete, so if there is an error, it will be hit ~80 seconds quicker than before).

These changes combined result in ~4-5 minutes improvement for the go, ansible, and helm jobs.

**Closed by AlexNPavel** 2019-02-07 20:06 UTC
