### ISSUE TITLE
Errorof type "CrashLoopBackOff" when executing the "get pods" on the Go memcached operator example

### ISSUE THREAD

**Issue by spanichella** [operator-framework/operator-sdk#927] opened 2019-01-16 08:37 UTC
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
Followed the guideline here:
https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

when I arrive at the point:

"Verify that the memcached-operator is up and running:
$ kubectl get deployment"

I see the following:

NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
memcached-operator-long   1         1         1            0           15h
The main big difference here is that I have renamed the operator to "memcached-operator-long"

moreover, when from command line I execute, i get the following output:

"kubectl get pods
NAME                                       READY     STATUS             RESTARTS   AGE
memcached-operator-long-6b45cc5d84-dhtr2   0/1       CrashLoopBackOff   30         15h"

**Environment**
* operator-sdk version:

operator-sdk version v0.3.0+git

* Kubernetes version information:

  Insert output of `kubectl version` here
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2019-01-13T08:18:56Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
"I'm using minishift"

* Are you writing your operator in ansible, helm, or go?
Go

**Possible Solution**

**Additional context**

**Comment by LiliC** [comment] 2019-01-16 08:44
Hello @spanichella, thanks for your bug report! Can you provide a bit more details, can you get the `events` or/and `logs` from the deployed operator?

**Comment by spanichella** [comment] 2019-01-16 10:18
Reporting all what I did here:

$ mkdir -p $GOPATH/src/github.com/example-inc/
$ cd 
$GOPATH/src/github.com/example-inc/
$ operator-sdk new memcached-operator-long --cluster-scoped 
$ cd memcached-operator-long

# This will scaffold the Memcached resource API under pkg/apis/cache/v1alpha1/....
$ operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Memcached

Modified the spec and status of the Memcached Custom Resource(CR) at pkg/apis/cache/v1alpha1/memcached_types.go:

```
type MemcachedSpec struct {    
// Size is the size of the memcached deployment   
Size int32 `json:"size"`}

type MemcachedStatus struct {    
// Nodes are the names of the memcached pods    
Nodes []string `json:"nodes"`}
```

$ operator-sdk generate k8s
$ operator-sdk add controller --api-version=cache.example.com/v1alpha1 --kind=Memcached

replace the generated Controller file pkg/controller/memcached/memcached_controller.go with the example memcached_controller.go implementation provided in the guide: 
https://github.com/operator-framework/operator-sdk/blob/master/example/memcached-operator/memcached_controller.go.tmpl

$ sudo docker login
$ operator-sdk build docker.io/spanichella/memcached-operator-long
$ sed -i "" 's|REPLACE_IMAGE|docker.io/spanichella/memcached-operator-long|g' deploy/operator.yaml
#If you created your operator using --cluster-scoped=true, update the service account namespace in the generated ClusterRoleBinding to match where you are deploying your operator.
$ export OPERATOR_NAMESPACE=$(kubectl config view --minify -o jsonpath='{.contexts[0].context.namespace}')
$ sed -i "" 's|REPLACE_NAMESPACE|$OPERATOR_NAMESPACE|g' deploy/role_binding.yaml
# push it to a registry with Docker:
$ docker push docker.io/spanichella/memcached-operator-long

$ kubectl create -f deploy/crds/cache_v1alpha1_memcached_crd.yaml 

$ kubectl create -f deploy/service_account.yaml
$ kubectl create -f deploy/role.yaml
$ kubectl create -f deploy/role_binding.yaml
$ kubectl create -f deploy/operator.yaml

#Then finally when I arrive at the point:

"Verify that the memcached-operator is up and running:
$ kubectl get deployment"

I see the following:

NAME DESIRED CURRENT UP-TO-DATE AVAILABLE AGE
memcached-operator-long 1 1 1 0 15h

"kubectl get pods
NAME READY STATUS RESTARTS AGE
memcached-operator-long-6b45cc5d84-dhtr2 0/1 CrashLoopBackOff 30 15h"

--




--



--

**Comment by spanichella** [comment] 2019-01-16 10:36
Attached you find the operator that I have generated and deployed:

https://www.dropbox.com/s/vq3tcnn5w94qiwv/memcached-operator-long.zip?dl=0

**Comment by LiliC** [comment] 2019-01-16 10:51
@spanichella It seems like your namespace field in the `deploy/role_binding.yaml` is not correct, the `sed` command or the setting of `OPERATOR_NAMESPACE` env variable seems to have failed there. It says currently `$OPERATOR_NAMESPACE `. You have to set the namespace you want there. See https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#operator-scope and https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#1-run-as-a-deployment-inside-the-cluster

**Comment by spanichella** [comment] 2019-01-16 12:38
You are right I have not noticed "Set the subject namespace to REPLACE_NAMESPACE. This must be changed to the namespace in which the operator is deployed". 

It was maybe not clear how to do it, I have replaced the line
"$ export OPERATOR_NAMESPACE=$(kubectl config view --minify -o jsonpath='{.contexts[0].context.namespace}')
$ sed -i "" 's|REPLACE_NAMESPACE|$OPERATOR_NAMESPACE|g' deploy/role_binding.yaml"

#check namespaces with 
$ kubectl get namespaces 
#then set the correct namespace (in my case it was "blogpost-project")
$ export OPERATOR_NAMESPACE=blogpost-project
$ sed -i "" 's|REPLACE_NAMESPACE|blogpost-project|g' deploy/role_binding.yaml #check if it worked correctly, otherwise set it manually...
# push it to a registry with Docker:
$ docker push   <docker id>/memcached-operator-long:v.0.0.1 
#(e.g., docker push docker.io/spanichella/memcached-operator-long)

Maybe one idea could be to update the description in the guide
https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#1-run-as-a-deployment-inside-the-cluster

Thanks @LiliC 👍

**Comment by spanichella** [comment] 2019-01-30 13:47
@LiliC You can download my operator from here https://www.dropbox.com/s/1lrqa2cnrxqn9np/memcached-operator-ansible.zip?dl=0 

I noticed that when running my operator I get some errors as you can see:
:

$ kubectl get pods
example-memcachedansible-memcachedansible-5c896748d9-7vk79   0/1       CrashLoopBackOff    6          6m
example-memcachedansible-memcachedansible-5c896748d9-kwqsw   0/1       CrashLoopBackOff    6          6m
example-memcachedansible-memcachedansible-5c896748d9-pvqsr   0/1       CrashLoopBackOff    6          6m
example-memcachedansible-memcachedansible-5c896748d9-vlpws   0/1       RunContainerError   0          5s
memcached-operator-ansible-d45fd455f-mmjbw                   1/1       Running             0          14m


$ kubectl get deployment
NAME                                        DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
example-memcachedansible-memcachedansible   4         4         4            0           33m
memcached-operator-ansible                  1         1         1            1           41m

What could be the problem?

Cheers,
Sebastiano

**Comment by LiliC** [comment] 2019-01-30 15:06
@spanichella Hello, can you see what the logs say. Can you do `kubectl logs deployment/memcached-operator-ansible ` and `kubectl get events`

**Comment by spanichella** [comment] 2019-01-30 15:12
@LiliC you find them here https://www.dropbox.com/s/ercy39wlmipu3fg/Logs-kubectl.zip?dl=0 
Thanks for the help.

**Comment by LiliC** [comment] 2019-01-31 09:06
@spanichella Could it be possible to paste the content of that in a https://gist.github.com instead of a download link :) Thanks!

**Comment by spanichella** [comment] 2019-01-31 16:56
Sorry @LiliC , I'm not frequent with Issues on GitHub, and I really appreciate your help.

Thanks for pointing me out "https://gist.github.com ". :)

Created the two files there:

https://gist.github.com/spanichella/255056c6a6bd9d71818616c4b2e5515b
https://gist.github.com/spanichella/59d0a957ecf00e7ef1066d689714b8d8

Sebastiano

**Comment by LiliC** [comment] 2019-01-31 17:08
@spanichella No worries, thanks for that!

Seems like the operator binary is not found in the container
```
"exec: \"memcachedansible\": executable file not found in $PATH"
```

https://gist.github.com/spanichella/59d0a957ecf00e7ef1066d689714b8d8#file-log_events-txt-L12

**Comment by spanichella** [comment] 2019-01-31 18:07
I tried to build and push again the operator, but still the same problem.

I found also a bit strange in the log and the pods the naming " example-memcachedansible-memcachedansible".

In any case, I'm not sure how to proceed, sorry.
Do I have to check if the in the "$PATH" of my local machine the executable file is there?

**Comment by LiliC** [comment] 2019-02-01 10:51
@spanichella can you provide details on how you built the operator. The problem seems to be at least judging by the logs the binary is missing from the container.

https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md#build-and-run-the-operator

**Comment by spanichella** [comment] 2019-02-04 09:16
Dear @LiliC , Attached you find a pdf of the process followed to build the operator.

It is very detailed
[Ansible operator.pdf](https://github.com/operator-framework/operator-sdk/files/2827186/Ansible.operator.pdf)
 so that you can get how I did build it.

Cheers,
Sebastiano

**Comment by shawn-hurley** [comment] 2019-02-04 13:23
@spanichella 

The problem appears that you update the tasks/main.yml to use the command `memcachedansible` with is not the correct command, if you change this to `memchached` then this works. 

Closing as I was able to reproduce locally and also fix the problem with this change. Please re-open if this is still a bug

**Closed by shawn-hurley** 2019-02-04 13:23 UTC
Labels: ansible-operator
