### ISSUE TITLE
"operator-sdk run local" not present in 1.1.0

### ISSUE THREAD

**Issue by kubealex** [operator-framework/operator-sdk#4158] opened 2020-11-01 18:14 UTC
#### What did you do?

Follow the documentation for Helm Operator Tutorial, and try to run a local instance of the operator locally. 
#### What did you expect to see?

Command operator-sdk run local --kubeconfig=<path_to_config> working as expected

#### What did you see instead? Under which circumstances?

operator-sdk run local --kubeconfig=kubeconfig
Error: unknown flag: --kubeconfig
Usage:
  operator-sdk run [command]

Available Commands:
  bundle           Deploy an Operator in the bundle format with OLM
  packagemanifests Deploy an Operator in the package manifests format with OLM

Flags:
  -h, --help   help for run

Global Flags:
      --verbose   Enable verbose logging

Use "operator-sdk run [command] --help" for more information about a command.

#### Environment

**Operator type:**

/language helm

**Kubernetes cluster type:**

Kind

`$ operator-sdk version`

alessandro@MBPdiAlessandro mediaserver-operator % operator-sdk version
operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15.2 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"

`$ kubectl version`

alessandro@MBPdiAlessandro mediaserver-operator % kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution

Implement the 'run local' command

**Comment by camilamacedo86** [comment] 2020-11-01 19:34
HI @kubealex, 

It is not a bug. The `operator run local` is no longer supported. For the version +1.0 (new layout) the projects are created with a Makefile where users are able to create the target `make run` which has the same purpose. See the e.g https://github.com/operator-framework/operator-sdk/blob/master/testdata/helm/memcached-operator/Makefile#L20-L21

In this way, I'd like to recommend you use the `make run` instead. 

I am closing it as sort out, however, feel free to ping us if you think that it should be re-opened.

**Closed by camilamacedo86** 2020-11-01 19:34 UTC
Labels: language/helm

**Comment by kubealex** [comment] 2020-11-01 19:51
Completely fine, I opened a pull request to update the documentation, since it is in 1.1 docs.
