### ISSUE TITLE
Not able to run `make install run` with go version 1.19 and operator version 1.28

### ISSUE THREAD

**Issue by kavyamani596** [operator-framework/operator-sdk#6418] opened 2023-05-04 05:48 UTC
#### What did you do?

Tried running the operator using make install run

#### What did you expect to see?

Operator should come up, should see logs of operator

#### What did you see instead? Under which circumstances?

/home/bruce/go/src/deploy/server-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/bruce/go/src/deploy/server-operator/bin/kustomize build config/crd | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/biosschemaregistries.infra.io.odimra configured
customresourcedefinition.apiextensions.k8s.io/biossettings.infra.io.odimra configured
customresourcedefinition.apiextensions.k8s.io/bmcs.infra.io.odimra configured
customresourcedefinition.apiextensions.k8s.io/bootordersettings.infra.io.odimra configured
customresourcedefinition.apiextensions.k8s.io/odims.infra.io.odimra configured
customresourcedefinition.apiextensions.k8s.io/rulebasedaggregates.infra.io.odimra configured
customresourcedefinition.apiextensions.k8s.io/volumes.infra.io.odimra configured
/home/bruce/go/src/deploy/server-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/usr/local/go/src/sync/atomic/type.go:39:16: expected ']', found any
/usr/local/go/src/sync/atomic/type.go:39:19: expected ';', found ']'
/usr/local/go/src/sync/atomic/type.go:39:19: expected type, found ']'
/usr/local/go/src/sync/atomic/type.go:50:34: expected declaration, found 'return'
/usr/local/go/src/sync/atomic/type.go:39:16: expected ']', found any
/usr/local/go/src/sync/atomic/type.go:39:19: expected ';', found ']'
/usr/local/go/src/sync/atomic/type.go:39:19: expected type, found ']'
/usr/local/go/src/sync/atomic/type.go:50:34: expected declaration, found 'return'
/usr/local/go/src/sync/atomic/type.go:39:16: expected ']', found any
/usr/local/go/src/sync/atomic/type.go:39:19: expected ';', found ']'
/usr/local/go/src/sync/atomic/type.go:39:19: expected type, found ']'
/usr/local/go/src/sync/atomic/type.go:50:34: expected declaration, found 'return'
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make: *** [Makefile:100: generate] Error 1

#### Environment

`$ operator-sdk version`
  operator-sdk version: "v1.28.0-5-gaf140625", commit: "af14062577914e4c79c77d8a31d2cf808e5ed76b", kubernetes version: "v1.26.0", go version: "go1.19.5", GOOS: "linux", GOARCH: "amd64"

Also saw an inconsistency in the documentation for 1.28 release
The version of go for 1.28 is different in each of these links:
      1.https://v1-28-x.sdk.operatorframework.io/docs/installation/
      2.https://v1-28-x.sdk.operatorframework.io/docs/building-operators/golang/installation/

**Comment by varshaprasad96** [comment] 2023-05-08 18:30
@kavyamani596 Could you provide a link to your project? This seems to be coming from controller-tools, @OchiengEd can help in looking into this issue.

**Comment by kavyamani596** [comment] 2023-05-09 04:06
hi @varshaprasad96 , yep , it was due to the old version of controller-gen executable.
I updated the controller-gen version to the latest, i.e 11.1 and it worked for go 19.5
but this is not mentioned in the operator documentation, it would be helpful if this is documented cause we took lot of time to arrive at this.

**Comment by OchiengEd** [comment] 2023-05-09 05:09
Thanks for the update; I am glad you were able to identify the root cause of the issue.

**Comment by OchiengEd** [comment] 2023-05-11 06:02
@kavyamani596 I have changed the milestone to `v1.30.0`. I will try to get some eyes on this as well.

**Comment by varshaprasad96** [comment] 2023-05-22 18:40
Closing this issue, since an unsupported version of controller tools was being used.

**Closed by varshaprasad96** 2023-05-22 18:40 UTC

**Comment by hassanahtasham** [comment] 2024-07-23 22:28
I am also facing the same kind of issue, can anyone from here, help me?

I have controller-gen version of v0.12.0 on my machine, but while compilation I can see v0.80. I dont understand why its happening. Same with the go, on my system it shows 1.22.5 but on VS code it shows, 1.17.6

I am in trouble, please help

Error: not all generators ran successfully run controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... #6789
