### ISSUE TITLE
Failed to list *v1.ServiceMonitor: v1.ListOptions is not suitable for converting to "monitoring.coreos.com/v1"

### ISSUE THREAD

**Issue by jpkrohling** [operator-framework/operator-sdk#1927] opened 2019-09-17 13:18 UTC
## Bug Report

When trying to `Get` an instance of a `ServiceMonitor`, the following is seen on the logs every second:

```
E0917 14:23:29.341637    6838 reflector.go:134] pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/tools/cache/reflector.go:95: Failed to list *v1.ServiceMonitor: v1.ListOptions is not suitable for converting to "monitoring.coreos.com/v1" in scheme "pkg/runtime/scheme.go:101"
```

**What did you do?**
1. Install the Prometheus Operator
1. Install a Prometheus CR, like:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
```
3. Run `make run-debug` from the branch: https://github.com/jpkrohling/opentelemetry-operator/tree/Add-Service-Monitor
1. Run `kubectl apply -f https://raw.githubusercontent.com/jpkrohling/opentelemetry-operator/Add-Service-Monitor/examples/simplest.yaml`

This the code that attempts to retrieve the service monitors and that triggers the error:
```go
existing := &monitoringv1.ServiceMonitor{}
err := r.client.Get(ctx, types.NamespacedName{Name: desired.Name, Namespace: desired.Namespace}, existing)
```

Note that the code never returns from the `Get` call, even when explicitly setting a `context.WithTimeout(time.Second)`.

**Environment**
* operator-sdk version: `v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170`
* go version: `go1.12.9 linux/amd64`
* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-12-06T15:15:06Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind:  `minikube`
* Are you writing your operator in ~ansible, helm,~ or go?

**Possible Solution**
Use the rest client from the monitoring package (`github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1`) instead of the client from the controller-runtime package (`sigs.k8s.io/controller-runtime/pkg/client`) sounds like a possible solution, but I'm yet to try that out. If that's the official workaround, the question is then: should we start using `rest.Client` (`k8s.io/client-go/rest`) everywhere instead of `controller-runtime`'s client?

**Comment by shawn-hurley** [comment] 2019-09-17 14:07
https://github.com/kubernetes-sigs/controller-runtime/pull/580

I am actively attempting to fix the timeout issue.

**Comment by jpkrohling** [comment] 2019-09-24 10:43
Any news on this? I wanted to clarify whether a fix for this is planned for the next release, or if I should invest some time in a workaround.

**Comment by jpkrohling** [comment] 2019-10-02 12:44
Is there any recommendation at all about a workaround?

**Comment by jpkrohling** [comment] 2019-10-11 11:29
I decided to not use the `controller-runtime`'s client and I'm moving to the client-go REST. Therefore, feel free to close this.

It would have been nice to get an official guidance from the Operator SDK team, though.

**Comment by camilamacedo86** [comment] 2019-10-15 11:28
Hi @jpkrohling,

By checking the description over what you did I am not sure if this is the correct steps.  Following the details and further information. I am not able to create a POC to help you with now (it would take a while), but following the steps which I would perform.  

- Install the Prometheus Operator: https://github.com/coreos/kube-prometheus
- Create the Memcached Getting Started POC example: https://github.com/operator-framework/getting-started using the latest version 0.11.0
NOTE: Ensure that you apply the RBCA roles and files with the admin user
- Ensure that the project in the main.go has the required impl to create the Service and MonitorService for the operator as for example [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/cmd/manager/main.go#L126)
- Then, install all in the Minikube and ensure that is all running with success. 
- After that I'd ensure that the `kubectl get ServiceMonitor -n <name>` and service for the operator deployment are created successfully.
- Then to check it, I would impl as the following GET example in the Reconcile to get the ServiceMonitor created. 

```go  
         import (
               monitoringv1 "github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1"
         )

         ...
	serviceMonitor := &monitoringv1.ServiceMonitor{}
	err = r.client.Get(context.TODO(), types.NamespacedName{Name: memcached.Name, Namespace: <name of the service monitor found by `kubectl get ServiceMonitor -n <name>`>}, service)
	....
	} else if err != nil {
		reqLogger.Error(err, "Failed to get Service.")
		return reconcile.Result{}, err
	}
```

So, It probably will not work and may face the issue described here since the schema was not added in the project which would confirm that the issue is because we need to add the schema as described [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#register-with-the-managers-scheme). 

I hope that it helps you with.

**Comment by camilamacedo86** [comment] 2020-03-10 11:57
Hi @jpkrohling,

I am closing this one since we are unable to reproduce this scenario as you can check in the comment https://github.com/operator-framework/operator-sdk/issues/1927#issuecomment-542166779 made at 15 Oct 2019 and no further information was sent for we are able to check it. 

However, please feel free to raise a new issue if you sill needing helping with.

**Closed by camilamacedo86** 2020-03-10 11:57 UTC
Labels: kind/bug, lifecycle/rotten, triage/needs-information
