### ISSUE TITLE
Operator Configmap Changes --> reconcile all crs

### ISSUE THREAD

**Issue by petro404** [operator-framework/operator-sdk#2610] opened 2020-02-28 15:15 UTC
Hi,

I would like to know if is there a way to trigger a reconcile of all the custom resources due to change if the operator configmap
Today i am using helm checksum annotation in the configmap and in case the configmap is changed the annotation is updated and the operator is restarted.

I would like to know if there is way to perform the same logic without using helm so I can watch to configmap my-operator-config-map (watch is easy to be done ) but my question how can i trigger reconcile of all the CRs?

Thanks

**Comment by camilamacedo86** [comment] 2020-03-04 14:40
Hi @petro404,

See that the watch feature does it for you. It will re-trigger the reconcile when something change for some specific object. See its section in the [user guide ](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#resources-watched-by-the-controller) for Go operators. 

So, could you please let us know:
- Did you try to use the watch feature?
- What type of operator are you working with?
- What do you mean with `operator configmap`? Is the config map created/managed by the operator? If yes, why would like to do it? I mean, what is the scenario that you are trying to solve with?

**Comment by petro404** [comment] 2020-03-07 08:36
Hi @camilamacedo86 
I am aware of the watch feature and I am already using it, my use case is the following:

**Comment by camilamacedo86** [comment] 2020-03-09 14:26
Hi @petro404,

Following my comments inline.

> my question if i got an event of configmp change how can start reconcile all the CR's
> even the event that i got is not on the Cr'S
 
All reconciles that should be re-trigged by a change in a resource would need to have the watch feature implemented on it. See that you can use the watch feature for resources which are/or not directly managed by the specific controller. 

Please, let me know if it answers your question and if we can close this one.

**Comment by camilamacedo86** [comment] 2020-03-10 11:53
Hi @petro404, 

I am closing this once since all shows sorted out.  However, please feel free to raise new issues with your questions, and your bugs as feature requests. 

Also, I'd like to kindly ask for you try fill all the issue template as to provide the required information for we are able to reproduce and check your scenario such as; steps to create a POC based on the sample or getting started scenario, logs and snippets of code for example.

**Closed by camilamacedo86** 2020-03-10 11:53 UTC
Labels: triage/needs-information, triage/support
