### ISSUE TITLE
The ` operator-sdk bundle validate` command should work with the default dir

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2877] opened 2020-04-22 16:47 UTC
## Bug Report

**What did you do?**

Run the command: 

```
$ operator-sdk bundle create --generate-only
INFO[0000] Building annotations.yaml                    
INFO[0000] Generating output manifests directory        
INFO[0000] Building Dockerfile    
```                      

Then I run the command `operator-sdk bundle validate`

**What did you expect to see?**
The validate works successfully by checking the data generated in the default dir.

**What did you see instead? Under which circumstances?**

> Error: error validating args: an image tag or directory is a required argument

**Environment**
* operator-sdk version: 0.17
* go version: 1.13

**Possible Solution**
Use the same logic to gen the dir to get it.

**Comment by joelanford** [comment] 2020-04-22 17:00
@camilamacedo86 This seems more like a feature request than a bug report. The feature being "add a default bundle directory location"

IMO, the design of the `bundle validate` CLI is intuitive, straightforward, and flexible. This command is intentionally designed to be standalone and not require a project since it can take an arbitrary directory or image reference. This design allows it to be used in pipeline scenarios where a bundle image or directory is present, but not an entire project.

**Comment by joelanford** [comment] 2020-04-22 20:53
@estroz Do you think we should close this as "Working as designed"?

**Comment by estroz** [comment] 2020-04-22 21:58
@joelanford yes.

**Closed by estroz** 2020-04-22 21:58 UTC
Labels: kind/bug, olm-catalog

**Comment by camilamacedo86** [comment] 2020-04-23 10:34
HI @joelanford and @estroz, 

I do not think that we should close this one. See that as I user would be expected to have a concise behaviour in the commands. I agree that it can be changed to RFE, however, I would expected use the bundle create and validate commands in the same way which do NOT mean change the default behaviour required for the pipeline. 

IHMO: The solution here would be: 

if the flag directory is empty then use the default dir instead of make it mandatory. 

Is it make sense?

**Comment by estroz** [comment] 2020-04-23 16:15
I would say defaulting the directory for `operator-sdk bundle validate` would be ok _if_ it were always validating a directory. However you can validate either and image or directory. Unless we have a way to provide a default image tag, which we cannot, we should not set either to defaults.

**Comment by camilamacedo86** [comment] 2020-04-23 16:20
I did not think about the image possibility. It is true. You are right whiteout the image and/or dir info we are unable to check what should be validated. Fair enough.
