### ISSUE TITLE
how to update operator with operator-sdk 

### ISSUE THREAD

**Issue by shimron** [operator-framework/operator-sdk#4101] opened 2020-10-26 11:38 UTC
## Type of question

Best practices 

#### What did you do?

I have already installed an operator with the  command "operator-sdk run bundle" , 

but doesn't know how to update this operator with a newer version.
 
Trying to install a newer version bundle with "operator-sdk run bundle", cause a fata error.

#### What did you expect to see?

operator updated 

#### What did you see instead? Under which circumstances?

```
operator-sdk run bundle {host}zhenjin-operator-bundle:0.0.2 -n operators
FATA[0009] Failed to run bundle: create catalog: error creating catalog source: catalogsources.operators.coreos.com "zhenjin-operator-catalog" already exists
```

#### Environment

**Operator type:**

**Kubernetes cluster type:**

tencent kubernetes engine

`$ operator-sdk version`

operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15 linux/amd64", GOOS: "linux", GOARCH: "amd64"

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.3-tke.16", GitCommit:"9371d4d740b11d5a83f14010ac8e5735e7c2803e", GitTreeState:"clean", BuildDate:"2020-08-03T03:38:09Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.3-tke.10", GitCommit:"02a1f2c1ac7af926ad01a8f70a8123107afdc56f", GitTreeState:"clean", BuildDate:"2020-07-22T07:30:52Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rashmigottipati** [comment] 2020-10-27 03:43
Hello @shimron, thanks for raising this issue. By design, run bundle command is not intended for operator upgrades. It is only meant for installing a particular version of an operator. We will be adding a new feature to perform/test operator upgrades. Here's the link to the enhancement proposal: [run bundle-upgrade](https://github.com/operator-framework/enhancements/blob/master/enhancements/run-bundle-upgrade.md)

For the time-being, you can get past this error by performing cleanup of the operator bundle using `operator-sdk cleanup <operatorName>` and using the `operator-sdk run bundle <bundleImage>` command with the newer operator version that you intended to install. Hope that helps.

**Comment by shimron** [comment] 2020-10-27 03:52
@rashmigottipati  As I know, cleanup will also delete the CRs,  this is unacceptable in production environment.  Is there another way to perform the update ?

**Comment by shimron** [comment] 2020-10-27 08:22
When will bundle-upgrade be available? Any release plan for it ?

**Comment by estroz** [comment] 2020-10-27 14:51
Closing in favor of #3070.

**Closed by estroz** 2020-10-27 14:51 UTC
