### ISSUE TITLE
Operator instance status and version status  are  shown UNKNOWN even after the successfull deployment.

### ISSUE THREAD

**Issue by AnilKumarBandi27** [operator-framework/operator-sdk#3308] opened 2020-06-29 07:17 UTC
My Operator instance and version status is shown unknown even after the successful deployment. Please let me know how to update the status and version filed of instance.

Thanks in Advance.
![image](https://user-images.githubusercontent.com/40137206/85984302-a213d400-ba06-11ea-955f-c82d7746a5f4.png)

**Comment by camilamacedo86** [comment] 2020-06-29 08:31
Hi @AnilKumarBandi27,

Shows that all worked fine. Note that the info is describing that has no status to show in the Kind database. So, if in this scenario a status should appear then it is in the implementation of the is operator project and not in the SDK tool. In this way, if your questions are related to the expected behaviours of this project please try to contact its maintainers. 

However, if you are looking for help to understand better how [OLM](https://github.com/operator-framework/operator-lifecycle-manager) works and what would be the good practices to work with it then, could you please raise your questions in this repo? 

I am closing this one since shows have no relation with the SDK tool project.

**Closed by camilamacedo86** 2020-06-29 08:31 UTC
Labels: triage/support
