### ISSUE TITLE
Problem during "make install"

### ISSUE THREAD

**Issue by heydenb** [operator-framework/operator-sdk#718] opened 2018-11-08 12:08 UTC
## Bug Report

Problem during "make install"

`myuser@mymachine ~/.go/src/github.com/operator-framework/operator-sdk $ make install`
`# github.com/operator-framework/operator-sdk/internal/util/projutil`
`internal/util/projutil/project_util.go:37: syntax error: unexpected = in type declaration`
`# github.com/operator-framework/operator-sdk/vendor/go.uber.org/zap`
`vendor/go.uber.org/zap/field.go:33: syntax error: unexpected = in type declaration`
`# github.com/operator-framework/operator-sdk/vendor/github.com/pborman/uuid`
`vendor/github.com/pborman/uuid/time.go:15: syntax error: unexpected = in type declaration`
`# github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/client`
`vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go:31: syntax error: unexpected = in type declaration`
`make: *** [install] Error 2`

**Comment by shawn-hurley** [comment] 2018-11-08 15:01
What is the version of golang that you using? I suspect that you are something less than 1.9 which is needed for type alias.

**Comment by heydenb** [comment] 2018-11-08 17:00
Yes. 1.8. I will try to update.

Op do 8 nov. 2018 16:01 schreef Shawn Hurley <notifications@github.com>:

**Comment by estroz** [comment] 2018-11-08 17:48
Closing, as this issue is caused by Golang versioning.

**Closed by estroz** 2018-11-08 17:48 UTC
