### ISSUE TITLE
Helm chart controller-runtime.controller Reconciler error for empty manifest

### ISSUE THREAD

**Issue by depohmel** [operator-framework/operator-sdk#2815] opened 2020-04-09 18:49 UTC
## Bug Report

similar to https://github.com/operator-framework/operator-sdk/issues/2622  

**What did you do?**
```operator-sdk new test-operator --api-version=test.test.io/v1alpha1 --type=helm --kind=Test --helm-chart=path_to_repo```

```
kubectl apply -f  deploy/crds/test.test.io_v1alpha1_test_cr.yaml 
```

**What did you expect to see?**
no errors 

**What did you see instead? Under which circumstances?**
I see a Reconciler in operator errors
```
2020-04-09T17:31:30.136Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "k10-controller", "request": "kasten/k10", "error": "Operation cannot be fulfilled on k10s.apik10.kasten.io \"k10\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
	/repo/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/repo/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/repo/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/repo/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/repo/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/repo/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/repo/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88
```

**Environment**
* operator-sdk version:
```
operator-sdk version: "v0.15.0-162-g2d94d237", commit: "2d94d2371f6a29748338438beae0be00fa30a738", kubernetes version: "v1.17.2", go version: "go1.14.2 linux/amd64"
```

* go version:
```
go version go1.14.2 linux/amd64
```

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"94e669a", GitTreeState:"clean", BuildDate:"2020-02-03T23:11:39Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

OCP 4.3

* Are you writing your operator in ansible, helm, or go?
helm

**Possible Solution**

@bharathi-tenneti has fixed the original issue and might know how to fix this one too :)

**Comment by joelanford** [comment] 2020-04-09 18:55
It sounds like there's a `409 Conflict` error being returned by the API server.

Can you provide more context around these errors?
- After you apply the CR, is the operator installing the release successfully the first time through?
- If so, do any of the subsequent reconciles succeed before you see this log message?
- Is there anything _OTHER_ than just applying the CR that you need to do to trigger that error?

**Comment by depohmel** [comment] 2020-04-09 19:06
@joelanford 
here are the logs from operator 
```
2020-04-09T00:28:18.227Z        DEBUG   predicates      Skipping reconciliation for dependent resource creation {"name": "aggregatedapis-svc", "namespace": "kasten", "apiVersion": "apps/v1", "kind": "Deployment"}
2020-04-09T00:28:18.234Z        INFO    helm.controller Cannot watch cluster-scoped dependent resource for namespace-scoped owner. Changes to this dependent resource type will not be reconciled       {"ownerApiVersion": "apik10.kasten.io/v1alpha1", "ownerKind": "K10", "apiVersion": "apiregistration.k8s.io/v1beta1", "kind": "APIService"}
2020-04-09T00:28:18.235Z        INFO    helm.controller Cannot watch cluster-scoped dependent resource for namespace-scoped owner. Changes to this dependent resource type will not be reconciled       {"ownerApiVersion": "apik10.kasten.io/v1alpha1", "ownerKind": "K10", "apiVersion": "security.openshift.io/v1", "kind": "SecurityContextConstraints"}
2020-04-09T00:28:18.235Z        INFO    helm.controller Installed release       {"namespace": "kasten", "name": "k10", "apiVersion": "apik10.kasten.io/v1alpha1", "kind": "K10", "release": "k10"}

prints fully rendered chart

+  - system:serviceaccount:kasten:prometheus-server
ESC[0m
2020-04-09T00:28:18.289Z        DEBUG   helm.controller Reconciling     {"namespace": "kasten", "name": "k10", "apiVersion": "apik10.kasten.io/v1alpha1", "kind": "K10"}
E0409 00:28:19.413108       1 memcache.go:199] couldn't get resource list for actions.kio.kasten.io/v1alpha1: the server is currently unable to handle the request
E0409 00:28:19.462782       1 memcache.go:199] couldn't get resource list for apps.kio.kasten.io/v1alpha1: the server is currently unable to handle the request
E0409 00:28:19.512851       1 memcache.go:199] couldn't get resource list for vault.kio.kasten.io/v1alpha1: the server is currently unable to handle the request
E0409 00:28:21.162630       1 memcache.go:111] couldn't get resource list for actions.kio.kasten.io/v1alpha1: the server is currently unable to handle the request
E0409 00:28:21.212558       1 memcache.go:111] couldn't get resource list for apps.kio.kasten.io/v1alpha1: the server is currently unable to handle the request
E0409 00:28:21.262713       1 memcache.go:111] couldn't get resource list for vault.kio.kasten.io/v1alpha1: the server is currently unable to handle the request
2020-04-09T00:28:21.935Z        DEBUG   predicates      Skipping reconciliation for dependent resource creation {"name": "sh.helm.release.v1.k10.v2", "namespace": "kasten", "apiVersion": "v1", "kind": "Secret"}
2020-04-09T00:28:22.017Z        DEBUG   predicates      Reconciling due to dependent resource update    {"name": "allow-external", "namespace": "kasten", "apiVersion": "networking.k8s.io/v1", "kind": "NetworkPolicy"}
2020-04-09T00:28:22.113Z        DEBUG   predicates      Reconciling due to dependent resource update    {"name": "k10-api-key", "namespace": "kasten", "apiVersion": "v1", "kind": "Secret"}
2020-04-09T00:28:22.172Z        DEBUG   predicates      Reconciling due to dependent resource update    {"name": "k10-config", "namespace": "kasten", "apiVersion": "v1", "kind": "ConfigMap"}
2020-04-09T00:28:22.774Z        DEBUG   predicates      Reconciling due to dependent resource update    {"name": "auth-svc", "namespace": "kasten", "apiVersion": "apps/v1", "kind": "Deployment"}
2020-04-09T00:28:23.208Z        DEBUG   predicates      Reconciling due to dependent resource update    {"name": "sh.helm.release.v1.k10.v1", "namespace": "kasten", "apiVersion": "v1", "kind": "Secret"}
2020-04-09T00:28:23.234Z        DEBUG   predicates      Reconciling due to dependent resource update    {"name": "sh.helm.release.v1.k10.v2", "namespace": "kasten", "apiVersion": "v1", "kind": "Secret"}
2020-04-09T00:28:23.246Z        INFO    helm.controller Updated release {"namespace": "kasten", "name": "k10", "apiVersion": "apik10.kasten.io/v1alpha1", "kind": "K10", "release": "k10"}

fully rendered template again 


2020-04-09T00:28:23.271Z        ERROR   controller-runtime.controller   Reconciler error        {"controller": "k10-controller", "request": "kasten/k10", "error": "Operation cannot be fulfilled on k10s.apik10.kasten.io \"k10\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
        /repo/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /repo/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /repo/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /repo/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /repo/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /repo/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        /repo/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88
2020-04-09T00:28:24.271Z        DEBUG   helm.controller Reconciling     {"namespace": "kasten", "name": "k10", "apiVersion": "apik10.kasten.io/v1alpha1", "kind": "K10"}
```
So as you can see it installed chart, but API services not reasy (pods are not up yet)
After this it goes into never ending loop of reconciling errors.

**Comment by joelanford** [comment] 2020-04-15 21:15
I tested this out and it looks like the never-ending loop is actually caused by constant release upgrades. See #1531.

I closed #1531 because I could never reproduce the issue, so thanks for inadvertently providing a reproduction! :)

The helm-operator code is comparing a candidate release manifest with the currently deployed manifest to see if an upgrade needs to happen. Right now that comparison is a string comparison (based on the assumption that the manifest sort order is deterministic and stable)

To me, it seems like Helm thinks it is doing a [deterministic stable sort](https://github.com/helm/helm/blob/07675392790aa2fdad519d69dea030e566dcf9b5/pkg/releaseutil/kind_sorter.go#L109-L115).

I was able to reduce the k10 chart to just these template files and still reproduce:
```
$ tree templates
templates
├── apiservice.yaml
├── _definitions.tpl
└── _helpers.tpl
```

So the next question in my mind is whether the k10 chart templates are introducing the non-determinism or whether the Helm sorting is.

I'm not sure if this will solve the error messages you're seeing, but we clearly need to solve this indefinite reconciliation problem regardless.

**Comment by joelanford** [comment] 2020-04-20 02:36
@depohmel Can you try upgrading your helm-operator base image to v0.17.0, and let me know if that resolves the problem. See https://github.com/operator-framework/operator-sdk/issues/1531#issuecomment-616275726 for details about what I think was going on.

I'm not positive the indefinite upgrading is causing the original issue, but it seems like it could be related.

**Comment by joelanford** [comment] 2020-05-19 21:32
@depohmel Closing this one since I think it may be solved by upgrading your operator's base image to v0.17. If that doesn't solve your issue, please open a new issue with the logs from a 0.17-based operator and we can keep debugging!

**Closed by joelanford** 2020-05-19 21:32 UTC
Labels: helm-operator, priority/awaiting-more-evidence, triage/support

**Comment by AndreaGiardini** [comment] 2020-11-11 16:57
Hey @joelanford 

I think I am experiencing the same problem with the latest version of operator-sdk:
```
operator-sdk version
operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"
```

I created a helm operator of https://github.com/Requarks/wiki/tree/dev/dev/helm using:
```
operator-sdk init --plugins=helm --helm-chart=../wiki/dev/helm
--domain=org --group=wiki.js --version=v1alpha1 --kind=Wikijs
```
Then (on a kind cluster):
```
make install
k apply -f config/samples/wiki.js_v1alpha1_wikijs.yaml
make run
```

The operator seems stuck in an endless upgrade loop:
```
{"level":"error","ts":1605113721.097391,"logger":"controller","msg":"Reconciler error","controller":"wikijs-controller","name":"wikijs-sample","namespace":"default","error":"Operation cannot be fulfilled on wikijs.wiki.js.org \"wikijs-sample\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/joe/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/joe/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/joe/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/joe/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/joe/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/joe/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/joe/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/joe/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90"}
{"level":"debug","ts":1605113721.0974643,"logger":"helm.controller","msg":"Reconciling","namespace":"default","name":"wikijs-sample","apiVersion":"wiki.js.org/v1alpha1","kind":"Wikijs"}
{"level":"debug","ts":1605113721.1129947,"logger":"predicate","msg":"Reconciling due to dependent resource deletion","name":"sh.helm.release.v1.wikijs-sample.v42","namespace":"default","apiVersion":"v1","kind":"Secret"}
^C{"level":"info","ts":1605113721.3361776,"logger":"controller","msg":"Stopping workers","controller":"wikijs-controller"}
```

Looks like it is constantly trying to upgrade the Secret resource.
Any pointer in the right direction?
