### ISSUE TITLE
Scorecard does not wait for finalisers to complete before removing operator

### ISSUE THREAD

**Issue by oseoin** [operator-framework/operator-sdk#2094] opened 2019-10-23 14:39 UTC
## Bug Report

**What did you do?**
Created a simple Ansible Operator with SDK v0.11.0 to reproduce an issue we are seeing on our Ansible operators where finalisers do not complete within a few seconds. 

Using the following tasks:
```yaml
---
- name: "Set state of {{ meta.name }}-test-cfg"
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: "v1"
      kind: ConfigMap
      metadata:
        name: "{{ meta.name }}-test-cfg"
        namespace: "{{ meta.namespace }}"
      data:
        key: value

- name: test wait
  shell: sleep 10
```

Set a finaliser set in watches:
```yaml
- version: v1
  group: example.com
  kind: TestCr
  playbook: /opt/ansible/playbook.yml
  finalizer:
    name: example.com
    vars:
      state: absent
```

Used the following scorecard configuration:
```yaml
scorecard:
  plugins:
    - basic:
        olm-deployed: false
        cr-manifest:
          - "deploy/crds/icm.ibm.com_v1_testcr_cr.yaml"
        init-timeout: 300
```

**What did you expect to see?**
With the sleep task disabled I see the following as expected: 
```
operator-sdk scorecard --verbose   
DEBU[0000] Debug logging is set                         
INFO[0000] Using config file: /Users/oseoin/playground/kubernetes/operators/operator-test/.osdk-scorecard.yaml 
Basic Tests:
        Writing into CRs has an effect: 1/1
        Spec Block Exists: 1/1
        Status Block Exists: 1/1
```

**What did you see instead? Under which circumstances?**
Instead I get an error that cleanup does not complete:
```
operator-sdk scorecard --verbose       
DEBU[0000] Debug logging is set                         
INFO[0000] Using config file: /Users/oseoin/playground/kubernetes/operators/operator-test/.osdk-scorecard.yaml 
WARN[0044] time="2019-10-23T15:19:35+01:00" level=info msg="a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\n"
time="2019-10-23T15:19:45+01:00" level=info msg="a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\n"
time="2019-10-23T15:19:45+01:00" level=error msg="Failed to cleanup resources: (a cleanup function failed; see stdout for more details)" 
Basic Tests:
        Spec Block Exists: 1/1
        Status Block Exists: 1/1
        Writing into CRs has an effect: 1/1
```

Watching the operator deployment I can see that it gets removed before the finaliser completes.

**Environment**
* operator-sdk version:

operator-sdk version: "v0.11.0"
commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d"

* go version:
go version: "go1.13.1 darwin/amd64"

* Kubernetes version information:
```Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Docker desktop 2.1.4.0 on macOs 10.15

* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**
Scorecard should wait before removing the operator deployment if finalisers are set.

**Comment by camilamacedo86** [comment] 2019-10-23 22:46
Hi,

Thank you for raise it. I will try to reproduce it.

**Comment by camilamacedo86** [comment] 2019-10-24 16:18
Hi @oseoin,

Thank you for raise it. Could you please let us the following information?

1. Have you tried to increase the `init-timeout: 120`? See [doc](https://github.com/operator-framework/operator-sdk/blob/b964dd61a75948a56bf3bbaadaba453504f1170a/doc/test-framework/scorecard.md#olm-integration).
2.  Is this project public? Could you share it? 
3. What is the command that you have been used to call scorecard? Could you provide the .osdk-scorecard.yaml used? 
4. Have any information in the stdout? See `see stdout for more details`?

**Comment by mew2057** [comment] 2019-10-25 14:56
I'm hitting a similar problem as well (stdout doesn't show anything):


- [Repo](https://github.com/IBM/ibm-spectrum-scale-csi-operator/tree/dev
) 
- [Travis CI Run](https://travis-ci.org/mew2057/ibm-spectrum-scale-csi-operator/jobs/602840508)
- [Internal Issue](https://github.com/IBM/ibm-spectrum-scale-csi-operator/issues/34)


Scorecard command:
``` bash
# If I don't spec cr-manifest and csv-path it doesn't work.
GO111MODULE=on operator-sdk scorecard --config .osdk-scorecard.yaml --cr-manifest  deploy/crds/ibm_v1alpha1_csiscaleoperator_cr.yaml  --csv-path deploy/olm-catalog/ibm-spectrum-scale-csi-operator/0.0.1/ibm-spectrum-scale-csi-operator.v0.0.1.clusterserviceversion.yaml
```
`.osdk-scorecard.yaml`
``` YAML
scorecard:
  init-timeout: 120
  output: json
  plugins:
    - basic:
        cr-manifest:
            - "deploy/crds/ibm_v1alpha1_csiscaleoperator_cr.yaml"
    - olm:
        cr-manifest:
            - "deploy/crds/ibm_v1alpha1_csiscaleoperator_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-spectrum-scale-csi-operator/0.0.1/ibm-spectrum-scale-csi-operator.v0.0.1.clusterserviceversion.yaml"
```

**Comment by mew2057** [comment] 2019-10-25 16:41
I just did two configs of my `watches.yaml` and it looks like there's a pretty concrete connection in the finalizer to the scorecard failing. I ran both versions through travis and got the following results:


[Scorecard 100%](https://travis-ci.org/mew2057/ibm-spectrum-scale-csi-operator/jobs/602897757)
"Good" config:
```
---
- version: v1alpha1
  group: scale.ibm.com
  kind: CSIScaleOperator
  role: /opt/ansible/roles/csi-scale
  ManageStatus: True
```


---

[Scorecard 50%](https://travis-ci.org/mew2057/ibm-spectrum-scale-csi-operator/jobs/602904105)
"Bad" Config
```
---
- version: v1alpha1
  group: scale.ibm.com
  kind: CSIScaleOperator
  role: /opt/ansible/roles/csi-scale
  ManageStatus: True
  finalizer:
    name: finalizer.scale.ibm.com
    vars:
      state: absent
```

**Comment by camilamacedo86** [comment] 2019-10-25 18:36
Hi @mew2057, 

Really thank you for the great info provide. Could you just please do the following test? 

I just would like to isolate the scenario to know if it is a scorecard issue or a finalizer issue with ansible operator. Then, could you check it out of the scorecard? I mean, could you install all, then check that are all running and then, try to delete the objects to see if it will get stuck? 

See [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/memcached-operator/Makefile) a Makefile with the commands `make install` and `make uninstall` which can help you to do this test.

**Comment by camilamacedo86** [comment] 2019-10-25 20:42
Hi @mew2057, 

Also, checking your logs I notice that you are using python 2.

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

So, try to use Python3. Following how to add it in your .travis file. 
 
```yaml
# Python 3.6 is the default Python when language: python.
# But when not language: python, Python 3 can not be used by default.
# There is pip (/usr/bin/pip), but not pip3.
# Because of it the global env is required.
env:
  global:
    - PATH=/opt/python/3.6.7/bin:$PATH

# Install python3 and utilities dependencies
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip" 
```

It may can be the root cause since because of the deprecation we upgrade it to use Python3.

**Comment by mew2057** [comment] 2019-10-28 13:03
Makefile
----
For the `Makefile` it looks like the delete is a bit slow (~74 seconds), but that's probably the finalizer running when  the object gets removed. That should fit my `init-timeout: 120` in my `.osdk-scorecard.yaml` configuration.

`make install`
``` bash
$ time make install
....... Creating namespace .......
kubectl create namespace csiscaleoperator
namespace/csiscaleoperator created
....... Applying CRDS and Operator .......
kubectl apply -f deploy/crds/ibm_v1alpha1_csiscaleoperator_crd.yaml -n csiscaleoperator
customresourcedefinition.apiextensions.k8s.io/csiscaleoperators.scale.ibm.com created
....... Applying Rules and Service Account .......
kubectl apply -f deploy/role.yaml -n csiscaleoperator
role.rbac.authorization.k8s.io/ibm-spectrum-scale-csi-operator created
clusterrole.rbac.authorization.k8s.io/ibm-spectrum-scale-csi-operator created
clusterrole.rbac.authorization.k8s.io/csi-nodeplugin created
clusterrole.rbac.authorization.k8s.io/external-attacher-runner created
clusterrole.rbac.authorization.k8s.io/external-provisioner-runner created
kubectl apply -f deploy/role_binding.yaml  -n csiscaleoperator
rolebinding.rbac.authorization.k8s.io/ibm-spectrum-scale-csi-operator created
clusterrolebinding.rbac.authorization.k8s.io/ibm-spectrum-scale-csi-operator created
clusterrolebinding.rbac.authorization.k8s.io/csi-nodeplugin created
clusterrolebinding.rbac.authorization.k8s.io/external-provisioner-runner created
clusterrolebinding.rbac.authorization.k8s.io/external-attacher-runner created
kubectl apply -f deploy/service_account.yaml  -n csiscaleoperator
serviceaccount/ibm-spectrum-scale-csi-operator created
serviceaccount/external-attacher-runner created
serviceaccount/csi-nodeplugin created
serviceaccount/external-provisioner-runner created
....... Applying Operator .......
kubectl apply -f deploy/operator.yaml -n csiscaleoperator
deployment.apps/ibm-spectrum-scale-csi-operator created
....... Creating the Cluster .......
kubectl apply -f deploy/crds/ibm_v1alpha1_csiscaleoperator_cr.yaml -n csiscaleoperator
csiscaleoperator.scale.ibm.com/csi-scale-operator created

real	0m2.436s
user	0m1.427s
sys	0m0.227s
```

`make uninstall`
``` bash
time make uninstall
....... Uninstalling .......
....... Deleting CRDs.......
kubectl delete -f deploy/crds/ibm_v1alpha1_csiscaleoperator_crd.yaml -n csiscaleoperator
warning: deleting cluster-scoped resources, not scoped to the provided namespace
customresourcedefinition.apiextensions.k8s.io "csiscaleoperators.scale.ibm.com" deleted
....... Deleting Rules and Service Account .......
kubectl delete -f deploy/role.yaml -n csiscaleoperator
role.rbac.authorization.k8s.io "ibm-spectrum-scale-csi-operator" deleted
warning: deleting cluster-scoped resources, not scoped to the provided namespace
clusterrole.rbac.authorization.k8s.io "ibm-spectrum-scale-csi-operator" deleted
clusterrole.rbac.authorization.k8s.io "csi-nodeplugin" deleted
clusterrole.rbac.authorization.k8s.io "external-attacher-runner" deleted
clusterrole.rbac.authorization.k8s.io "external-provisioner-runner" deleted
kubectl delete -f deploy/role_binding.yaml -n csiscaleoperator
rolebinding.rbac.authorization.k8s.io "ibm-spectrum-scale-csi-operator" deleted
warning: deleting cluster-scoped resources, not scoped to the provided namespace
clusterrolebinding.rbac.authorization.k8s.io "ibm-spectrum-scale-csi-operator" deleted
clusterrolebinding.rbac.authorization.k8s.io "csi-nodeplugin" deleted
clusterrolebinding.rbac.authorization.k8s.io "external-provisioner-runner" deleted
clusterrolebinding.rbac.authorization.k8s.io "external-attacher-runner" deleted
kubectl delete -f deploy/service_account.yaml -n csiscaleoperator
serviceaccount "ibm-spectrum-scale-csi-operator" deleted
serviceaccount "external-attacher-runner" deleted
serviceaccount "csi-nodeplugin" deleted
serviceaccount "external-provisioner-runner" deleted
....... Deleting Operator .......
kubectl delete -f deploy/operator.yaml -n csiscaleoperator
deployment.apps "ibm-spectrum-scale-csi-operator" deleted
....... Deleting namespace csiscaleoperator.......
kubectl delete namespace csiscaleoperator
namespace "csiscaleoperator" deleted

real	1m14.311s
user	0m0.732s
sys	0m0.099s
```

Makefile (modified from example):
``` Makefile
[root ibm-spectrum-scale-csi-operator]# cat Makefile
.DEFAULT_GOAL:=help
SHELL:=/bin/bash
NAMESPACE=csiscaleoperator

# Modified from operator framework sample.
##@ Application

install: ## Install all resources (CR/CRD's, RBCA and Operator)
	@echo ....... Creating namespace .......
	- kubectl create namespace ${NAMESPACE}
	@echo ....... Applying CRDS and Operator .......
	- kubectl apply -f deploy/crds/ibm_v1alpha1_csiscaleoperator_crd.yaml -n ${NAMESPACE}
	@echo ....... Applying Rules and Service Account .......
	- kubectl apply -f deploy/role.yaml -n ${NAMESPACE}
	- kubectl apply -f deploy/role_binding.yaml  -n ${NAMESPACE}
	- kubectl apply -f deploy/service_account.yaml  -n ${NAMESPACE}
	@echo ....... Applying Operator .......
	- kubectl apply -f deploy/operator.yaml -n ${NAMESPACE}
	@echo ....... Creating the Cluster .......
	- kubectl apply -f deploy/crds/ibm_v1alpha1_csiscaleoperator_cr.yaml -n ${NAMESPACE}

uninstall: ## Uninstall all that all performed in the $ make install
	@echo ....... Uninstalling .......
	@echo ....... Deleting CRDs.......
	- kubectl delete -f deploy/crds/ibm_v1alpha1_csiscaleoperator_crd.yaml -n ${NAMESPACE}
	@echo ....... Deleting Rules and Service Account .......
	- kubectl delete -f deploy/role.yaml -n ${NAMESPACE}
	- kubectl delete -f deploy/role_binding.yaml -n ${NAMESPACE}
	- kubectl delete -f deploy/service_account.yaml -n ${NAMESPACE}
	@echo ....... Deleting Operator .......
	- kubectl delete -f deploy/operator.yaml -n ${NAMESPACE}
	@echo ....... Deleting namespace ${NAMESPACE}.......
	- kubectl delete namespace ${NAMESPACE}

.PHONY: help
help:  ## Display this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z0-9_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
```

Environment Change
---
I updated my config to match the recommendation and it still looks like I'm hitting the timeout on the resource cleanup: 

https://travis-ci.org/mew2057/ibm-spectrum-scale-csi-operator/jobs/603884581#L358

Thoughts
---
What the timeout is tripping on the delete because the timeout is not being properly loaded by the scorecard? If I don't run the scorecard with the `csv-path` in the variable list it errors out, maybe something similar is happening with the timeout? 

``` bash
$ operator-sdk scorecard --init-timeout 120 --config .osdk-scorecard.yaml --cr-manifest  deploy/crds/ibm_v1alpha1_csiscaleoperator_cr.yaml  --csv-path deploy/olm-catalog/ibm-spectrum-scale-csi-operator/0.0.1/ibm-spectrum-scale-csi-operator.v0.0.1.clusterserviceversion.yaml
INFO[0000] Using config file: .osdk-scorecard.yaml
WARN[0000] Plugin directory not found; skipping external plugins: stat scorecard: no such file or directory
WARN[0035] time="2019-10-28T06:02:14-07:00" level=info msg="a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\n"
time="2019-10-28T06:02:29-07:00" level=info msg="a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\n"
time="2019-10-28T06:02:29-07:00" level=error msg="Failed to cleanup resources: (a cleanup function failed; see stdout for more details)"
ERRO[0035] Plugin `olm-tests` failed with error (failed to create global resources: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "csiscaleoperators.scale.ibm.com" already exists)
Basic Tests:
	Spec Block Exists: 1/1
	Status Block Exists: 1/1
	Writing into CRs has an effect: 1/1
Failed Plugin: olm-tests:

Total Score: 50%
```

Apparently not.

**Comment by camilamacedo86** [comment] 2019-10-28 13:20
Hi @oseoin, 

Could you share your role.yaml file? Also, could you try to use the same permissions that we a check in the [samples](https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/memcached-operator/deploy/role.yaml)

**Comment by mew2057** [comment] 2019-10-28 21:03
Is this related to #1513? I've tried a lot of different configs (bumped to 0.11.0, verified the role was present and even dug through the scorecard logic) and I can't identify any other sources. 

Additionally, clearing the CR's finalizer will clear the CR and CRD 100% of the time after the scorecard fails.

**Comment by oseoin** [comment] 2019-10-29 09:12
Hi @camilamacedo86, apologies for the delay in getting back to you. I tested using `init-timeout: 300`. Our projects are not public but I have attached the test operator that I created to recreate the issue, which I have verified uses the same permissions as in the memcached sample. Unfortunately there is no other output in stdout, and the JSON output does not provide any additional information. I think that this has to be a scorecard issue rather than a permissions one as the finaliser works fine when run manually - unless scorecard uses permissions differently?
[operator-test.zip](https://github.com/operator-framework/operator-sdk/files/3782552/operator-test.zip).
Thanks!

**Comment by jmccormick2001** [comment] 2019-10-29 18:23
I played around this morning and was able to recreate your error I think...

jeffmc@doppio114 ~/projects/memcached-operator> operator-sdk scorecard -o text
INFO[0000] Using config file: /home/jeffmc/projects/memcached-operator/.osdk-scorecard.yaml 
WARN[0027] time="2019-10-29T13:14:52-05:00" level=info msg="a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\n"
time="2019-10-29T13:15:02-05:00" level=info msg="a cleanup function failed with error: cleanup function failed: timed out waiting for the condition\n"
time="2019-10-29T13:15:02-05:00" level=error msg="Failed to cleanup resources: (a cleanup function failed; see stdout for more details)" 
ERRO[0027] Plugin `OLM Integration` failed with error (failed to create global resources: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "memcacheds.cache.example.com" already exists) 
basic:
	Spec Block Exists                  : pass
	Status Block Exists                : pass
	Writing into CRs has an effect     : pass

I did this by artificially putting a Sleep of 75 seconds in the finalizer function.

**Comment by joelanford** [comment] 2019-10-29 21:19
The `Deployment.apps` is the operator itself, right? If so, the correct order would be:

1. CustomResourceDefinition.apiextensions.k8s.io
2. Deployment.apps
3. RoleBinding.rbac.authorization.k8s.io
4. Role.rbac.authorization.k8s.io
5. ServiceAccount

Deleting the CRD causes all CRs of that type to be deleted, but if the CR has a finalizer, then the operator still needs to be running. So we would need to make sure that our code waits until the CRDs from step 1 are actually deleted before proceeding to step 2.

**Comment by jmccormick2001** [comment] 2019-10-29 21:31
@joelanford I confirmed that order does indeed work, to the fix here would be to change scorecard to delete in that order it sounds like.

**Comment by mew2057** [comment] 2020-02-17 19:20
/remove-lifecycle stale

This is still very much a problem.

**Comment by jmccormick2001** [comment] 2020-02-24 23:47
fyi, I'm picking this one back up, should have a fix for this in a day or so.  I'll make a change to scorecard's resource cleanup logic to remove the CRD resource first when doing its cleanup....I'll also change the deletion timeout from a hard-coded value to use the --init-timeout configuration setting, this will allow for finalizers to complete before the operator deployment is deleted.

**Comment by jmccormick2001** [comment] 2020-02-25 22:15
ok, the order of deletion was actually ok, but the initTimeout value was not being used in the deletion wait, I've added that, a PR is coming up soon.

**Closed** 2020-02-26 17:44 UTC
Labels: ansible-operator, kind/bug, scorecard, triage/support
